### ISSUE TITLE
 reciprocal is not implemented for type torch.cuda.ByteTensor

### ISSUE THREAD

**Issue by chengchengowen** [jwyang/faster-rcnn.pytorch#116]
Traceback (most recent call last):
  File "trainval_net.py", line 322, in <module>
    rois_label = fasterRCNN(im_data, im_info, gt_boxes, num_boxes)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 371, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 100, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 110, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/parallel_apply.py", line 68, in parallel_apply
    raise output
RuntimeError: reciprocal is not implemented for type torch.cuda.ByteTensor
Exception NameError: "global name 'FileNotFoundError' is not defined" in <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7feb74e19290>> ignored

**Comment by kebijuelun** [comment]
have you found any solutions？I met the same question.
/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 328, in __rdiv__
    return self.reciprocal() * other
RuntimeError: reciprocal is not implemented for type torch.cuda.ByteTensor

**Comment by kebijuelun** [comment]
Use Pytorch 0.3.0 version. It will solve the problem @chengchengowen
