### ISSUE TITLE
error in demo.py

### ISSUE THREAD

**Issue by RichardMrLu** [jwyang/faster-rcnn.pytorch#12]
python demo.py --net vgg16

Traceback (most recent call last):
  File "demo.py", line 152, in <module>
    fasterRCNN = _fasterRCNN(args.net, classes)
  File "/raid/wangw/faster-rcnn.pytorch/lib/model/faster_rcnn/faster_rcnn_cascade.py", line 32, in __init__
    self.RCNN_rpn = _RPN(self.dout_base_model)
  File "/raid/home/wangw/.pyenv/versions/2.7.13/lib/python2.7/site-packages/torch/nn/modules/module.py", line 366, in __getattr__
    type(self).__name__, name))
AttributeError: '_fasterRCNN' object has no attribute 'dout_base_model'

**Comment by jwyang** [comment]
@RichardMrLu , thanks for pointing out this, i will address this issue soon.

**Comment by jwyang** [comment]
Hi, @RichardMrLu , I have updated demo.py. Now it should work fine. Have a try. Note that it can now merely support pascal_voc model. Will add coco soon.

**Comment by RichardMrLu** [comment]
yell, It works wells now! Thanks for your work.

**Comment by jwyang** [comment]
great!
