### ISSUE TITLE
RuntimeError: While copying the parameter named RCNN_rpn.RPN_cls_score.weight, whose dimensions in the model are torch.Size([18, 512, 1, 1]) and whose dimensions in the checkpoint are torch.Size([24, 512, 1, 1]).

### ISSUE THREAD

**Issue by gulcinbaykal** [jwyang/faster-rcnn.pytorch#125]
Hello, I'm a beginner in this field and I'm trying to train the network with my own data set. I created my own file by taking **imagenet.py** file as reference. Then I modified **factory.py**. I tell you my process because maybe I missed an important point. After all, I run **trainval_net.py** file and saved the results. I did not use my whole data set, I just wanted to make sure that my code works and I used very few images just to try. When I run **test_net.py** to try the trained model, this error message shows up: 

> Traceback (most recent call last):
>   File "/home/gulcin/test_net.py", line 176, in <module>
>     fasterRCNN.load_state_dict(checkpoint['model'])
>   File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 519, in load_state_dict
>     .format(name, own_state[name].size(), param.size()))
> RuntimeError: While copying the parameter named RCNN_rpn.RPN_cls_score.weight, whose dimensions in the model are torch.Size([18, 512, 1, 1]) and whose dimensions in the checkpoint are torch.Size([24, 512, 1, 1]).

Did anyone face with a similar problem? Thanks in advance!

**Comment by gulcinbaykal** [comment]
I used the solution that is mentioned in #26 and it worked. Thanks!
