### ISSUE TITLE
RuntimeError: inconsistent tensor sizes at /pytorch/torch/lib/TH/generic/THTensorMath.c:2709

### ISSUE THREAD

**Issue by guyan277** [jwyang/faster-rcnn.pytorch#126]
When running test_net.py this happens, anyone any idea why?

Traceback (most recent call last):
  File "test_net.py", line 232, in <module>
    data = next(data_iter)
  File "/home/guyan/anaconda3/envs/Maxwell2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 179, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/guyan/anaconda3/envs/Maxwell2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 109, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/home/guyan/anaconda3/envs/Maxwell2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 91, in default_collate
    return torch.stack(batch, 0, out=out)
  File "/home/guyan/anaconda3/envs/Maxwell2/lib/python2.7/site-packages/torch/functional.py", line 64, in stack
    return torch.cat(inputs, dim)
RuntimeError: inconsistent tensor sizes at /pytorch/torch/lib/TH/generic/THTensorMath.c:2709

**Comment by jwyang** [comment]
@guyan277 did you try to run test_net.py with batch data? If that's true, now our code does not support this. You should specify the batch size = 1.

**Comment by guyan277** [comment]
@jwyang thx for replying, i have just found that. if i want to test with batch data, where should i modify the code ? the blob.py ?

**Comment by jwyang** [comment]
@guyan277 , In this case, you can use the dalaloader for training data.
