### ISSUE TITLE
cuda running out of memory and testval_net without cuda

### ISSUE THREAD

**Issue by ahmed-shariff** [jwyang/faster-rcnn.pytorch#142]
I keep running into problems with memory. How much memory is needed to run the model on pascal_voc?
I have a GTX 1050 (2GB). I was able to run the `trainval_net`, but the `testval_net` keeps saying it's out of memory. When I try to run the test without cuda, I get different set of errors (`TypeError`, due to `THCudaIntTensor vs THIntTensor`), which I believe are coming from the nms layer as it uses `nms_gpu`
I tried setting the `post_nms_nop_n` to a 30 (and is it ok to go any lower?), and I still am running into problems, even with resnet50.
Any suggestions or workarounds for this problem?

**Running with cuda and `post_nms_top_n` set to 30**
```
python test_net.py --cuda
Called with args:
Namespace(batch_size=1, cfg_file='cfgs/vgg16.yml', checkepoch=1, checkpoint=10021, checksession=1, class_agnostic=False, cuda=True, dataset='pascal_voc', large_scale=False, load_dir='save_dir', mGPUs=False, net='res101', parallel_type=0, set_cfgs=None, vis=False)
Using config:
{'ANCHOR_RATIOS': [0.5, 1, 2],
 'ANCHOR_SCALES': [8, 16, 32],
 'CROP_RESIZE_WITH_MAX_POOL': True,
 'CUDA': False,
 'DATA_DIR': '/media/Files/Research/faster-rcnn.pytorch/data',
 'DEDUP_BOXES': 0.0625,
 'EPS': 1e-14,
 'EXP_DIR': 'default',
 'FEAT_STRIDE': [16],
 'GPU_ID': 0,
 'MATLAB': 'matlab',
 'MAX_NUM_GT_BOXES': 20,
 'MOBILENET': {'DEPTH_MULTIPLIER': 1.0,
               'FIXED_LAYERS': 5,
               'REGU_DEPTH': False,
               'WEIGHT_DECAY': 4e-05},
 'PIXEL_MEANS': array([[[102.9801, 115.9465, 122.7717]]]),
 'POOLING_MODE': 'crop',
 'POOLING_SIZE': 7,
 'RESNET': {'FIXED_BLOCKS': 1, 'MAX_POOL': False},
 'RNG_SEED': 3,
 'ROOT_DIR': '/media/Files/Research/faster-rcnn.pytorch',
 'TEST': {'BBOX_REG': True,
          'HAS_RPN': False,
          'MAX_SIZE': 1000,
          'MODE': 'nms',
          'NMS': 0.3,
          'PROPOSAL_METHOD': 'gt',
          'RPN_MIN_SIZE': 8,
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 30,
          'RPN_PRE_NMS_TOP_N': 1000,
          'RPN_TOP_N': 5000,
          'SCALES': [600],
          'SVM': False},
 'TRAIN': {'ASPECT_GROUPING': False,
           'BATCH_SIZE': 115,
           'BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'BBOX_NORMALIZE_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZE_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_NORMALIZE_TARGETS': True,
           'BBOX_NORMALIZE_TARGETS_PRECOMPUTED': False,
           'BBOX_REG': True,
           'BBOX_THRESH': 0.5,
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.1,
           'BIAS_DECAY': False,
           'BN_TRAIN': False,
           'DISPLAY': 10,
           'DOUBLE_BIAS': True,
           'FG_FRACTION': 0.25,
           'FG_THRESH': 0.5,
           'GAMMA': 0.1,
           'HAS_RPN': True,
           'IMS_PER_BATCH': 1,
           'LEARNING_RATE': 0.001,
           'MAX_SIZE': 1000,
           'MOMENTUM': 0.9,
           'PROPOSAL_METHOD': 'gt',
           'RPN_BATCHSIZE': 256,
           'RPN_BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_MIN_SIZE': 8,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 2000,
           'RPN_PRE_NMS_TOP_N': 12000,
           'SCALES': [600],
           'SNAPSHOT_ITERS': 5000,
           'SNAPSHOT_KEPT': 3,
           'SNAPSHOT_PREFIX': 'res101_faster_rcnn',
           'STEPSIZE': [30000],
           'SUMMARY_INTERVAL': 180,
           'TRIM_HEIGHT': 600,
           'TRIM_WIDTH': 600,
           'TRUNCATED': False,
           'USE_ALL_GT': True,
           'USE_FLIPPED': True,
           'USE_GT': False,
           'WEIGHT_DECAY': 0.0005},
 'USE_GPU_NMS': True}
Loaded dataset `voc_2007_test` for training
Set proposal method: gt
Preparing training data...
voc_2007_test gt roidb loaded from /media/Files/Research/faster-rcnn.pytorch/data/cache/voc_2007_test_gt_roidb.pkl
done
4952 roidb entries
load checkpoint save_dir/res101/pascal_voc/faster_rcnn_1.pth
load model successfully!
test_net.py:191: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  im_data = Variable(im_data, volatile=True)
test_net.py:192: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  im_info = Variable(im_info, volatile=True)
test_net.py:193: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  num_boxes = Variable(num_boxes, volatile=True)
test_net.py:194: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  gt_boxes = Variable(gt_boxes, volatile=True)
/media/Files/Research/faster-rcnn.pytorch/lib/model/rpn/rpn.py:68: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  rpn_cls_prob_reshape = F.softmax(rpn_cls_score_reshape)
/media/Files/Research/faster-rcnn.pytorch/lib/model/faster_rcnn/faster_rcnn.py:98: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  cls_prob = F.softmax(cls_score)
THCudaCheck FAIL file=/home/amsha/builds/pytorch/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "test_net.py", line 243, in <module>
    rois_label = fasterRCNN(im_data, im_info, gt_boxes, num_boxes)
  File "/home/amsha/virtualenv/torch-master-13022018/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/Files/Research/faster-rcnn.pytorch/lib/model/faster_rcnn/faster_rcnn.py", line 47, in forward
    base_feat = self.RCNN_base(im_data)
  File "/home/amsha/virtualenv/torch-master-13022018/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/amsha/virtualenv/torch-master-13022018/lib/python3.6/site-packages/torch/nn/modules/container.py", line 81, in forward
    input = module(input)
  File "/home/amsha/virtualenv/torch-master-13022018/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/amsha/virtualenv/torch-master-13022018/lib/python3.6/site-packages/torch/nn/modules/container.py", line 81, in forward
    input = module(input)
  File "/home/amsha/virtualenv/torch-master-13022018/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/Files/Research/faster-rcnn.pytorch/lib/model/faster_rcnn/resnet.py", line 97, in forward
    residual = self.downsample(x)
  File "/home/amsha/virtualenv/torch-master-13022018/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/amsha/virtualenv/torch-master-13022018/lib/python3.6/site-packages/torch/nn/modules/container.py", line 81, in forward
    input = module(input)
  File "/home/amsha/virtualenv/torch-master-13022018/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/amsha/virtualenv/torch-master-13022018/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 37, in forward
    self.training, self.momentum, self.eps)
  File "/home/amsha/virtualenv/torch-master-13022018/lib/python3.6/site-packages/torch/nn/functional.py", line 1195, in batch_norm
    Variable(running_mean), Variable(running_var), training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: cuda runtime error (2) : out of memory at /home/amsha/builds/pytorch/aten/src/THC/generic/THCStorage.cu:58
```

**Running without cuda:**
```
python test_net.py
Called with args:
Namespace(batch_size=1, cfg_file='cfgs/vgg16.yml', checkepoch=1, checkpoint=10021, checksession=1, class_agnostic=False, cuda=False, dataset='pascal_voc', large_scale=False, load_dir='save_dir', mGPUs=False, net='res101', parallel_type=0, set_cfgs=None, vis=False)
WARNING: You have a CUDA device, so you should probably run with --cuda
Using config:
{'ANCHOR_RATIOS': [0.5, 1, 2],
 'ANCHOR_SCALES': [8, 16, 32],
 'CROP_RESIZE_WITH_MAX_POOL': True,
 'CUDA': False,
 'DATA_DIR': '/media/Files/Research/faster-rcnn.pytorch/data',
 'DEDUP_BOXES': 0.0625,
 'EPS': 1e-14,
 'EXP_DIR': 'default',
 'FEAT_STRIDE': [16],
 'GPU_ID': 0,
 'MATLAB': 'matlab',
 'MAX_NUM_GT_BOXES': 20,
 'MOBILENET': {'DEPTH_MULTIPLIER': 1.0,
               'FIXED_LAYERS': 5,
               'REGU_DEPTH': False,
               'WEIGHT_DECAY': 4e-05},
 'PIXEL_MEANS': array([[[102.9801, 115.9465, 122.7717]]]),
 'POOLING_MODE': 'crop',
 'POOLING_SIZE': 7,
 'RESNET': {'FIXED_BLOCKS': 1, 'MAX_POOL': False},
 'RNG_SEED': 3,
 'ROOT_DIR': '/media/Files/Research/faster-rcnn.pytorch',
 'TEST': {'BBOX_REG': True,
          'HAS_RPN': False,
          'MAX_SIZE': 1000,
          'MODE': 'nms',
          'NMS': 0.3,
          'PROPOSAL_METHOD': 'gt',
          'RPN_MIN_SIZE': 8,
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 30,
          'RPN_PRE_NMS_TOP_N': 1000,
          'RPN_TOP_N': 5000,
          'SCALES': [600],
          'SVM': False},
 'TRAIN': {'ASPECT_GROUPING': False,
           'BATCH_SIZE': 115,
           'BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'BBOX_NORMALIZE_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZE_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_NORMALIZE_TARGETS': True,
           'BBOX_NORMALIZE_TARGETS_PRECOMPUTED': False,
           'BBOX_REG': True,
           'BBOX_THRESH': 0.5,
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.1,
           'BIAS_DECAY': False,
           'BN_TRAIN': False,
           'DISPLAY': 10,
           'DOUBLE_BIAS': True,
           'FG_FRACTION': 0.25,
           'FG_THRESH': 0.5,
           'GAMMA': 0.1,
           'HAS_RPN': True,
           'IMS_PER_BATCH': 1,
           'LEARNING_RATE': 0.001,
           'MAX_SIZE': 1000,
           'MOMENTUM': 0.9,
           'PROPOSAL_METHOD': 'gt',
           'RPN_BATCHSIZE': 256,
           'RPN_BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_MIN_SIZE': 8,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 2000,
           'RPN_PRE_NMS_TOP_N': 12000,
           'SCALES': [600],
           'SNAPSHOT_ITERS': 5000,
           'SNAPSHOT_KEPT': 3,
           'SNAPSHOT_PREFIX': 'res101_faster_rcnn',
           'STEPSIZE': [30000],
           'SUMMARY_INTERVAL': 180,
           'TRIM_HEIGHT': 600,
           'TRIM_WIDTH': 600,
           'TRUNCATED': False,
           'USE_ALL_GT': True,
           'USE_FLIPPED': True,
           'USE_GT': False,
           'WEIGHT_DECAY': 0.0005},
 'USE_GPU_NMS': True}
Loaded dataset `voc_2007_test` for training
Set proposal method: gt
Preparing training data...
voc_2007_test gt roidb loaded from /media/Files/Research/faster-rcnn.pytorch/data/cache/voc_2007_test_gt_roidb.pkl
done
4952 roidb entries
load checkpoint save_dir/res101/pascal_voc/faster_rcnn_1.pth
load model successfully!
test_net.py:191: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  im_data = Variable(im_data, volatile=True)
test_net.py:192: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  im_info = Variable(im_info, volatile=True)
test_net.py:193: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  num_boxes = Variable(num_boxes, volatile=True)
test_net.py:194: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  gt_boxes = Variable(gt_boxes, volatile=True)
/media/Files/Research/faster-rcnn.pytorch/lib/model/rpn/rpn.py:68: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  rpn_cls_prob_reshape = F.softmax(rpn_cls_score_reshape)
Traceback (most recent call last):
  File "test_net.py", line 243, in <module>
    rois_label = fasterRCNN(im_data, im_info, gt_boxes, num_boxes)
  File "/home/amsha/virtualenv/torch-master-13022018/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/Files/Research/faster-rcnn.pytorch/lib/model/faster_rcnn/faster_rcnn.py", line 50, in forward
    rois, rpn_loss_cls, rpn_loss_bbox = self.RCNN_rpn(base_feat, im_info, gt_boxes, num_boxes)
  File "/home/amsha/virtualenv/torch-master-13022018/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/Files/Research/faster-rcnn.pytorch/lib/model/rpn/rpn.py", line 78, in forward
    im_info, cfg_key))
  File "/home/amsha/virtualenv/torch-master-13022018/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/Files/Research/faster-rcnn.pytorch/lib/model/rpn/proposal_layer.py", line 148, in forward
    keep_idx_i = nms(torch.cat((proposals_single, scores_single), 1), nms_thresh)
  File "/media/Files/Research/faster-rcnn.pytorch/lib/model/nms/nms_wrapper.py", line 18, in nms
    return nms_gpu(dets, thresh)
  File "/media/Files/Research/faster-rcnn.pytorch/lib/model/nms/nms_gpu.py", line 10, in nms_gpu
    nms.nms_cuda(keep, dets, num_out, thresh)
  File "/home/amsha/virtualenv/torch-master-13022018/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 199, in safe_call
    result = torch._C._safe_call(*args, **kwargs)
TypeError: initializer for ctype 'struct THCudaIntTensor *' must be a pointer to same type, not cdata 'struct THIntTensor *'
```

edit: added the outputs

**Comment by kyuusaku** [comment]
Hi, did you solve this problem?

**Comment by ahmed-shariff** [comment]
unfortunately, still no.

**Comment by jwyang** [comment]
@ahmed-shariff I think it is because you gpu memory is low, and during testing, you have 300 rois for roi pooling, which takes a lot of memory though. You may want to reduce the number of rois during test, say to 128 instead, which is the number during training.

**Comment by ahmed-shariff** [comment]
That is set by `TEST.RPN_POST_NMS_TOP_N`, right? That is the value i tried setting as low as 30, and still am running into the same problems. I'll keep digging, and see what comes up. 
Also, any suggestions to run the script without cuda?

**Comment by ahmed-shariff** [comment]
Something I still couldn't understand is the purpose of the third value in the `im_info`, what is it used for? When training on my custom dataset I was able to train it without having to set a value for the third slot of `im_info`.

**Comment by dashesy** [comment]
I think there is some memory leak in the code, I added some `del` to delete intermediate variables when not needed then added `torch.cuda.empty_cache()` at the beginning of big for loops and now it proceeds. Now I got a `bad memory access`:

```
    keep = keep[:num_out[0]]
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /opt/conda/conda-bld/pytorch_1524577177097/work/aten/src/THC/generic/THCStorage.c:36
```

But that could be some other error

**Comment by ahmed-shariff** [comment]
@dashesy that sounds like you may have deleted variables still being used?

**Comment by dashesy** [comment]
@ahmed-shariff no, I later realized I had hit another out-of-memory that caused it, used more `del` + `empty_cache` and it went through. It is a memory issue.

**Comment by ahmed-shariff** [comment]
@dashesy you are able to run this code without adjusting any of the configuration parameters on a GPU with 2GB memory?

**Comment by dashesy** [comment]
@ahmed-shariff It is a 1070 (8GB ram) but 1GB is used by X, so with 7GB. I doubt 2GB will be enough.

**Comment by ahmed-shariff** [comment]
Agree :D
I am closing this issue for now. Thus, conclusion: 2GB of GPU ram aint enough to train using this implementation. If I am correct, i'd need atleast 4GB (to run witch batch size 1).
