### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by qinghua2016** [jwyang/faster-rcnn.pytorch#156]
the network can train for some batches. But it occurs the error at line 76 of im = im[:,:,::-1] int the file of minibatch. The error is  as follows:
IndexError: too many indices for array

**Comment by lipka-clazzpl** [comment]
@qinghua2016, in my case partially reverting this [commit](https://github.com/jwyang/faster-rcnn.pytorch/commit/618590347e3b50a3f7fc8b24f078532897adbfaf) for minibatch.py only solved the problem. I've left blob.py intact because of partial revert under this [commit](https://github.com/jwyang/faster-rcnn.pytorch/commit/d64dd6cddf44663aaea1a4abc45d2ac6b7745256).

For some of the images in my dataset  [imread](https://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.imread.html) (from scipy.misc) failed to load the image properly thus the empty image array and IndexError at runtime. This was not the case for PASCAL VOC on which I've did sanity check at first, probably the reason why it didn't surface earlier.

**Comment by qinghua2016** [comment]
Yes, it it because the function of imread, I change it to cv2.imread.

**Comment by fromWRF** [comment]
i have the same issue, did you reslove it?

**Comment by cherishfive** [comment]
Hi@qinghua2016 
I tried to connect to the webcam and perform real-time detection, which can be detected in real time and the frame rate is about 7~8fps. After a while, the following error will occur:
[h264 @ 0x305adc0] negative number of zero coeffs at 24 66
[h264 @ 0x305adc0] error while decoding MB 24 66
.........
Traceback (most recent call last):
   File "demo1.py", line 300, in <module>
     Im = im_in[:,:,::-1]
IndexError: too many indices for array
I also tried changing imread to cv2.imread, but it didn't work. Can you give me some suggestions? Very grateful

**Comment by EMCP** [comment]
openCV reads in a different format than SciPy's `imread`..

Also be careful you are not seeing the alpha channel, for `.png` files I had to drop the alpha channel before training.. unsure about the demo.

**Comment by henderypaul** [comment]
I also meet this problem, and the network can train for some batches:
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/xx/Research/faster-rcnn.pytorch-master/lib/roi_data_layer/roibatchLoader.py", line 67, in __getitem__
    blobs = get_minibatch(minibatch_db, self._num_classes)
  File "/home/xx/Research/faster-rcnn.pytorch-master/lib/roi_data_layer/minibatch.py", line 30, in get_minibatch
    im_blob, im_scales = _get_image_blob(roidb, random_scale_inds)
  File "/home/xx/Research/faster-rcnn.pytorch-master/lib/roi_data_layer/minibatch.py", line 73, in _get_image_blob
    im = im[:,:,::-1]
IndexError: too many indices for array

**Comment by Wangxy1202** [comment]
> Yes, it it because the function of imread, I change it to cv2.imread.
I take this method it can work ,but meet other problem, the train  result  as follow:

WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
[session 1][epoch  1][iter  900/5290] loss: nan, lr: 1.00e-03
                        fg/bg=(128/0), time cost: 20.427851
                        rpn_cls: nan, rpn_box: nan, rcnn_cls: 2.3916, rcnn_box 0.0000

    how to deal with this problem? please give me  help,thank you very much
