### ISSUE TITLE
ImportError: /root/workspace/object-detection/faster-rcnn.pytorch/lib/model/roi_crop/_ext/roi_crop/_roi_crop.so: undefined symbol: state

### ISSUE THREAD

**Issue by HandsomeCao** [jwyang/faster-rcnn.pytorch#159]
When I attempt to train, the problem occured:

`Traceback (most recent call last):
  File "trainval_net.py", line 30, in <module>
    from model.utils.net_utils import weights_normal_init, save_net, load_net, \
  File "/root/workspace/object-detection/faster-rcnn.pytorch/lib/model/utils/net_utils.py", line 8, in <module>
    from model.roi_crop.functions.roi_crop import RoICropFunction
  File "/root/workspace/object-detection/faster-rcnn.pytorch/lib/model/roi_crop/functions/roi_crop.py", line 4, in <module>
    from .._ext import roi_crop
  File "/root/workspace/object-detection/faster-rcnn.pytorch/lib/model/roi_crop/_ext/roi_crop/__init__.py", line 3, in <module>
    from ._roi_crop import lib as _lib, ffi as _ffi
ImportError: /root/workspace/object-detection/faster-rcnn.pytorch/lib/model/roi_crop/_ext/roi_crop/_roi_crop.so: undefined symbol: state`

**Comment by booyoungxu** [comment]
Hello, do you solve it? I also meet this problem.

**Comment by HandsomeCao** [comment]
maybe change the version of pytorch, and compile it again

**Comment by anil-bit** [comment]
hi, guys did you solve this issue?
