### ISSUE TITLE
execution failure, something wrong in rpn

### ISSUE THREAD

**Issue by ntubertchen** [jwyang/faster-rcnn.pytorch#160]
hi, I ran into some trouble running your program.

I was wondering if you can fix this.

under the command python test_net.py --dataset pascal_voc --net res101 --load_dir ./data/pretrained_model --checkpoint 10021 --checksession 1 --checkepoch 7 --cuda
Traceback (most recent call last):
  File "test_net.py", line 246, in <module>
    rois_label = fasterRCNN(im_data, im_info, gt_boxes, num_boxes)
  File "/home/alas79923/miniconda3/envs/visualmodel/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/nfs/home/alas79923/vqa/faster-rcnn.pytorch/lib/model/faster_rcnn/faster_rcnn.py", line 50, in forward
    rois, rpn_loss_cls, rpn_loss_bbox = self.RCNN_rpn(base_feat, im_info, gt_boxes, num_boxes)
  File "/home/alas79923/miniconda3/envs/visualmodel/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/nfs/home/alas79923/vqa/faster-rcnn.pytorch/lib/model/rpn/rpn.py", line 78, in forward
    im_info, cfg_key))
  File "/home/alas79923/miniconda3/envs/visualmodel/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/nfs/home/alas79923/vqa/faster-rcnn.pytorch/lib/model/rpn/proposal_layer.py", line 159, in forward
    output[i,:num_proposal,1:] = proposals_single
RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)

**Comment by super-wcg** [comment]
@ntubertchen do you solve this problem?I have the same problem....

**Comment by Liu-Yicheng** [comment]
There is a bug in the code：lib/model/rpn/proposal_layer.py line150 --- pre_nms_topN < scores_keep.numel() should be pre_nms_topN < scores_single.numel()

**Comment by Liu-Yicheng** [comment]
@super-wcg @ntubertchen I think there is a bug in the code：lib/model/rpn/proposal_layer.py line150 --- pre_nms_topN < scores_keep.numel() should be pre_nms_topN < scores_single.numel()

**Comment by super-wcg** [comment]
delete output[i,:num_proposal,1:] = proposals_single,
then add
            if num_proposal == 0:
                num_proposal = num_proposal + 1
                proposals_single = torch.zeros((1, 4))
            output[i, :num_proposal, 1:] = proposals_single
it works....

**Comment by super-wcg** [comment]
delete output[i,:num_proposal,1:] = proposals_single，change the code as follow:
`#output[i,:num_proposal,1:] = proposals_single    #origin code
 if num_proposal == 0:
        num_proposal = num_proposal + 1
        proposals_single = torch.zeros((1, 4))
 output[i, :num_proposal, 1:] = proposals_single`
