### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by fanwenyuan** [jwyang/faster-rcnn.pytorch#21]
When I was trying to run demo, it said:
ImportError: cannot import name gradgradcheck
The whole log was:
Traceback (most recent call last):
  File "demo.py", line 36, in <module>
    from model.faster_rcnn.vgg16 import vgg16
  File "/home/fanwenyuan/imgs/RFCN-python/faster-rcnn.pytorch/lib/model/faster_rcnn/vgg16.py", line 16, in <module>
    from model.faster_rcnn.faster_rcnn import _fasterRCNN
  File "/home/fanwenyuan/imgs/RFCN-python/faster-rcnn.pytorch/lib/model/faster_rcnn/faster_rcnn.py", line 6, in <module>
    from torch.autograd.gradcheck import gradgradcheck
So what is the package?How can I fix it?thx.

**Comment by jwyang** [comment]
@fanwenyuan ,
I think it is because we are using different pytorch version, mine is 0.2.0, while 0.3.0 does not have torch.autograd.gradcheck.

I have fixed it by removing the imports of gradcheck. you can simply remove those two imports or update your faster_rcnn.py with checkout.
