### ISSUE TITLE
 No module named _nms

### ISSUE THREAD

**Issue by babyjie57** [jwyang/faster-rcnn.pytorch#215]
Looks like in  "/faster-rcnn.pytorch/lib/model/nms/_ext/nms/__init__.py"
the word "from ._nms import lib as _lib, ffi as _ffi"
doesn't work.

**Comment by jwyang** [comment]
@babyjie57 hi, this is much likely that there is a conflict to your cuda version and torch version. could you check which cuda you are using via "nvcc --version", and check whether you are installing the pytorch support the cuda version

**Comment by babyjie57** [comment]
@jwyang Thank you for replying me. My cuda version is 9.1, and I installed pytorch using the command on their website 'conda install pytorch torchvision cuda91 -c pytorch'. I don't really know where is the mistake.

**Comment by jwyang** [comment]
@babyjie57   that's weird, could you post all the error information here?

**Comment by babyjie57** [comment]
@jwyang Thanks for helping me.
I downloaded the pretrained model and use this command to check the demo.
**'python demo.py --net vgg16 --checksession $SESSION --checkepoch $EPOCH --checkpoint $CHECKPOINT --load_dir data/pretrained_model/vgg16_caffe.pth '**
And I got this error:
'Traceback (most recent call last):
  File "demo.py", line 31, in <module>
    from model.nms.nms_wrapper import nms
  File "/home/t-jiew/t-jiew/Video_summary/faster-rcnn.pytorch/lib/model/nms/nms_wrapper.py", line 10, in <module>
    from model.nms.nms_gpu import nms_gpu
  File "/home/t-jiew/t-jiew/Video_summary/faster-rcnn.pytorch/lib/model/nms/nms_gpu.py", line 4, in <module>
    from ._ext import nms
  File "/home/t-jiew/t-jiew/Video_summary/faster-rcnn.pytorch/lib/model/nms/_ext/nms/__init__.py", line 3, in <module>
    from ._nms import lib as _lib, ffi as _ffi
ImportError: No module named _nms'

If I use cpu version, I got the same error like this:
'
Traceback (most recent call last):
  File "demo.py", line 33, in <module>
    from model.utils.net_utils import save_net, load_net, vis_detections
  File "/home/t-jiew/t-jiew/Video_summary/faster-rcnn.pytorch/lib/model/utils/net_utils.py", line 8, in <module>
    from model.roi_crop.functions.roi_crop import RoICropFunction
  File "/home/t-jiew/t-jiew/Video_summary/faster-rcnn.pytorch/lib/model/roi_crop/functions/roi_crop.py", line 4, in <module>
    from .._ext import roi_crop
  File "/home/t-jiew/t-jiew/Video_summary/faster-rcnn.pytorch/lib/model/roi_crop/_ext/roi_crop/__init__.py", line 3, in <module>
    from ._roi_crop import lib as _lib, ffi as _ffi
ImportError: No module named _roi_crop'

**Comment by jwyang** [comment]
@babyjie57 you need to go to lib directory and run

'''
sh make.sh
'''

**Comment by amlandas78** [comment]
I did compile the lib using "sh make.sh". I have "nms_cuda_kernel.cu.o" in my nms/src folder. I still have the same error. It shows "ImportError: No module named _nms". From "faster-rcnn.pytorch/lib/model/nms/_ext/nms/__init__.py", line 3, in <module>
    from ._nms import lib as _lib, ffi as _ffi"

**Comment by zhennaziyu** [comment]
I also had this problem

**Comment by jundeli** [comment]
same problem here.

**Comment by zhoukang123** [comment]
same problem here

**Comment by Uddd821** [comment]
Same problem. How did you solve it?

**Comment by cecilia930426** [comment]
@jundeli @Uddd821 Same problem here. Did you solve it?

**Comment by cs-heibao** [comment]
same error here.

**Comment by jackchen0713** [comment]
+1，I  did compile the lib using "sh make.sh" like @amlandas78 ，but  the problem stall here。

**Comment by OmSDeshmukh** [comment]
I did the same thing but still facing the same issue. Has anyone found the solution
