### ISSUE TITLE
train-issue

### ISSUE THREAD

**Issue by chenhongming** [jwyang/faster-rcnn.pytorch#23]
<img width="669" alt="2018-01-17 9 57 15" src="https://user-images.githubusercontent.com/29920966/35046504-1ec2841a-fbd2-11e7-9ce7-7580ade83646.png">
<img width="670" alt="2018-01-17 10 00 06" src="https://user-images.githubusercontent.com/29920966/35046505-1f14867a-fbd2-11e7-93dd-418c2dbd3f0f.png">
@jwyang Training problems, I tried a lot of ways to solve it but  are not successful. I hope you can help me solve it.

**Comment by chenhongming** [comment]
Loading pretrained weights from data/pretrained_model/resnet101_caffe.pth
/home/priv-lab1/workspace/pytorch_priv/faster-rcnn.pytorch/lib/model/rpn/rpn.py:67: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  rpn_cls_prob_reshape = F.softmax(rpn_cls_score_reshape)
Traceback (most recent call last):
  File "trainval_net.py", line 322, in <module>
    rois_label = fasterRCNN(im_data, im_info, gt_boxes, num_boxes)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/priv-lab1/workspace/pytorch_priv/faster-rcnn.pytorch/lib/model/faster_rcnn/faster_rcnn.py", line 51, in forward
    rois, rpn_loss_cls, rpn_loss_bbox = self.RCNN_rpn(base_feat, im_info, gt_boxes, num_boxes)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/priv-lab1/workspace/pytorch_priv/faster-rcnn.pytorch/lib/model/rpn/rpn.py", line 77, in forward
    im_info, cfg_key))
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/priv-lab1/workspace/pytorch_priv/faster-rcnn.pytorch/lib/model/rpn/proposal_layer.py", line 147, in forward
    keep_idx_i = nms(torch.cat((proposals_single, scores_single), 1), nms_thresh)
  File "/home/priv-lab1/workspace/pytorch_priv/faster-rcnn.pytorch/lib/model/nms/nms_wrapper.py", line 18, in nms
    return nms_gpu(dets, thresh)
  File "/home/priv-lab1/workspace/pytorch_priv/faster-rcnn.pytorch/lib/model/nms/nms_gpu.py", line 9, in nms_gpu
    nms.nms_cuda(keep, dets, num_out, thresh)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/__init__.py", line 180, in safe_call
    result = torch._C._safe_call(*args, **kwargs)
TypeError: initializer for ctype 'struct THCudaIntTensor *' must be a pointer to same type, not cdata 'struct THIntTensor *'
how to solve this problem?thanks for your answer. @jwyang

**Comment by chenhongming** [comment]
Loading pretrained weights from data/pretrained_model/resnet101_caffe.pth
/home/priv-lab1/workspace/pytorch_priv/faster-rcnn.pytorch/lib/model/rpn/rpn.py:67: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  rpn_cls_prob_reshape = F.softmax(rpn_cls_score_reshape)
/home/priv-lab1/workspace/pytorch_priv/faster-rcnn.pytorch/lib/model/faster_rcnn/faster_rcnn.py:99: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  cls_prob = F.softmax(cls_score)
[session 1][epoch  1][iter    0] loss: 4.1766, lr: 1.00e-03
			fg/bg=(9/119), time cost: 1.090616
			rpn_cls: 0.8102, rpn_box: 0.1707, rcnn_cls: 2.9747, rcnn_box 0.2209
[session 1][epoch  1][iter  100] loss: 1.8903, lr: 1.00e-03
			fg/bg=(17/111), time cost: 22.786204
			rpn_cls: 0.0832, rpn_box: 0.0026, rcnn_cls: 0.8636, rcnn_box 0.3705
Is this normal? It's training. @jwyang

**Comment by jwyang** [comment]
@chenhongming  I think it looks good. you can keep training and evaluate it at some point

**Comment by chenhongming** [comment]
Thanks @jwyang
