### ISSUE TITLE
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by TheShadow29** [jwyang/faster-rcnn.pytorch#238]
I am using Pytoch 0.3 and GPU 1080ti. I am unable to figure out why the error is occuring. It seems to be caused by redefinition of `half` somewhere. I have tried more or less all the solutions of other issues unfortunately none of them helped. Any help is appreciated. On another note is it possible to write the cuda kernels in cupy? That would make the installation process much easier.

My make.sh file 
```
export CUDA_PATH=/usr/local/cuda/

python setup.py build_ext --inplace
rm -rf build

CUDA_ARCH="-gencode arch=compute_61,code=sm_61"

# compile NMS
cd model/nms/src
echo "Compiling nms kernels by nvcc..."
$CUDA_PATH/bin/nvcc -c -o nms_cuda_kernel.cu.o nms_cuda_kernel.cu \
					-D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC $CUDA_ARCH

cd ../
python build.py
```

Here is the output of doing sh make.sh

```
running build_ext
skipping 'model/utils/bbox.c' Cython extension (up-to-date)
skipping 'pycocotools/_mask.c' Cython extension (up-to-date)
Compiling nms kernels by nvcc...
Including CUDA code.
/home/arka/Ark_files/pyt-QRC/other_codes/faster-rcnn.pytorch/lib/model/nms
['/home/arka/Ark_files/pyt-QRC/other_codes/faster-rcnn.pytorch/lib/model/nms/src/nms_cuda_kernel.cu.o']
generating /tmp/tmpabero6lh/_nms.c
setting the current directory to '/tmp/tmpabero6lh'
running build_ext
building '_nms' extension
creating home
creating home/arka
creating home/arka/Ark_files
creating home/arka/Ark_files/pyt-QRC
creating home/arka/Ark_files/pyt-QRC/other_codes
creating home/arka/Ark_files/pyt-QRC/other_codes/faster-rcnn.pytorch
creating home/arka/Ark_files/pyt-QRC/other_codes/faster-rcnn.pytorch/lib
creating home/arka/Ark_files/pyt-QRC/other_codes/faster-rcnn.pytorch/lib/model
creating home/arka/Ark_files/pyt-QRC/other_codes/faster-rcnn.pytorch/lib/model/nms
creating home/arka/Ark_files/pyt-QRC/other_codes/faster-rcnn.pytorch/lib/model/nms/src
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/scratch/arka/miniconda3/envs/fastai/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/scratch/arka/miniconda3/envs/fastai/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/scratch/arka/miniconda3/envs/fastai/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/scratch/arka/miniconda3/envs/fastai/include/python3.6m -c _nms.c -o ./_nms.o
In file included from /scratch/arka/miniconda3/envs/fastai/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC/THCBlas.h:5:0,
                 from /scratch/arka/miniconda3/envs/fastai/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC/THC.h:6,
                 from _nms.c:493:
/scratch/arka/miniconda3/envs/fastai/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC/THCHalf.h:18:20: error: conflicting types for ‘half’
 typedef __half_raw half;
                    ^
In file included from /usr/include/cublas_api.h:74:0,
                 from /usr/include/cublas_v2.h:65,
                 from /scratch/arka/miniconda3/envs/fastai/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:11,
                 from /scratch/arka/miniconda3/envs/fastai/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC/THC.h:4,
                 from _nms.c:493:
/usr/include/cuda_fp16.h:93:16: note: previous declaration of ‘half’ was here
 typedef __half half;
                ^
Traceback (most recent call last):
  File "/scratch/arka/miniconda3/envs/fastai/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/scratch/arka/miniconda3/envs/fastai/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/scratch/arka/miniconda3/envs/fastai/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/scratch/arka/miniconda3/envs/fastai/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/arka/miniconda3/envs/fastai/lib/python3.6/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/scratch/arka/miniconda3/envs/fastai/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/scratch/arka/miniconda3/envs/fastai/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/scratch/arka/miniconda3/envs/fastai/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/scratch/arka/miniconda3/envs/fastai/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/scratch/arka/miniconda3/envs/fastai/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/scratch/arka/miniconda3/envs/fastai/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/scratch/arka/miniconda3/envs/fastai/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 38, in <module>
    ffi.build()
  File "/scratch/arka/miniconda3/envs/fastai/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 167, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/scratch/arka/miniconda3/envs/fastai/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 103, in _build_extension
    ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/scratch/arka/miniconda3/envs/fastai/lib/python3.6/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/scratch/arka/miniconda3/envs/fastai/lib/python3.6/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/scratch/arka/miniconda3/envs/fastai/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/scratch/arka/miniconda3/envs/fastai/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1
```

**Comment by TheShadow29** [comment]
I solved it by changing the definition in `/usr/include/cuda_fp16.h` line 93 and commenting out the `ifndef CUDA_NO_HALF` part. After that I was able to compile and the code seems to be working. I am hoping this would not break anything later. Closing this for now.
