### ISSUE TITLE
trainval_net error of loss.backward()

### ISSUE THREAD

**Issue by 1csu** [jwyang/faster-rcnn.pytorch#241]
When the trainval_net.py is processing,an error occurred  as follows:
Traceback (most recent call last):
  File "/media/csu/新加卷/AI Competition/Baidu Competition/intermediary_contest/faster-rcnn.pytorch-master/trainval_net.py", line 316, in <module>
    loss.backward()
  File "/home/csu/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/csu/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
  File "/media/csu/新加卷/AI Competition/Baidu Competition/intermediary_contest/faster-rcnn.pytorch-master/lib/model/roi_align/functions/roi_align.py", line 38, in backward
    assert(self.feature_size is not None and grad_output.is_cuda)
AssertionError
How can I solve the problem?Thanks a lot

**Comment by ssli23** [comment]
I experienced the same problem.can you give me any help?
