### ISSUE TITLE
Type error in trainva_lnet.py

### ISSUE THREAD

**Issue by 1csu** [jwyang/faster-rcnn.pytorch#243]
When the trainval_net is processing,an unexpected error occurred as follows:
Traceback (most recent call last):
  File "/media/csu/新加卷/AI Competition/Baidu Competition/intermediary_contest/faster-rcnn.pytorch-master/trainval_net.py", line 316, in <module>
    loss.backward()
  File "/home/csu/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/csu/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
  File "/media/csu/新加卷/AI Competition/Baidu Competition/intermediary_contest/faster-rcnn.pytorch-master/lib/model/roi_align/functions/roi_align.py", line 51, in backward
    grad_input.cuda())
  File "/home/csu/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 180, in safe_call
    result = torch._C._safe_call(*args, **kwargs)
TypeError: initializer for ctype 'struct THCudaTensor *' must be a pointer to same type, not cdata 'struct THFloatTensor *'
How can find the solution to this problem?Please give me some kindly advice.Thanks a lot

**Comment by jwyang** [comment]
@1scu, are you using gpu? you might need to add --cuda into your command.

**Comment by jwyang** [comment]
you can set the args manually.

**Comment by jwyang** [comment]
@1csu have you solved this problem?

**Comment by markchen2016** [comment]
@jwyang I have the same question when use your project in pytorch 0.3.1 now? Could you please tell me how to handle on this trash specifically?

**Comment by markchen2016** [comment]
I solved the problem by adding --cuda in my terminal. 
Just like this:
CUDA_DEVICES_VISIBLE=1 python train_net.py --cuda

**Comment by kathydo** [comment]
What exactly does adding --cuda to your terminal do ? I have similar problem but my program mistakes it as an argument

**Comment by markchen2016** [comment]
You can type in this way:
'CUDA_VISIBLE_DEVICES=0 python train_net.py --cuda' in your terminal
this is a parser process

**Comment by markchen2016** [comment]
> What exactly does adding --cuda to your terminal do ? I have similar problem but my program mistakes it as an argument

You can type in this way:
'CUDA_VISIBLE_DEVICES=0 python train_net.py --cuda' in your terminal
this is a parser process
