### ISSUE TITLE
How to make annotations for the images without any object?

### ISSUE THREAD

**Issue by cltdevelop** [jwyang/faster-rcnn.pytorch#253]
Hello, thank you very much for sharing this great code.

I encounter a problem when I train this detection model on my own custom dataset. I do not know how to make the annotation for the images without any object? The bbox shoud cover whole images?

**Comment by Worulz** [comment]
@cltdevelop in this particular code, images without annotations is ignored. As seen in the code below. If you just leave them blank that's fine. However if you'd like to use them, you'll have to configure some code. 

https://github.com/jwyang/faster-rcnn.pytorch/blob/28db6d0b313220d200b739f4e22410fbe35529f4/lib/roi_data_layer/roidb.py#L75-L86

**Comment by cltdevelop** [comment]
OK, thank you!

So if I want to use the images without bbox, how to configure this code.

**Comment by Worulz** [comment]
@cltdevelop 
I'm not sure. I haven't done the configurations myself. I just know you'll be starting from this code. Otherwise you can label the annotations a certain class and ignore that class during classification. That's a quick and dirty way. Good luck.

**Comment by srp753** [comment]
I tried to comment out filter_roidb however I get the following error:
`Traceback (most recent call last):
  File "trainval_net.py", line 312, in <module>
    data = next(data_iter)
  File "/home/ubuntu/anaconda3/envs/pytorch_p27/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 188, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/ubuntu/frcnn_sep12/faster-rcnn.pytorch/lib/roi_data_layer/roibatchLoader.py", line 74, in __getitem__
    gt_boxes = torch.from_numpy(blobs['gt_boxes'])
RuntimeError: the given numpy array has zero-sized dimensions. Zero-sized dimensions are not supported in PyTorch
`
I am trying to see how I can add a zero or zero-sized tensor for images having no bounding boxes however I am intrigued by the following piece of code, whether would it create complications given a zero tensor. @jwyang Your guidance on this will be really helpful. 
`
        # check the bounding box:
        not_keep = (gt_boxes[:,0] == gt_boxes[:,2]) | (gt_boxes[:,1] == gt_boxes[:,3])
        keep = torch.nonzero(not_keep == 0).view(-1)

        gt_boxes_padding = torch.FloatTensor(self.max_num_box, gt_boxes.size(1)).zero_()
        if keep.numel() != 0:
            gt_boxes = gt_boxes[keep]
            num_boxes = min(gt_boxes.size(0), self.max_num_box)
            gt_boxes_padding[:num_boxes,:] = gt_boxes[:num_boxes]
        else:
            num_boxes = 0

            # permute trim_data to adapt to downstream processing
        padding_data = padding_data.permute(2, 0, 1).contiguous()
        im_info = im_info.view(3)

        return padding_data, im_info, gt_boxes_padding, num_boxes
    else:
        data = data.permute(0, 3, 1, 2).contiguous().view(3, data_height, data_width)
        im_info = im_info.view(3)

        gt_boxes = torch.FloatTensor([1,1,1,1,1])
        num_boxes = 0

        return data, im_info, gt_boxes, num_boxes
`

**Comment by eugenelet** [comment]
Hey there, is there any solution for this?
