### ISSUE TITLE
IndexError: too many indices for tensor of dimension 1

### ISSUE THREAD

**Issue by 1csu** [jwyang/faster-rcnn.pytorch#258]
I have finished the iteration for 86 times in trainval_net.py,but suddenly index error occurred as follows:
Traceback (most recent call last):
  File "/media/csu/新加卷/AI Competition/Baidu Competition/intermediary_contest/faster-rcnn.pytorch-master/trainval_net.py", line 304, in <module>
    data = next(data_iter)
  File "/home/csu/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 264, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/csu/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 264, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/media/csu/新加卷/AI Competition/Baidu Competition/intermediary_contest/faster-rcnn.pytorch-master/lib/roi_data_layer/roibatchLoader.py", line 190, in __getitem__
    not_keep = (gt_boxes[:,0] == gt_boxes[:,2]) | (gt_boxes[:,1] == gt_boxes[:,3])
IndexError: too many indices for tensor of dimension 1
I don't know what incurs this error.I hope someone can give me some advice to solve this problem.Thanks a lot.

**Comment by TheShadow29** [comment]
Can you check/ print gt_boxes when this error occurs?

**Comment by rkosti** [comment]
@1csu How did you solve this issue?

**Comment by baek85** [comment]
I have same problem, how did you solve it?

**Comment by gaoyao123** [comment]
Please clean up the cache in data.I had tried and it worked.

**Comment by anuragiitg** [comment]
I have also tried and cleared the data cache but its not working

**Comment by gaoyao123** [comment]
Sorry,maybe my solution only worked for my problem.I guess the error occured in data prepocessing process.@anuragiitg

**Comment by charulatalodha** [comment]
Facing the same error:

File "/content/drive/My Drive/fasterrcnn18nov/faster2/repofaster-rcnn-pytorch/lib/roi_data_layer/roibatchLoader.py", line 185, in __getitem__
    gt_boxes[:, :4].clamp_(0, trim_size)
IndexError: too many indices for tensor of dimension 1

**Comment by DengXianqi** [comment]
This problem may be caused by your boxes being "None".
you can check up your boxes, and set a limit before you store the value to boxes.
