### ISSUE TITLE
Getting features for each image region

### ISSUE THREAD

**Issue by claudiogreco** [jwyang/faster-rcnn.pytorch#27]
Hello,

is it possible to use this implementation to get features for each image region like they do in the bottom-up attention model of [Bottom-Up and Top-Down Attention for Image Captioning and Visual Question Answering](https://arxiv.org/pdf/1707.07998.pdf)?

Thank you!

**Comment by jwyang** [comment]
@claudiogreco, Yes, we have that locally. We will add feature extraction part to this repo.

**Comment by claudiogreco** [comment]
Thank you! It would be very useful for my work! Do you roughly know when you will commit this feature?

**Comment by jwyang** [comment]
@claudiogreco ， it will be very soon,  tomorrow or the day after it.

**Comment by claudiogreco** [comment]
Hi @jwyang ,

do you have news about this feature?

Thank you!

**Comment by jiasenlu** [comment]
Hi @claudiogreco I'll try to upload the feature extraction part in 1 or 2 days.

**Comment by dotannn** [comment]
@jiasenlu - any news on this?

**Comment by ObadaJabassini** [comment]
@jiasenlu any new updates?

**Comment by dotannn** [comment]
hey -  I've been able to amend the code for extracting the features pretty easily

in the class **_fasterRCNN** forward method, return also the **pooled_feat** parameter - it contains feature vector of each region proposal.

return statement of _fasterRCNN.forward() :

`        return rois, cls_prob, bbox_pred, rpn_loss_cls, rpn_loss_bbox, RCNN_loss_cls, RCNN_loss_bbox, \
               rois_label, pooled_feat`

**Comment by jwyang** [comment]
Closing this issue for now, thanks for @dotannn !

**Comment by dreamedrainbow** [comment]
> pooled_feat

Hi，there! I also want to get features for each bbox using Faster R-CNN pretrained on Visual Genome, so I tried your method mentioned. But I get the error below surprisingly:
```shell
ssh://zz@10.103.238.164:22./anaconda3/envs/fasterrcnn/bin/python3.6 -u ./faster-rcnn.pytorch-pytorch-1.0/demo.py
Called with args:
Namespace(batch_size=1, cfg_file='cfgs/res101.yml', checkepoch=20, checkpoint=16193, checksession=1, class_agnostic=False, cuda=True, dataset='vg', image_dir='./ImageData/video_validation_0000188', load_dir='./faster-rcnn.pytorch-pytorch-1.0/models', mGPUs=True, net='res101', parallel_type=0, set_cfgs=None, vis=True, webcam_num=-1)
./faster-rcnn.pytorch-pytorch-1.0/lib/model/utils/config.py:374: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yaml_cfg = edict(yaml.load(f))
Using config:
{'ANCHOR_RATIOS': [0.5, 1, 2],
 'ANCHOR_SCALES': [4, 8, 16, 32],
 'CROP_RESIZE_WITH_MAX_POOL': False,
 'CUDA': False,
 'DATA_DIR': './faster-rcnn.pytorch-pytorch-1.0/data',
 'DEDUP_BOXES': 0.0625,
 'EPS': 1e-14,
 'EXP_DIR': 'res101',
 'FEAT_STRIDE': [16],
 'GPU_ID': 0,
 'MATLAB': 'matlab',
 'MAX_NUM_GT_BOXES': 20,
 'MOBILENET': {'DEPTH_MULTIPLIER': 1.0,
               'FIXED_LAYERS': 5,
               'REGU_DEPTH': False,
               'WEIGHT_DECAY': 4e-05},
 'PIXEL_MEANS': array([[[102.9801, 115.9465, 122.7717]]]),
 'POOLING_MODE': 'align',
 'POOLING_SIZE': 7,
 'RESNET': {'FIXED_BLOCKS': 1, 'MAX_POOL': False},
 'RNG_SEED': 3,
 'ROOT_DIR': './faster-rcnn.pytorch-pytorch-1.0',
 'TEST': {'BBOX_REG': True,
          'HAS_RPN': True,
          'MAX_SIZE': 1000,
          'MODE': 'nms',
          'NMS': 0.3,
          'PROPOSAL_METHOD': 'gt',
          'RPN_MIN_SIZE': 16,
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 300,
          'RPN_PRE_NMS_TOP_N': 6000,
          'RPN_TOP_N': 5000,
          'SCALES': [600],
          'SVM': False},
 'TRAIN': {'ASPECT_GROUPING': False,
           'BATCH_SIZE': 128,
           'BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'BBOX_NORMALIZE_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZE_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_NORMALIZE_TARGETS': True,
           'BBOX_NORMALIZE_TARGETS_PRECOMPUTED': True,
           'BBOX_REG': True,
           'BBOX_THRESH': 0.5,
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.0,
           'BIAS_DECAY': False,
           'BN_TRAIN': False,
           'DISPLAY': 20,
           'DOUBLE_BIAS': False,
           'FG_FRACTION': 0.25,
           'FG_THRESH': 0.5,
           'GAMMA': 0.1,
           'HAS_RPN': True,
           'IMS_PER_BATCH': 1,
           'LEARNING_RATE': 0.001,
           'MAX_SIZE': 1000,
           'MOMENTUM': 0.9,
           'PROPOSAL_METHOD': 'gt',
           'RPN_BATCHSIZE': 256,
           'RPN_BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_MIN_SIZE': 8,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 2000,
           'RPN_PRE_NMS_TOP_N': 12000,
           'SCALES': [600],
           'SNAPSHOT_ITERS': 5000,
           'SNAPSHOT_KEPT': 3,
           'SNAPSHOT_PREFIX': 'res101_faster_rcnn',
           'STEPSIZE': [30000],
           'SUMMARY_INTERVAL': 180,
           'TRIM_HEIGHT': 600,
           'TRIM_WIDTH': 600,
           'TRUNCATED': False,
           'USE_ALL_GT': True,
           'USE_FLIPPED': True,
           'USE_GT': False,
           'WEIGHT_DECAY': 0.0001},
 'USE_GPU_NMS': True}
load checkpoint ./faster-rcnn.pytorch-pytorch-1.0/models/res101/vg/faster_rcnn_1_20_16193.pth
load model successfully!
load checkpoint ./faster-rcnn.pytorch-pytorch-1.0/models/res101/vg/faster_rcnn_1_20_16193.pth
Loaded Photo: 341 images.
Traceback (most recent call last):
  File "./faster-rcnn.pytorch-pytorch-1.0/demo.py", line 311, in <module>
    rois_label = fasterRCNN(im_data, im_info, gt_boxes, num_boxes)
ValueError: too many values to unpack (expected 8)
```
Then adjust 
```python
return rois, cls_prob, bbox_pred, rpn_loss_cls, rpn_loss_bbox, RCNN_loss_cls, RCNN_loss_bbox, rois_label
```
to
```python
return rois, cls_prob, bbox_pred, rpn_loss_cls, rpn_loss_bbox, RCNN_loss_cls, RCNN_loss_bbox, pooled_feat
```
It turns out correct, but still can‘t find the feature of bbox and where the output dir definnition of the feature. How can I solve the  problem?

**Comment by dreamedrainbow** [comment]
> hey - I've been able to amend the code for extracting the features pretty easily
> 
> in the class **_fasterRCNN** forward method, return also the **pooled_feat** parameter - it contains feature vector of each region proposal.
> 
> return statement of _fasterRCNN.forward() :
> 
> ` return rois, cls_prob, bbox_pred, rpn_loss_cls, rpn_loss_bbox, RCNN_loss_cls, RCNN_loss_bbox, rois_label, **pooled_feat**`



> hey - I've been able to amend the code for extracting the features pretty easily
> 
> in the class **_fasterRCNN** forward method, return also the **pooled_feat** parameter - it contains feature vector of each region proposal.
> 
> return statement of _fasterRCNN.forward() :
> 
> ` return rois, cls_prob, bbox_pred, rpn_loss_cls, rpn_loss_bbox, RCNN_loss_cls, RCNN_loss_bbox, rois_label, **pooled_feat**`

> pooled_feat

Hi，there! I also want to get features for each bbox using Faster R-CNN pretrained on Visual Genome, so I tried your method mentioned. But I get the error below surprisingly:
```shell
ssh://zz@10.103.238.164:22./anaconda3/envs/fasterrcnn/bin/python3.6 -u ./faster-rcnn.pytorch-pytorch-1.0/demo.py
Called with args:
Namespace(batch_size=1, cfg_file='cfgs/res101.yml', checkepoch=20, checkpoint=16193, checksession=1, class_agnostic=False, cuda=True, dataset='vg', image_dir='./ImageData/video_validation_0000188', load_dir='./faster-rcnn.pytorch-pytorch-1.0/models', mGPUs=True, net='res101', parallel_type=0, set_cfgs=None, vis=True, webcam_num=-1)
./faster-rcnn.pytorch-pytorch-1.0/lib/model/utils/config.py:374: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yaml_cfg = edict(yaml.load(f))
Using config:
{'ANCHOR_RATIOS': [0.5, 1, 2],
 'ANCHOR_SCALES': [4, 8, 16, 32],
 'CROP_RESIZE_WITH_MAX_POOL': False,
 'CUDA': False,
 'DATA_DIR': './faster-rcnn.pytorch-pytorch-1.0/data',
 'DEDUP_BOXES': 0.0625,
 'EPS': 1e-14,
 'EXP_DIR': 'res101',
 'FEAT_STRIDE': [16],
 'GPU_ID': 0,
 'MATLAB': 'matlab',
 'MAX_NUM_GT_BOXES': 20,
 'MOBILENET': {'DEPTH_MULTIPLIER': 1.0,
               'FIXED_LAYERS': 5,
               'REGU_DEPTH': False,
               'WEIGHT_DECAY': 4e-05},
 'PIXEL_MEANS': array([[[102.9801, 115.9465, 122.7717]]]),
 'POOLING_MODE': 'align',
 'POOLING_SIZE': 7,
 'RESNET': {'FIXED_BLOCKS': 1, 'MAX_POOL': False},
 'RNG_SEED': 3,
 'ROOT_DIR': './faster-rcnn.pytorch-pytorch-1.0',
 'TEST': {'BBOX_REG': True,
          'HAS_RPN': True,
          'MAX_SIZE': 1000,
          'MODE': 'nms',
          'NMS': 0.3,
          'PROPOSAL_METHOD': 'gt',
          'RPN_MIN_SIZE': 16,
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 300,
          'RPN_PRE_NMS_TOP_N': 6000,
          'RPN_TOP_N': 5000,
          'SCALES': [600],
          'SVM': False},
 'TRAIN': {'ASPECT_GROUPING': False,
           'BATCH_SIZE': 128,
           'BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'BBOX_NORMALIZE_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZE_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_NORMALIZE_TARGETS': True,
           'BBOX_NORMALIZE_TARGETS_PRECOMPUTED': True,
           'BBOX_REG': True,
           'BBOX_THRESH': 0.5,
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.0,
           'BIAS_DECAY': False,
           'BN_TRAIN': False,
           'DISPLAY': 20,
           'DOUBLE_BIAS': False,
           'FG_FRACTION': 0.25,
           'FG_THRESH': 0.5,
           'GAMMA': 0.1,
           'HAS_RPN': True,
           'IMS_PER_BATCH': 1,
           'LEARNING_RATE': 0.001,
           'MAX_SIZE': 1000,
           'MOMENTUM': 0.9,
           'PROPOSAL_METHOD': 'gt',
           'RPN_BATCHSIZE': 256,
           'RPN_BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_MIN_SIZE': 8,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 2000,
           'RPN_PRE_NMS_TOP_N': 12000,
           'SCALES': [600],
           'SNAPSHOT_ITERS': 5000,
           'SNAPSHOT_KEPT': 3,
           'SNAPSHOT_PREFIX': 'res101_faster_rcnn',
           'STEPSIZE': [30000],
           'SUMMARY_INTERVAL': 180,
           'TRIM_HEIGHT': 600,
           'TRIM_WIDTH': 600,
           'TRUNCATED': False,
           'USE_ALL_GT': True,
           'USE_FLIPPED': True,
           'USE_GT': False,
           'WEIGHT_DECAY': 0.0001},
 'USE_GPU_NMS': True}
load checkpoint ./faster-rcnn.pytorch-pytorch-1.0/models/res101/vg/faster_rcnn_1_20_16193.pth
load model successfully!
load checkpoint ./faster-rcnn.pytorch-pytorch-1.0/models/res101/vg/faster_rcnn_1_20_16193.pth
Loaded Photo: 341 images.
Traceback (most recent call last):
  File "./faster-rcnn.pytorch-pytorch-1.0/demo.py", line 311, in <module>
    rois_label = fasterRCNN(im_data, im_info, gt_boxes, num_boxes)
ValueError: too many values to unpack (expected 8)
```
Then adjust 
```python
return rois, cls_prob, bbox_pred, rpn_loss_cls, rpn_loss_bbox, RCNN_loss_cls, RCNN_loss_bbox, rois_label
```
to
```python
return rois, cls_prob, bbox_pred, rpn_loss_cls, rpn_loss_bbox, RCNN_loss_cls, RCNN_loss_bbox, pooled_feat
```
It turns out correct, but still can‘t find the feature of bbox and where the output dir definnition of the feature. How can I solve the  problem?
