### ISSUE TITLE
if 'caption' in anns[0]: IndexError: list index out of range

### ISSUE THREAD

**Issue by Darkknight0425** [jwyang/faster-rcnn.pytorch#284]
After I trained this model using coco dataset, I encountered some problems while I'm testing it. Actually the testing process has already completed, and there's something wrong  while showing the results.

Could anyone please help me? Thx~

**Writing results json to /mnt/lustre/jihaorui/detection/faster-rcnn.pytorch/pascal_voc/output/res101/coco_2014_minival/faster_rcnn_10/detections_minival2014_results.json
Loading and preparing results...
Traceback (most recent call last):
  File "test_net.py", line 323, in <module>
    imdb.evaluate_detections(all_boxes, output_dir)
  File "/mnt/lustre/jihaorui/detection/faster-rcnn.pytorch/pascal_voc/lib/datasets/coco.py", line 314, in evaluate_detections
    self._do_detection_eval(res_file, output_dir)
  File "/mnt/lustre/jihaorui/detection/faster-rcnn.pytorch/pascal_voc/lib/datasets/coco.py", line 256, in _do_detection_eval
    coco_dt = self._COCO.loadRes(res_file)
  File "/mnt/lustre/jihaorui/detection/faster-rcnn.pytorch/pascal_voc/data/coco/PythonAPI/pycocotools/coco.py", line 315, in loadRes
    if 'caption' in anns[0]:
IndexError: list index out of range**

**Comment by jwyang** [comment]
@Darkknight0425 you are using python 3.6, right? I think this is because there are something wrong when using coco api with python 3.

**Comment by Darkknight0425** [comment]
Cool~ I switched my python version to 2.7 and everything works out fine, thank you~

**Comment by zcl912** [comment]
@jwyang hello, I meet the same issue when i upload the result to the  coco online evaluation, the details is as follow:
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
/opt/conda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "/tmp/codalab/tmpyOj6bJ/run/program/run_test.py", line 76, in <module>
    cocoDt=cocoGt.loadRes(dets)
  File "/tmp/codalab/tmpyOj6bJ/run/program/pycocokp/coco.py", line 305, in loadRes
    if 'caption' in anns[0]:
IndexError: list index out of range

it is already with python2,can you help me?

**Comment by litingsjj** [comment]
@zcl912 Same problem！Have you fixed it?

**Comment by Rmuli** [comment]
Same problem as for me！How to solve it?

**Comment by Rmuli** [comment]
我知道怎么解决了.... 在eval阶段，设置命令-language_eval 0....如果-language_eval  1, 会报错：    if 'caption' in anns[0]:
IndexError: list index out of range

**Comment by 1209805200** [comment]
> 我知道怎么解决了.... 在eval阶段，设置命令-language_eval 0....如果-language_eval 1, 会报错： if 'caption' in anns[0]:
> IndexError: list index out of range

什么意思？

**Comment by Apsu95** [comment]
has anyone fixed this?

**Comment by aaag97** [comment]
I have the same issue, has anyone managed to fix it?

**Comment by BudingZ** [comment]
has anyone fixed? it works when I test  with maskscoring rcnn model,but it has this error when I run with mask scoring rcnn model.
