### ISSUE TITLE
RuntimeError: dimension specified as 0 but tensor has no dimensions.

### ISSUE THREAD

**Issue by JerryLauzzz** [jwyang/faster-rcnn.pytorch#296]
I want to fine-tuning from your model ```faster_rcnn_1_10_14657.pth```. I run the following command
```bash
python trainval_net.py --dataset coco \
 --nw 5 --bs 15 \
--net res101  --cuda \
--r True --checkepoch 10 --checkpoint 14657 --mGPUs
```
I get the error:
```
Traceback (most recent call last):
  File "trainval_net.py", line 320, in <module>
    rois_label = fasterRCNN(im_data, im_info, gt_boxes, num_boxes)
  File "/home/dell/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dell/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 115, in forward
    return self.gather(outputs, self.output_device)
  File "/home/dell/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 127, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/home/dell/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 68, in gather
    return gather_map(outputs)
  File "/home/dell/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/home/dell/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 55, in gather_map
    return Gather.apply(target_device, dim, *outputs)
  File "/home/dell/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 54, in forward
    ctx.input_sizes = tuple(map(lambda i: i.size(ctx.dim), inputs))
  File "/home/dell/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 54, in <lambda>
    ctx.input_sizes = tuple(map(lambda i: i.size(ctx.dim), inputs))
RuntimeError: dimension specified as 0 but tensor has no dimensions
```
My pytorch version is 0.4.0.

**Comment by jwyang** [comment]
@JerryLauzzz were you able to test this model?

**Comment by JerryLauzzz** [comment]
Yes. wizardliu 邮箱：wizardliu@t.shu.edu.cn 签名由 网易邮箱大师 定制 On 09/07/2018 01:45, Jianwei Yang wrote: @JerryLauzzz were you able to test this model? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by merryImage** [comment]
I suffer from same error.

**Comment by Kinpzz** [comment]
see issue #226

**Comment by JerryLauzzz** [comment]
I tried the [solution](https://github.com/jwyang/faster-rcnn.pytorch/issues/226#issuecomment-402459343). Another error occured:
```
Traceback (most recent call last):
  File "trainval_net.py", line 331, in <module>
    optimizer.step()
  File "/home/dell/anaconda3/lib/python3.6/site-packages/torch/optim/sgd.py", line 101, in step
    buf.mul_(momentum).add_(1 - dampening, d_p)
RuntimeError: The expanded size of the tensor (512) must match the existing size (1024) at non-singleton dimension 1
```
Maybe I should open a new issue?

**Comment by Kinpzz** [comment]
@JerryLauzzz 
My environment is 
`python=3.6.5`
`pytorch=0.4.0 with cuda-9.0 and cudnn-v7'
It seems a bug of pytorch 0.4.0 using multiple GPUs. But this solution solved my problem `RuntimeError: dimension specified as 0 but tensor has no dimensions`

**Comment by JerryLauzzz** [comment]
Yes, the solution solved the titled problem. 
I think it's a bug either... If there is no update about this problem, I will close the issue.

**Comment by dmortem** [comment]
Hi, @JerryLauzzz 
Does multiple GPUs speed up the training process? I have tried the solution, but the speed is the same as the speed with only one GPU. And my GPU util is only 0%-2%. Are you the same as me? Thank you!
