### ISSUE TITLE
batchsize>1 fail for smaller models?(eg resnet50)

### ISSUE THREAD

**Issue by kentaroy47** [jwyang/faster-rcnn.pytorch#297]
While trying to train with smaller models like resnet50, batchsize>1 seems to fail.
have anyone experienced same probloms? batchsize==1 works fine and resnet101 works with larger batchsize.

```
Preparing training data...
done
{'misc': 9, 'person': 5, 'van': 3, 'bg': 0, 'cyclist': 7, 'tram': 8, 'person_sitting': 6, 'car': 2, 'dontcare': 1, 'truck': 4}
before filtering, there are 14962 images...
after filtering, there are 14962 images...
14962 roidb entries
Loading pretrained weights from data/pretrained_model/resnet50-19c8e357.pth
error in BilinearSampler.updateOutput: invalid argument
Traceback (most recent call last):
  File "trainval_net.py", line 349, in <module>
    rois_label = fasterRCNN(im_data, im_info, gt_boxes, num_boxes)
  File "/home/ken/miniconda3/envs/pytorch/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/pytorch/faster-rcnn.pytorch/lib/model/faster_rcnn/faster_rcnn.py", line 77, in forward
    pooled_feat = self.RCNN_roi_crop(base_feat, Variable(grid_yx).detach())
  File "/pytorch/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/preprocess_data_ed/brainage/rev7_brainage_dec25_single_mode_ken/keras/pytorch/faster-rcnn.pytorch/lib/model/roi_crop/modules/roi_crop.py", line 8, in forward
    return RoICropFunction()(input1, input2)
  File "/pytorch/faster-rcnn.pytorch/lib/model/roi_crop/functions/roi_crop.py", line 14, in forward
    roi_crop.BilinearSamplerBHWD_updateOutput_cuda(input1, input2, output)
  File "/home/ken/miniconda3/envs/pytorch/lib/python3.5/site-packages/torch/utils/ffi/__init__.py", line 197, in safe_call
    result = torch._C._safe_call(*args, **kwargs)
torch.FatalError: aborting at /data/preprocess_data_ed/brainage/rev7_brainage_dec25_single_mode_ken/keras/pytorch/faster-rcnn.pytorch/lib/model/roi_crop/src/roi_crop_cuda.c:49
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f7d489e6128>>
Traceback (most recent call last):
  File "/home/ken/miniconda3/envs/pytorch/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 349, in __del__
  File "/home/ken/miniconda3/envs/pytorch/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 328, in _shutdown_workers
  File "/home/ken/miniconda3/envs/pytorch/lib/python3.5/multiprocessing/queues.py", line 337, in get
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 887, in _find_spec
TypeError: 'NoneType' object is not iterable
[6]+  Killed                  python trainval_net.py --dataset pascal_voc --net res101 --cuda --r True --checkepoch 4 --checkpoint 2492 --epoch 50 --bs 6 --nw 6
```

**Comment by jwyang** [comment]
@kentaroy47 what if you use roi_pooling instead of roi_crop?

**Comment by kentaroy47** [comment]
Thanks!
using "pool" fixed my problem. Helps alot :)
