### ISSUE TITLE
torch.FatalError: invalid argument 2: out of range at /pytorch/aten/src/THC/generic/THCTensor.c:23

### ISSUE THREAD

**Issue by hongdayu** [jwyang/faster-rcnn.pytorch#311]
![image](https://user-images.githubusercontent.com/32477868/45662213-9148e580-bb33-11e8-981c-c7f963ebb1c1.png)

**Comment by hongdayu** [comment]
how to resolve this problem?

**Comment by jwyang** [comment]
@hongdayu it might because the rois exceed the input feature map. set a breakpoint to see when this happens.

**Comment by liveway6** [comment]
Hi, can you fixed this problem? Thanks.

**Comment by hongdayu** [comment]
> Hi, can you fixed this problem? Thanks.
![image](https://user-images.githubusercontent.com/32477868/45915783-d51e5080-be8d-11e8-9d85-3e94f4f7c1a8.png)

this is my solution

**Comment by liveway6** [comment]
Thank for your reply. this code lied in lib/model/fpn/fpn.py 131 and 147 ？ I follow you, but another problem is occur:

Traceback (most recent call last):
  File "trainval_net.py", line 324, in <module>
    data = data_iter.next()
  File "/home/wangshaoju/.conda/envs/ycy/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 264, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/wangshaoju/.conda/envs/ycy/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 264, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/wangshaoju/jwyang/fpn.pytorch/lib/roi_data_layer/roibatchLoader.py", line 150, in __getitem__
    gt_boxes[:, 0] = gt_boxes[:, 0] - x_s
TypeError: sub() received an invalid combination of arguments - got (numpy.int64), but expected one of:
 * (Tensor other, float alpha)
 * (float other, float alpha)

Thanks!

**Comment by hongdayu** [comment]
> Thank for your reply. this code lied in lib/model/fpn/fpn.py 131 and 147 ？ I follow you, but another problem is occur:
> 
> Traceback (most recent call last):
> File "trainval_net.py", line 324, in 
> data = data_iter.next()
> File "/home/wangshaoju/.conda/envs/ycy/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 264, in **next**
> batch = self.collate_fn([self.dataset[i] for i in indices])
> File "/home/wangshaoju/.conda/envs/ycy/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 264, in 
> batch = self.collate_fn([self.dataset[i] for i in indices])
> File "/home/wangshaoju/jwyang/fpn.pytorch/lib/roi_data_layer/roibatchLoader.py", line 150, in **getitem**
> gt_boxes[:, 0] = gt_boxes[:, 0] - x_s
> TypeError: sub() received an invalid combination of arguments - got (numpy.int64), but expected one of:
> 
> * (Tensor other, float alpha)
> * (float other, float alpha)
> 
> Thanks!
the error 
TypeError! The error occurred during the data loading phase.. the type of  x_s   is numpy.int64 , not tensor or float

**Comment by hongdayu** [comment]
> > Thank for your reply. this code lied in lib/model/fpn/fpn.py 131 and 147 ？ I follow you, but another problem is occur:
> > Traceback (most recent call last):
> > File "trainval_net.py", line 324, in
> > data = data_iter.next()
> > File "/home/wangshaoju/.conda/envs/ycy/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 264, in **next**
> > batch = self.collate_fn([self.dataset[i] for i in indices])
> > File "/home/wangshaoju/.conda/envs/ycy/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 264, in
> > batch = self.collate_fn([self.dataset[i] for i in indices])
> > File "/home/wangshaoju/jwyang/fpn.pytorch/lib/roi_data_layer/roibatchLoader.py", line 150, in **getitem**
> > gt_boxes[:, 0] = gt_boxes[:, 0] - x_s
> > TypeError: sub() received an invalid combination of arguments - got (numpy.int64), but expected one of:
> > 
> > * (Tensor other, float alpha)
> > * (float other, float alpha)
> > 
> > Thanks!
> > the error
> > TypeError! The error occurred during the data loading phase.. the type of  x_s   is numpy.int64 , not tensor or float


![Uploading image.png…]()


> > Thank for your reply. this code lied in lib/model/fpn/fpn.py 131 and 147 ？ I follow you, but another problem is occur:
> > Traceback (most recent call last):
> > File "trainval_net.py", line 324, in
> > data = data_iter.next()
> > File "/home/wangshaoju/.conda/envs/ycy/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 264, in **next**
> > batch = self.collate_fn([self.dataset[i] for i in indices])
> > File "/home/wangshaoju/.conda/envs/ycy/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 264, in
> > batch = self.collate_fn([self.dataset[i] for i in indices])
> > File "/home/wangshaoju/jwyang/fpn.pytorch/lib/roi_data_layer/roibatchLoader.py", line 150, in **getitem**
> > gt_boxes[:, 0] = gt_boxes[:, 0] - x_s
> > TypeError: sub() received an invalid combination of arguments - got (numpy.int64), but expected one of:
> > 
> > * (Tensor other, float alpha)
> > * (float other, float alpha)
> > 
> > Thanks!
> > the error
> > TypeError! The error occurred during the data loading phase.. the type of  x_s   is numpy.int64 , not tensor or float


> > Thank for your reply. this code lied in lib/model/fpn/fpn.py 131 and 147 ？ I follow you, but another problem is occur:
> > Traceback (most recent call last):
> > File "trainval_net.py", line 324, in
> > data = data_iter.next()
> > File "/home/wangshaoju/.conda/envs/ycy/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 264, in **next**
> > batch = self.collate_fn([self.dataset[i] for i in indices])
> > File "/home/wangshaoju/.conda/envs/ycy/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 264, in
> > batch = self.collate_fn([self.dataset[i] for i in indices])
> > File "/home/wangshaoju/jwyang/fpn.pytorch/lib/roi_data_layer/roibatchLoader.py", line 150, in **getitem**
> > gt_boxes[:, 0] = gt_boxes[:, 0] - x_s
> > TypeError: sub() received an invalid combination of arguments - got (numpy.int64), but expected one of:
> > 
> > * (Tensor other, float alpha)
> > * (float other, float alpha)
> > 
> > Thanks!
> > the error
> > TypeError! The error occurred during the data loading phase.. the type of  x_s   is numpy.int64 , not tensor or float

float(x_s)

**Comment by Karthik-Suresh93** [comment]
Hi @hongdayu @liveway6, did you solve this issue? If so, can you please elaborate on the solution?

**Comment by Forgetmyfairy** [comment]
@hongdayu @jwyang @liveway6 @Karthik-Suresh93 @severian I changed the code :idx_l = (roi_level == l).nonzero().view(-1) , but the error still exit. Could you tell me how to fix it. Help!!!

**Comment by Marcus208** [comment]
> @hongdayu @jwyang @liveway6 @Karthik-Suresh93 @severian I changed the code :idx_l = (roi_level == l).nonzero().view(-1) , but the error still exit. Could you tell me how to fix it. Help!!!

i have used your method and it works
