### ISSUE TITLE
can't train with cpu only

### ISSUE THREAD

**Issue by SnowyJune973** [jwyang/faster-rcnn.pytorch#323]
Because of some certain reason, I want to train the model with small data on a PC with no GPU. But Python gave me an AssertionError as I found here.
```
Traceback (most recent call last):
  File "/home/snowyjune/local/faster-rcnn.pytorch/faster-rcnn.pytorch/trainval_net.py", line 336, in <module>
    loss.backward()

  File "/home/snowyjune/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)

  File "/home/snowyjune/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag

  File "/home/snowyjune/local/faster-rcnn.pytorch/faster-rcnn.pytorch/lib/model/roi_align/functions/roi_align.py", line 38, in backward
    assert((self.feature_size is not None) and (grad_output.is_cuda))

AssertionError
```
It seems that the program is designed not to support training with CPU. Is that true?

**Comment by SnowyJune973** [comment]
If not, how could I run the code properly with CPU only? Thanks so much!

**Comment by SnowyJune973** [comment]
> @SnowyJune973 please use roi_pooling instead of roi_align

I added cfg.POOLING_MODE = 'pool' under Line 260 of trainval_net.py, and ran trainval_net.py again with arguments '--bs 1', but it still didn't work.

Python still gave me the same AssertionError, but this time it came from roi_pool.py

```

Traceback (most recent call last):
  File "trainval_net.py", line 333, in <module>
    loss.backward()
  File "/home/cch/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/cch/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/cch/faster-rcnn.pytorch/lib/model/roi_pooling/functions/roi_pool.py", line 31, in backward
    assert(ctx.feature_size is not None and grad_output.is_cuda)
AssertionError
```

**Comment by jwyang** [comment]
@SnowyJune973 I will change some code, will let you know when it works.

**Comment by SnowyJune973** [comment]
I'm sorry for the inconvenience.

**Comment by SnowyJune973** [comment]
> @SnowyJune973 I will change some code, will let you know when it works.

I'm so sorry for the inconvenience.

**Comment by jihwan1008** [comment]
@SnowyJune973  Sorry to bother, but did you succeeded in 'sh make.sh'? Didn't you get any cffi errors?

**Comment by kangkang59812** [comment]
@SnowyJune973 Does it work when traing a small dataset with CPU only?

**Comment by simomagi** [comment]
I have the same problem.  For some testing purpose, i'm not able to train  faster R-CNN  on a CPU only machine. I have cffi errors when i run "sh make.sh". How can i solve it?

**Comment by ZiyuBao** [comment]
Same as @jihwan1008 and @simomagi, I was working in MacOS with CPU only and trying to run sh make.sh but got a cffi error (cffi.VerificationError: LinkError: command 'gcc' failed with exit status 1). What can I do with it? Issue #678

**Comment by mekong0404** [comment]
Same as @jihwan1008 and @simomagi, I was working in MacOS with CPU only and trying to run sh make.sh but got a cffi error (cffi.VerificationError: LinkError: command 'gcc' failed with exit status 1). 
please advice

**Comment by mekong0404** [comment]
sorry for trouble , but when I check for gcc by putting gcc --version 

onfigured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

what should I do

**Comment by ZiyuBao** [comment]
It says clang there. I think that's what he meant. You probably cannot get CPU-only mode running. I am now turning into clusters

**Comment by EMCP** [comment]
Right... See the line where it says Clang .. hence GCC isn't quite what you
have here in OSX.. I'm unsure how to proceed other than look up how to
install proper GCC somehow, without messing with the Mac Clang "GCC"

**Comment by dionisole** [comment]
Same problem here. I tried to train the resnet18 from the pytorch examples and it gives me the assertion error  for the nvidia driver even if the args.gpu is None. Any thoughts?

**Comment by loolzaaa** [comment]
This implementation for PyTorch 1.0 cannot be run for CPU, some source are not exist. If you want to train on CPU only, you can try [my implementation of this network](https://github.com/loolzaaa/faster-rcnn-pytorch)

**Comment by EMCP** [comment]
if you're using COCO based datasets and resnet 101, you can give my implementation a try https://github.com/EMCP/faster-rcnn.pytorch
