### ISSUE TITLE
 dynamic module does not define module export function (PyInit_cython_bbox)

### ISSUE THREAD

**Issue by yimingGS** [jwyang/faster-rcnn.pytorch#340]
I tried to run demo.py. And the following mistake occur :

Traceback (most recent call last):
  File "demo.py", line 27, in <module>
    from roi_data_layer.roidb import combined_roidb
  File "/home/andy/sym/faster-rcnn.pytorch/lib/roi_data_layer/roidb.py", line 9, in <module>
    from datasets.factory import get_imdb
  File "/home/andy/sym/faster-rcnn.pytorch/lib/datasets/factory.py", line 14, in <module>
    from datasets.pascal_voc import pascal_voc
  File "/home/andy/sym/faster-rcnn.pytorch/lib/datasets/pascal_voc.py", line 23, in <module>
    from .imdb import imdb
  File "/home/andy/sym/faster-rcnn.pytorch/lib/datasets/imdb.py", line 14, in <module>
    from model.utils.cython_bbox import bbox_overlaps
ImportError: dynamic module does not define module export function (PyInit_cython_bbox)

Anyone met the same question? Thanks!

**Comment by jwyang** [comment]
@yimingGS have you run sh make.sh to compile python_bbox?

**Comment by yimingGS** [comment]
@jwyang  I have run make.sh, and find cython_bbox.so successfully. But this mistake still occured. 
 
After that, I searched the mistake and find there's another idea that it's due to the name's mismatching for cython_bbox & bbox. So I modified 'cython_bbox' to 'bbox'  in the code, and the mistake disappered. But I don't know whether this operation is reasonable~
