### ISSUE TITLE
AttributeError: 'int' object has no attribute 'item'

### ISSUE THREAD

**Issue by h510166404** [jwyang/faster-rcnn.pytorch#354]
6468 roidb entries
Loading pretrained weights from data/pretrained_model/resnet101_caffe.pth
Traceback (most recent call last):
  File "trainval_net.py", line 320, in <module>
    rois_label = fasterRCNN(im_data, im_info, gt_boxes, num_boxes)
  File "/home/hyc/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hyc/faster-rcnn.pytorch-master/lib/model/faster_rcnn/faster_rcnn.py", line 50, in forward
    rois, rpn_loss_cls, rpn_loss_bbox = self.RCNN_rpn(base_feat, im_info, gt_boxes, num_boxes)
  File "/home/hyc/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hyc/faster-rcnn.pytorch-master/lib/model/rpn/rpn.py", line 87, in forward
    rpn_data = self.RPN_anchor_target((rpn_cls_score.data, gt_boxes, im_info, num_boxes))
  File "/home/hyc/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hyc/faster-rcnn.pytorch-master/lib/model/rpn/anchor_target_layer.py", line 157, in forward
    positive_weights = 1.0 / num_examples.item()
AttributeError: 'int' object has no attribute 'item'

**Comment by h510166404** [comment]
when i train my own dataset with coco api,i meet this error.

**Comment by jwyang** [comment]
@h510166404 please check your pytorch version, now it is with 0.4.0
