### ISSUE TITLE
90 Rotation Data Augmentation

### ISSUE THREAD

**Issue by wheemyungshin** [jwyang/faster-rcnn.pytorch#367]
I added some codes to try 90' rotation right after horizontal flip. But i don't know why my code doesn't work now.

###  train_val.net:
  cfg.TRAIN.USE_FLIPPED = True
  cfg.TRAIN.USE_90ROTATION = True
  cfg.USE_GPU_NMS = args.cuda
  #print("\n name: ", args.imdb_name)
  imdb, roidb, ratio_list, ratio_index = combined_roidb(args.imdb_name)

  ### def get_training_roidb(imdb):
    """Returns a roidb (Region of Interest database) for use in training."""
    if cfg.TRAIN.USE_FLIPPED:
      print('Appending horizontally-flipped training examples...')
      imdb.append_flipped_images()
      print('done')
    if cfg.TRAIN.USE_90ROTATION:
      print('Appending 90-rotated training examples...')
      imdb.append_90rotation_images()
      print('done')
    print('Preparing training data...')

  ### def append_90rotation_images(self):
    num_images = self.num_images
    widths = self._get_widths()
    for i in range(num_images):
      boxes = self.roidb[i]['boxes'].copy()
      oldx1 = boxes[:, 0].copy()
      oldx2 = boxes[:, 1].copy()
      oldx3 = boxes[:, 2].copy()
      oldx4 = boxes[:, 3].copy()
      boxes[:, 0] = widths[i] - oldx2 - 1
      boxes[:, 1] = oldx1
      boxes[:, 2] = widths[i] - oldx4 - 1
      boxes[:, 3] = oldx3
      entry = {'boxes': boxes,
               'gt_overlaps': self.roidb[i]['gt_overlaps'],
               'gt_classes': self.roidb[i]['gt_classes'],
               'flipped': self.roidb[i]['flipped'],
               '90rotation': True}
      self.roidb.append(entry)
    self._image_index = self._image_index * 2

###     if roidb[i]['flipped']:
      im = im[:, ::-1, :]

    if roidb[i]['90rotation']:
      im2 = im
      for k in range(len(im) - 1):
        for j in range(len(im) - 1):
          im2[j][len(im) - 1 - k] = im[k][j]
      im = im2

    target_size = cfg.TRAIN.SCALES[scale_inds[i]]
    im, im_scale = prep_im_for_blob(im, cfg.PIXEL_MEANS, target_size,
                    cfg.TRAIN.MAX_SIZE)
    im_scales.append(im_scale)
    processed_ims.append(im)

### pascal_voc.py:
       return {'boxes': boxes,
                'gt_classes': gt_classes,
                'gt_ishard': ishards,
                'gt_overlaps': overlaps,
                'flipped': False,
                '90rotation': False,
                'seg_areas': seg_areas}

Below is error:

Preparing training data...
done
before filtering, there are 2232 images...
after filtering, there are 2232 images...
2232 roidb entries
[session 1][epoch  1][iter    0/  93] loss: nan, lr: 3.00e-02
                        fg/bg=(0/6144), time cost: 12.006276
                        rpn_cls: 0.7278, rpn_box: nan, rcnn_cls: 1.2322, rcnn_box 0.0000
THCudaCheck FAIL file=/pytorch/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "trainval_net.py", line 323, in <module>
    rois_label = fasterRCNN(im_data, im_info, gt_boxes, num_boxes)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 114, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 124, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/parallel_apply.py", line 65, in parallel_apply
    raise output
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/generic/THCStorage.cu:58
Exception NameError: "global name 'FileNotFoundError' is not defined" in <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7efe6391bb50>> ignored

This is my first time to submit an issue, and i am sorry for my bad english.

Thank you.

**Comment by Saharkakavand** [comment]
dear @wheemyungshin 
did you solve it?
