### ISSUE TITLE
[help] sh make.sh error on cpu on windows - compile error - cffi.error.VerificationError...failed with exit status 2

### ISSUE THREAD

**Issue by yoojin317** [jwyang/faster-rcnn.pytorch#368]
Hi!
I am trying to implement faster rcnn with cpu on windows.
(I don't have gpu! i tried to install cuda but i don't know whether i should install cuda or not even thouth i dont' have gpu!)

so i try to follow https://github.com/gullalc/faster-rcnn.pytorch/blob/master/windows_readme.md
this page!

i am using anaconda 3.4.2, python=3.6, pytorch=0.4.0

when i did
""To compile cuda code,
Use x86_x64 cross tools command prompt.
Open git-bash using "C:\Program Files\Git\git-bash.exe" (usual location)
Follow the same instructions as for linux.""  written in https://github.com/gullalc/faster-rcnn.pytorch/blob/master/windows_readme.md,

I have some error like these.

$ sh make.sh
running build_ext
Traceback (most recent call last):
  File "setup.py", line 136, in <module>
    cmdclass={'build_ext': custom_build_ext},
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\core.py", line 148, in                                                              setup
    dist.run_commands()
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\dist.py", line 955, in                                                              run_commands
    self.run_command(cmd)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\dist.py", line 974, in                                                              run_command
    cmd_obj.run()
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\Cython\Distutils\o                                                             ld_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\command\build_ext.py",                                                              line 339, in run
    self.build_extensions()
  File "setup.py", line 112, in build_extensions
    customize_compiler_for_nvcc(self.compiler)
  File "setup.py", line 84, in customize_compiler_for_nvcc
    default_compiler_so = self.compiler_so
AttributeError: 'MSVCCompiler' object has no attribute 'compiler_so'
Compiling nms kernels by nvcc...
make.sh: line 25: nvcc: command not found
C:\Users\YOOJIN\faster-rcnn.pytorch\lib\model\nms
['C:\\Users\\YOOJIN\\faster-rcnn.pytorch\\lib\\model\\nms\\src/nms_cuda_kernel.cu.o']
generating C:\Users\YOOJIN\AppData\Local\Temp\tmpocljlibo\_nms.c
setting the current directory to 'C:\\Users\\YOOJIN\\AppData\\Local\\Temp\\tmpocljlibo                                                             '
running build_ext
building '_nms' extension
creating Release
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.2702                                                             3\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\YOOJIN\Anacond                                                             a3\envs\ci_pytorch\lib\site-packages\torch\utils\ffi\..\..\lib\include -IC:\Users\YOOJ                                                             IN\Anaconda3\envs\ci_pytorch\lib\site-packages\torch\utils\ffi\..\..\lib\include\TH -I                                                             C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\include -IC:\Users\YOOJIN\Anaconda3\envs\ci_                                                             pytorch\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\To                                                             ols\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio                                                             \2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Microsoft                                                              Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program                                                              Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include"                                                              /Tc_nms.c /Fo.\Release\_nms.obj
_nms.c
C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\include\pyconfig.h(59): fatal error C1083: ▒                                                             ▒▒▒ ▒▒▒▒▒▒ ▒▒ ▒▒ ▒▒▒▒▒ϴ▒. 'io.h': No such file or directory
Traceback (most recent call last):
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\_msvccompiler.py", lin                                                             e 423, in compile
    self.spawn(args)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\_msvccompiler.py", lin                                                             e 542, in spawn
    return super().spawn(cmd)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\ccompiler.py", line 90                                                             9, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\spawn.py", line 38, in                                                              spawn
    _spawn_nt(cmd, search_path, dry_run=dry_run)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\spawn.py", line 81, in                                                              _spawn_nt
    "command %r failed with exit status %d" % (cmd, rc))
distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visua                                                             l Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' fa                                                             iled with exit status 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\cffi\ffiplatform.p                                                             y", line 51, in _build
    dist.run_command('build_ext')
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\dist.py", line 974, in                                                              run_command
    cmd_obj.run()
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\setuptools\command                                                             \build_ext.py", line 78, in run
    _build_ext.run(self)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\Cython\Distutils\o                                                             ld_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\command\build_ext.py",                                                              line 339, in run
    self.build_extensions()
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\Cython\Distutils\o                                                             ld_build_ext.py", line 194, in build_extensions
    self.build_extension(ext)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\setuptools\command                                                             \build_ext.py", line 199, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\command\build_ext.py",                                                              line 533, in build_extension
    depends=ext.depends)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\_msvccompiler.py", lin                                                             e 425, in compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'C:\\Program Files (x86)\\Microsoft Visual Stud                                                             io\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed w                                                             ith exit status 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 37, in <module>
    ffi.build()
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\torch\utils\ffi\__                                                             init__.py", line 184, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\torch\utils\ffi\__                                                             init__.py", line 108, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\cffi\api.py", line                                                              697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\cffi\recompiler.py                                                             ", line 1520, in recompile
    compiler_verbose, debug)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\cffi\ffiplatform.p                                                             y", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\cffi\ffiplatform.p                                                             y", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'C:\\Program Files (x86)\\Microsof                                                             t Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.                                                             exe' failed with exit status 2
Compiling roi pooling kernels by nvcc...
make.sh: line 35: nvcc: command not found
C:\Users\YOOJIN\faster-rcnn.pytorch\lib\model\roi_pooling
generating C:\Users\YOOJIN\AppData\Local\Temp\tmptpcge53i\_roi_pooling.c
setting the current directory to 'C:\\Users\\YOOJIN\\AppData\\Local\\Temp\\tmptpcge53i                                                             '
running build_ext
building '_roi_pooling' extension
creating Release
creating Release\Users
creating Release\Users\YOOJIN
creating Release\Users\YOOJIN\faster-rcnn.pytorch
creating Release\Users\YOOJIN\faster-rcnn.pytorch\lib
creating Release\Users\YOOJIN\faster-rcnn.pytorch\lib\model
creating Release\Users\YOOJIN\faster-rcnn.pytorch\lib\model\roi_pooling
creating Release\Users\YOOJIN\faster-rcnn.pytorch\lib\model\roi_pooling\src
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.2702                                                             3\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\YOOJIN\Anacond                                                             a3\envs\ci_pytorch\lib\site-packages\torch\utils\ffi\..\..\lib\include -IC:\Users\YOOJ                                                             IN\Anaconda3\envs\ci_pytorch\lib\site-packages\torch\utils\ffi\..\..\lib\include\TH -I                                                             C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\include -IC:\Users\YOOJIN\Anaconda3\envs\ci_                                                             pytorch\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\To                                                             ols\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio                                                             \2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Microsoft                                                              Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program                                                              Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include"                                                              /Tc_roi_pooling.c /Fo.\Release\_roi_pooling.obj
_roi_pooling.c
C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\include\pyconfig.h(59): fatal error C1083: ▒                                                             ▒▒▒ ▒▒▒▒▒▒ ▒▒ ▒▒ ▒▒▒▒▒ϴ▒. 'io.h': No such file or directory
Traceback (most recent call last):
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\_msvccompiler.py", lin                                                             e 423, in compile
    self.spawn(args)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\_msvccompiler.py", lin                                                             e 542, in spawn
    return super().spawn(cmd)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\ccompiler.py", line 90                                                             9, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\spawn.py", line 38, in                                                              spawn
    _spawn_nt(cmd, search_path, dry_run=dry_run)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\spawn.py", line 81, in                                                              _spawn_nt
    "command %r failed with exit status %d" % (cmd, rc))
distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visua                                                             l Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' fa                                                             iled with exit status 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\cffi\ffiplatform.p                                                             y", line 51, in _build
    dist.run_command('build_ext')
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\dist.py", line 974, in                                                              run_command
    cmd_obj.run()
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\setuptools\command                                                             \build_ext.py", line 78, in run
    _build_ext.run(self)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\Cython\Distutils\o                                                             ld_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\command\build_ext.py",                                                              line 339, in run
    self.build_extensions()
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\Cython\Distutils\o                                                             ld_build_ext.py", line 194, in build_extensions
    self.build_extension(ext)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\setuptools\command                                                             \build_ext.py", line 199, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\command\build_ext.py",                                                              line 533, in build_extension
    depends=ext.depends)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\_msvccompiler.py", lin                                                             e 425, in compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'C:\\Program Files (x86)\\Microsoft Visual Stud                                                             io\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed w                                                             ith exit status 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 36, in <module>
    ffi.build()
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\torch\utils\ffi\__                                                             init__.py", line 184, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\torch\utils\ffi\__                                                             init__.py", line 108, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\cffi\api.py", line                                                              697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\cffi\recompiler.py                                                             ", line 1520, in recompile
    compiler_verbose, debug)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\cffi\ffiplatform.p                                                             y", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\cffi\ffiplatform.p                                                             y", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'C:\\Program Files (x86)\\Microsof                                                             t Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.                                                             exe' failed with exit status 2
Compiling roi align kernels by nvcc...
make.sh: line 44: nvcc: command not found
C:\Users\YOOJIN\faster-rcnn.pytorch\lib\model\roi_align
generating C:\Users\YOOJIN\AppData\Local\Temp\tmp_vaehka7\_roi_align.c
setting the current directory to 'C:\\Users\\YOOJIN\\AppData\\Local\\Temp\\tmp_vaehka7                                                             '
running build_ext
building '_roi_align' extension
creating Release
creating Release\Users
creating Release\Users\YOOJIN
creating Release\Users\YOOJIN\faster-rcnn.pytorch
creating Release\Users\YOOJIN\faster-rcnn.pytorch\lib
creating Release\Users\YOOJIN\faster-rcnn.pytorch\lib\model
creating Release\Users\YOOJIN\faster-rcnn.pytorch\lib\model\roi_align
creating Release\Users\YOOJIN\faster-rcnn.pytorch\lib\model\roi_align\src
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.2702                                                             3\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\YOOJIN\Anacond                                                             a3\envs\ci_pytorch\lib\site-packages\torch\utils\ffi\..\..\lib\include -IC:\Users\YOOJ                                                             IN\Anaconda3\envs\ci_pytorch\lib\site-packages\torch\utils\ffi\..\..\lib\include\TH -I                                                             C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\include -IC:\Users\YOOJIN\Anaconda3\envs\ci_                                                             pytorch\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\To                                                             ols\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio                                                             \2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Microsoft                                                              Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program                                                              Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include"                                                              /Tc_roi_align.c /Fo.\Release\_roi_align.obj
_roi_align.c
C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\include\pyconfig.h(59): fatal error C1083: ▒                                                             ▒▒▒ ▒▒▒▒▒▒ ▒▒ ▒▒ ▒▒▒▒▒ϴ▒. 'io.h': No such file or directory
Traceback (most recent call last):
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\_msvccompiler.py", lin                                                             e 423, in compile
    self.spawn(args)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\_msvccompiler.py", lin                                                             e 542, in spawn
    return super().spawn(cmd)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\ccompiler.py", line 90                                                             9, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\spawn.py", line 38, in                                                              spawn
    _spawn_nt(cmd, search_path, dry_run=dry_run)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\spawn.py", line 81, in                                                              _spawn_nt
    "command %r failed with exit status %d" % (cmd, rc))
distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visua                                                             l Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' fa                                                             iled with exit status 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\cffi\ffiplatform.p                                                             y", line 51, in _build
    dist.run_command('build_ext')
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\dist.py", line 974, in                                                              run_command
    cmd_obj.run()
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\setuptools\command                                                             \build_ext.py", line 78, in run
    _build_ext.run(self)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\Cython\Distutils\o                                                             ld_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\command\build_ext.py",                                                              line 339, in run
    self.build_extensions()
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\Cython\Distutils\o                                                             ld_build_ext.py", line 194, in build_extensions
    self.build_extension(ext)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\setuptools\command                                                             \build_ext.py", line 199, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\command\build_ext.py",                                                              line 533, in build_extension
    depends=ext.depends)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\_msvccompiler.py", lin                                                             e 425, in compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'C:\\Program Files (x86)\\Microsoft Visual Stud                                                             io\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed w                                                             ith exit status 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 38, in <module>
    ffi.build()
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\torch\utils\ffi\__                                                             init__.py", line 184, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\torch\utils\ffi\__                                                             init__.py", line 108, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\cffi\api.py", line                                                              697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\cffi\recompiler.py                                                             ", line 1520, in recompile
    compiler_verbose, debug)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\cffi\ffiplatform.p                                                             y", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\cffi\ffiplatform.p                                                             y", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'C:\\Program Files (x86)\\Microsof                                                             t Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.                                                             exe' failed with exit status 2
Compiling roi crop kernels by nvcc...
make.sh: line 53: nvcc: command not found
C:\Users\YOOJIN\faster-rcnn.pytorch\lib\model\roi_crop
generating C:\Users\YOOJIN\AppData\Local\Temp\tmp39t87xti\_roi_crop.c
setting the current directory to 'C:\\Users\\YOOJIN\\AppData\\Local\\Temp\\tmp39t87xti                                                             '
running build_ext
building '_roi_crop' extension
creating Release
creating Release\Users
creating Release\Users\YOOJIN
creating Release\Users\YOOJIN\faster-rcnn.pytorch
creating Release\Users\YOOJIN\faster-rcnn.pytorch\lib
creating Release\Users\YOOJIN\faster-rcnn.pytorch\lib\model
creating Release\Users\YOOJIN\faster-rcnn.pytorch\lib\model\roi_crop
creating Release\Users\YOOJIN\faster-rcnn.pytorch\lib\model\roi_crop\src
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.2702                                                             3\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\YOOJIN\Anacond                                                             a3\envs\ci_pytorch\lib\site-packages\torch\utils\ffi\..\..\lib\include -IC:\Users\YOOJ                                                             IN\Anaconda3\envs\ci_pytorch\lib\site-packages\torch\utils\ffi\..\..\lib\include\TH -I                                                             C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\include -IC:\Users\YOOJIN\Anaconda3\envs\ci_                                                             pytorch\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\To                                                             ols\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio                                                             \2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Microsoft                                                              Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program                                                              Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include"                                                              /Tc_roi_crop.c /Fo.\Release\_roi_crop.obj
_roi_crop.c
C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\include\pyconfig.h(59): fatal error C1083: ▒                                                             ▒▒▒ ▒▒▒▒▒▒ ▒▒ ▒▒ ▒▒▒▒▒ϴ▒. 'io.h': No such file or directory
Traceback (most recent call last):
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\_msvccompiler.py", lin                                                             e 423, in compile
    self.spawn(args)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\_msvccompiler.py", lin                                                             e 542, in spawn
    return super().spawn(cmd)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\ccompiler.py", line 90                                                             9, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\spawn.py", line 38, in                                                              spawn
    _spawn_nt(cmd, search_path, dry_run=dry_run)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\spawn.py", line 81, in                                                              _spawn_nt
    "command %r failed with exit status %d" % (cmd, rc))
distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visua                                                             l Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' fa                                                             iled with exit status 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\cffi\ffiplatform.p                                                             y", line 51, in _build
    dist.run_command('build_ext')
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\dist.py", line 974, in                                                              run_command
    cmd_obj.run()
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\setuptools\command                                                             \build_ext.py", line 78, in run
    _build_ext.run(self)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\Cython\Distutils\o                                                             ld_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\command\build_ext.py",                                                              line 339, in run
    self.build_extensions()
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\Cython\Distutils\o                                                             ld_build_ext.py", line 194, in build_extensions
    self.build_extension(ext)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\setuptools\command                                                             \build_ext.py", line 199, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\command\build_ext.py",                                                              line 533, in build_extension
    depends=ext.depends)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\distutils\_msvccompiler.py", lin                                                             e 425, in compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'C:\\Program Files (x86)\\Microsoft Visual Stud                                                             io\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed w                                                             ith exit status 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 36, in <module>
    ffi.build()
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\torch\utils\ffi\__                                                             init__.py", line 184, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\torch\utils\ffi\__                                                             init__.py", line 108, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\cffi\api.py", line                                                              697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\cffi\recompiler.py                                                             ", line 1520, in recompile
    compiler_verbose, debug)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\cffi\ffiplatform.p                                                             y", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "C:\Users\YOOJIN\Anaconda3\envs\ci_pytorch\lib\site-packages\cffi\ffiplatform.p                                                             y", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'C:\\Program Files (x86)\\Microsof                                                             t Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.                                                             exe' failed with exit status 2

hum...............
i don't know what to do...
i've no seen this error related to faster rcnn..
""cffi.error.VerificationError: CompileError: command 'C:\\Program Files (x86)\\Microsof                                                             t Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.                                                             exe' failed with exit status 2"" 

please tell me what is wrong..

**Comment by huziling** [comment]
can you train the network in windows rightnow

**Comment by nanshuiyu** [comment]
me too.......

**Comment by nanshuiyu** [comment]
how  help me !!!!!

**Comment by ZiyuBao** [comment]
Same question and same error: How to compile in MacOS with CPU only? #678
