### ISSUE TITLE
nms error

### ISSUE THREAD

**Issue by FzuLJ** [jwyang/faster-rcnn.pytorch#373]
Traceback (most recent call last):
  File "test_net.py", line 332, in <module>
    keep = nms(cls_dets, cfg.TEST.NMS)
  File "/home/linjie/src/pcl.pytorch/lib/model/nms/nms_wrapper.py", line 21, in nms
    return nms_gpu(dets, thresh) if force_cpu == False else nms_cpu(dets, thresh)
  File "/home/linjie/src/pcl.pytorch/lib/model/nms/nms_gpu.py", line 8, in nms_gpu
    keep = dets.new(dets.size(0), 1).zero_().int()
AttributeError: 'numpy.ndarray' object has no attribute 'new'

When I run test_net.py, an error occured. Does anyone know how to solve it?

**Comment by linquanxu** [comment]
@FzuLJ @jwyang hi,I also have the same problem, have you solve it?
