### ISSUE TITLE
ImportError: Building module pycocotools._mask failed: ["CompileError: command 'gcc' failed with exit status 1\n"]

### ISSUE THREAD

**Issue by u101022205** [jwyang/faster-rcnn.pytorch#374]
I dig into the solutions you gave for the error from make.sh. But my problem is that my make.sh works fine. The error occurs when i run the main code

> python trainval_net.py --dataset pascal_voc --net vgg16 --bs 20 --nw 4 --cuda

> In file included from /usr/include/numpy/ndarraytypes.h:1777:0,
                 from /usr/include/numpy/ndarrayobject.h:18,
                 from /usr/include/numpy/arrayobject.h:4,
                 from /home/sxs/.pyxbld/temp.linux-x86_64-2.7/pyrex/pycocotools/_mask.c:610:
/usr/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
/home/sxs/.pyxbld/temp.linux-x86_64-2.7/pyrex/pycocotools/_mask.c:613:21: fatal error: maskApi.h: No such file or directory
compilation terminated.
Traceback (most recent call last):
  File "trainval_net.py", line 27, in <module>
    from roi_data_layer.roidb import combined_roidb
  File "/home/sxs/yuhsuan/faster-rcnn.pytorch/lib/roi_data_layer/roidb.py", line 9, in <module>
    from datasets.factory import get_imdb
  File "/home/sxs/yuhsuan/faster-rcnn.pytorch/lib/datasets/factory.py", line 16, in <module>
    from datasets.coco import coco
  File "/home/sxs/yuhsuan/faster-rcnn.pytorch/lib/datasets/coco.py", line 23, in <module>
    from pycocotools.coco import COCO
  File "/home/sxs/yuhsuan/faster-rcnn.pytorch/lib/pycocotools/coco.py", line 60, in <module>
    from . import mask
  File "/home/sxs/yuhsuan/faster-rcnn.pytorch/lib/pycocotools/mask.py", line 8, in <module>
    import _mask
  File "/home/sxs/anaconda3/envs/test1/lib/python2.7/site-packages/pyximport/pyximport.py", line 462, in load_module
    language_level=self.language_level)
  File "/home/sxs/anaconda3/envs/test1/lib/python2.7/site-packages/pyximport/pyximport.py", line 233, in load_module
    exec("raise exc, None, tb", {'exc': exc, 'tb': tb})
  File "/home/sxs/anaconda3/envs/test1/lib/python2.7/site-packages/pyximport/pyximport.py", line 215, in load_module
    inplace=build_inplace, language_level=language_level)
  File "/home/sxs/anaconda3/envs/test1/lib/python2.7/site-packages/pyximport/pyximport.py", line 191, in build_module
    reload_support=pyxargs.reload_support)
  File "/home/sxs/anaconda3/envs/test1/lib/python2.7/site-packages/pyximport/pyxbuild.py", line 102, in pyx_to_dll
    dist.run_commands()
  File "/home/sxs/anaconda3/envs/test1/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/sxs/anaconda3/envs/test1/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/sxs/anaconda3/envs/test1/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/sxs/anaconda3/envs/test1/lib/python2.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/sxs/anaconda3/envs/test1/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 194, in build_extensions
    self.build_extension(ext)
  File "/home/sxs/anaconda3/envs/test1/lib/python2.7/distutils/command/build_ext.py", line 499, in build_extension
    depends=ext.depends)
  File "/home/sxs/anaconda3/envs/test1/lib/python2.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/home/sxs/anaconda3/envs/test1/lib/python2.7/distutils/unixccompiler.py", line 124, in _compile
    raise CompileError, msg
ImportError: Building module pycocotools._mask failed: ["CompileError: command 'gcc' failed with exit status 1\n"]

Does there anyone know how to solve it?

**Comment by DingyuanZheng-XJTLU** [comment]
What's your gcc version? You could try gcc 4.8.5.

**Comment by u101022205** [comment]
> I found an error in your message:
> 
> > /home/sxs/.pyxbld/temp.linux-x86_64-2.7/pyrex/pycocotools/_mask.c:613:21: fatal error: maskApi.h: No such file or directory
> 
> Maybe you have deleted it?

actually, i put it in the right location. I have no idea why it will search this path. 

`/home/sxs/.pyxbld/temp.linux-x86_64-2.7/pyrex/`

The file is in /home/sxs/faster-rcnn/lib

**Comment by cutrain** [comment]
Try `export  C_INCLUDE_PATH=/home/sxs/faster-rcnn/lib:$C_INCLUDE_PATH` to add the include path may help you.

**Comment by CAROLZXYZXY** [comment]
Hello! I meet he same problem, have you solved?? Thanks!

**Comment by masterwei1024** [comment]
hi, I meet the same problem, have you solved? thanks!

**Comment by masterwei1024** [comment]
raise CompileError(msg)
ImportError: Building module subiterations failed: ["CompileError: command 'E:\\\\software install\\\\VS\\\\install location\\\\VC\\\\BIN\\\\amd64\\\\cl.exe' failed with exit status 2\n"]

**Comment by masterwei1024** [comment]
help me!

**Comment by masterwei1024** [comment]
please!
