### ISSUE TITLE
when i begin my training，I have a problem like this

### ISSUE THREAD

**Issue by wangkuan1115** [jwyang/faster-rcnn.pytorch#378]
when i begin my training，I have a problem like this：
##
Traceback (most recent call last):
  File "/media/jsu/205E470B5E46D8E4/fasterrcnn-pytorch/faster-rcnn.pytorch/trainval_net.py", line 328, in <module>
    loss.backward()
  File "/home/jsu/anaconda3/envs/torch0.4.0/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/jsu/anaconda3/envs/torch0.4.0/lib/python3.6/site-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/media/jsu/205E470B5E46D8E4/fasterrcnn-pytorch/faster-rcnn.pytorch/lib/model/roi_align/functions/roi_align.py", line 38, in backward
    assert(self.feature_size is not None and grad_output.is_cuda)
AssertionError
##
Can you give me some suggestions？

**Comment by haitaobiyao** [comment]
Did you solve the problem,I have the same problem when i want train

**Comment by niuniu111** [comment]
> when i begin my training，I have a problem like this：
> 
> Traceback (most recent call last):
> File "/media/jsu/205E470B5E46D8E4/fasterrcnn-pytorch/faster-rcnn.pytorch/trainval_net.py", line 328, in
> loss.backward()
> File "/home/jsu/anaconda3/envs/torch0.4.0/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
> torch.autograd.backward(self, gradient, retain_graph, create_graph)
> File "/home/jsu/anaconda3/envs/torch0.4.0/lib/python3.6/site-packages/torch/autograd/**init**.py", line 89, in backward
> allow_unreachable=True) # allow_unreachable flag
> File "/media/jsu/205E470B5E46D8E4/fasterrcnn-pytorch/faster-rcnn.pytorch/lib/model/roi_align/functions/roi_align.py", line 38, in backward
> assert(self.feature_size is not None and grad_output.is_cuda)
> AssertionError
> 
> Can you gi

> when i begin my training，I have a problem like this：
> 
> Traceback (most recent call last):
> File "/media/jsu/205E470B5E46D8E4/fasterrcnn-pytorch/faster-rcnn.pytorch/trainval_net.py", line 328, in
> loss.backward()
> File "/home/jsu/anaconda3/envs/torch0.4.0/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
> torch.autograd.backward(self, gradient, retain_graph, create_graph)
> File "/home/jsu/anaconda3/envs/torch0.4.0/lib/python3.6/site-packages/torch/autograd/**init**.py", line 89, in backward
> allow_unreachable=True) # allow_unreachable flag
> File "/media/jsu/205E470B5E46D8E4/fasterrcnn-pytorch/faster-rcnn.pytorch/lib/model/roi_align/functions/roi_align.py", line 38, in backward
> assert(self.feature_size is not None and grad_output.is_cuda)
> AssertionError
> 
> Can you give me some suggestions？

I also meet the question,do you have solved?

**Comment by haitaobiyao** [comment]
maybe your grad_output not cuda,you should run the code in GPU

**Comment by niuniu111** [comment]
you can specify your GPU

**Comment by haitaobiyao** [comment]
>           you can specify your GPU
why can't specify GPU,if your have GPU,just run this command.
CUDA_VISIBLE_DEVICES=$GPU_ID python trainval_net.py \
                   --dataset pascal_voc --net vgg16 \
                   --bs $BATCH_SIZE --nw $WORKER_NUMBER \
                   --lr $LEARNING_RATE --lr_decay_step $DECAY_STEP \
                   --cuda

**Comment by haofeng0928** [comment]
your commend --cuda
