### ISSUE TITLE
I meet such as  issue,I donnot know,I hope I can  get a help

### ISSUE THREAD

**Issue by niuniu111** [jwyang/faster-rcnn.pytorch#379]
Traceback (most recent call last):
  File "/home/cv2018/faster-rcnn.pytorch-master/trainval_net.py", line 198, in <module>
    imdb, roidb, ratio_list, ratio_index = combined_roidb(args.imdb_name)
  File "/home/cv2018/faster-rcnn.pytorch-master/lib/roi_data_layer/roidb.py", line 116, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "/home/cv2018/faster-rcnn.pytorch-master/lib/roi_data_layer/roidb.py", line 116, in <listcomp>
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "/home/cv2018/faster-rcnn.pytorch-master/lib/roi_data_layer/roidb.py", line 113, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/home/cv2018/faster-rcnn.pytorch-master/lib/roi_data_layer/roidb.py", line 97, in get_training_roidb
    imdb.append_flipped_images()
  File "/home/cv2018/faster-rcnn.pytorch-master/lib/datasets/imdb.py", line 118, in append_flipped_images
    boxes = self.roidb[i]['boxes'].copy()
  File "/home/cv2018/faster-rcnn.pytorch-master/lib/datasets/imdb.py", line 76, in roidb
    self._roidb = self.roidb_handler()
  File "/home/cv2018/faster-rcnn.pytorch-master/lib/datasets/pascal_voc.py", line 128, in gt_roidb
    roidb = pickle.load(fid)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 5: ordinal not in range(128)
the version of python is 3.6 and pytorch  is 0.4

**Comment by jwyang** [comment]
I think the reason is that you changed the python version or pickle version? I guess maybe you used different version to save and load the pickle.
