### ISSUE TITLE
I have some problems who can help me thank very much

### ISSUE THREAD

**Issue by haitaobiyao** [jwyang/faster-rcnn.pytorch#392]
Traceback (most recent call last):
  File "/home/xionghaitao/workplace/study_example/faster-rcnn.pytorch-master/trainval_net.py", line 328, in <module>
    loss.backward()
  File "/home/xionghaitao/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/xionghaitao/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/xionghaitao/workplace/study_example/faster-rcnn.pytorch-master/lib/model/roi_align/functions/roi_align.py", line 42, in backward
    assert(self.feature_size is not None and grad_output.is_cuda)
AssertionError

**Comment by zhendong94** [comment]
Hello， How do you solve this problem, I met a problem similar to yours.

**Comment by IMBINGO95** [comment]
I met the same problem.Could you tell me how you solved it?

**Comment by LcenArthas** [comment]
I met the same problem.Could you tell me how you solved it?

**Comment by haitaobiyao** [comment]
use --cuda




------------------ 原始邮件 ------------------
发件人: "Arthas"<notifications@github.com>; 
发送时间: 2019年5月14日(星期二) 下午3:20
收件人: "jwyang/faster-rcnn.pytorch"<faster-rcnn.pytorch@noreply.github.com>; 
抄送: "残雪—也只不过是一时"<993599291@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [jwyang/faster-rcnn.pytorch] I have some problems who can help methank very much (#392)




I met the same problem.Could you tell me how you solved it?
