### ISSUE TITLE
When training TypeError issue? Please help

### ISSUE THREAD

**Issue by EldorIbragimov** [jwyang/faster-rcnn.pytorch#40]
Traceback (most recent call last):
  File "/home/e/faster-rcnn.pytorch/trainval_net.py", line 322, in <module>
    rois_label = fasterRCNN(im_data, im_info, gt_boxes, num_boxes)
  File "/home/e/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/e/faster-rcnn.pytorch/lib/model/faster_rcnn/faster_rcnn.py", line 50, in forward
    rois, rpn_loss_cls, rpn_loss_bbox = self.RCNN_rpn(base_feat, im_info, gt_boxes, num_boxes)
  File "/home/e/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/e/faster-rcnn.pytorch/lib/model/rpn/rpn.py", line 77, in forward
    im_info, cfg_key))
  File "/home/e/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/e/faster-rcnn.pytorch/lib/model/rpn/proposal_layer.py", line 147, in forward
    keep_idx_i = nms(torch.cat((proposals_single, scores_single), 1), nms_thresh)
  File "/home/e/faster-rcnn.pytorch/lib/model/nms/nms_wrapper.py", line 18, in nms
    return nms_gpu(dets, thresh)
  File "/home/e/faster-rcnn.pytorch/lib/model/nms/nms_gpu.py", line 9, in nms_gpu
    nms.nms_cuda(keep, dets, num_out, thresh)
  File "/home/e/.local/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 180, in safe_call
    result = torch._C._safe_call(*args, **kwargs)
TypeError: initializer for ctype 'struct THCudaIntTensor *' must be a pointer to same type, not cdata 'struct THIntTensor *'

**Comment by jwyang** [comment]
@EldorIbragimov you need use GPU to train the model. Try add "--cuda" to the training command.
