### ISSUE TITLE
RuntimeError: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by rmxhhh** [jwyang/faster-rcnn.pytorch#407]
@jwyang  Hi,I have an error when i want to train the faster-rcnn. 
`Loaded dataset `voc_2007_trainval` for training
Set proposal method: gt
Appending horizontally-flipped training examples...
voc_2007_trainval gt roidb loaded from /home/wr506/faster-rcnn.pytorch/data/cache/voc_2007_trainval_gt_roidb.pkl
done
Preparing training data...
done
before filtering, there are 10022 images...
after filtering, there are 10022 images...
10022 roidb entries
Loading pretrained weights from data/pretrained_model/vgg16_caffe.pth
Traceback (most recent call last):
  File "trainval_net.py", line 320, in <module>
    rois_label = fasterRCNN(im_data, im_info, gt_boxes, num_boxes)
  File "/home/wr506/anaconda3/envs/rmx/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wr506/faster-rcnn.pytorch/lib/model/faster_rcnn/faster_rcnn.py", line 47, in forward
    base_feat = self.RCNN_base(im_data)
  File "/home/wr506/anaconda3/envs/rmx/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wr506/anaconda3/envs/rmx/lib/python2.7/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/wr506/anaconda3/envs/rmx/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wr506/anaconda3/envs/rmx/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDNN_STATUS_EXECUTION_FAILED
Exception NameError: "global name 'FileNotFoundError' is not defined" in <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f3637c8b550>> ignored
`
my inviroment is:
2080Ti
ubuntu16
pytorch0.4.0
cuda9.0
and my training command is:
`python trainval_net.py \
                   --dataset pascal_voc --net vgg16 \
                   --bs 1 --nw 1 \
                   --lr 1e-3 --lr_decay_step 5 \
                   --cuda`

Can you tell me what should i do?Thank you very much

**Comment by andrewjong** [comment]
Is this related? https://github.com/pytorch/pytorch/issues/6932#issuecomment-384692621
Says to try using Python 3, or implement your own quick fix a couple comments down.

**Comment by hrbeuyz24** [comment]
the same question as you

**Comment by MaddyThakker** [comment]
I am also facing the same error, did anyone find the solution to this?

**Comment by hanhao2019102935** [comment]
我有同样的问题。请问你是否解决掉这个问题了，如果是能否给我一些建议。 @andrewjong @MaddyThakker

**Comment by hanhao2019102935** [comment]
I have the same problem.May I ask if you have solved this problem? If so, could you give me some advice? @andrewjong @MaddyThakker @rmxhhh
