### ISSUE TITLE
Training issue

### ISSUE THREAD

**Issue by JanVin** [jwyang/faster-rcnn.pytorch#414]
Preparing training data...
done
before filtering, there are 10022 images...
after filtering, there are 10022 images...
10022 roidb entries
Loading pretrained weights from data/pretrained_model/vgg16_caffe.pth
Traceback (most recent call last):
  File "trainval_net.py", line 320, in <module>
    rois_label = fasterRCNN(im_data, im_info, gt_boxes, num_boxes)
  File "/home/janvin/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/janvin/faster-rcnn.pytorch/lib/model/faster_rcnn/faster_rcnn.py", line 54, in forward
    rois, rpn_loss_cls, rpn_loss_bbox = self.RCNN_rpn(base_feat, im_info, gt_boxes, num_boxes)
  File "/home/janvin/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/janvin/faster-rcnn.pytorch/lib/model/rpn/rpn.py", line 78, in forward
    im_info, cfg_key))
  File "/home/janvin/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/janvin/faster-rcnn.pytorch/lib/model/rpn/proposal_layer.py", line 147, in forward
    keep_idx_i = nms(proposals_single, scores_single.squeeze(1), nms_thresh)
RuntimeError: Not compiled with GPU support (nms at /home/janvin/faster-rcnn.pytorch/lib/model/csrc/nms.h:22)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x45 (0x7fc141178cc5 in /home/janvin/anaconda3/envs/python36/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: nms(at::Tensor const&, at::Tensor const&, float) + 0xdc (0x7fc13ceae48c in /home/janvin/faster-rcnn.pytorch/lib/model/_C.cpython-36m-x86_64-linux-gnu.so)
frame #2: <unknown function> + 0x148e8 (0x7fc13ceba8e8 in /home/janvin/faster-rcnn.pytorch/lib/model/_C.cpython-36m-x86_64-linux-gnu.so)
frame #3: <unknown function> + 0x11f35 (0x7fc13ceb7f35 in /home/janvin/faster-rcnn.pytorch/lib/model/_C.cpython-36m-x86_64-linux-gnu.so)
<omitting python frames>
frame #56: __libc_start_main + 0xe7 (0x7fc192bcab97 in /lib/x86_64-linux-gnu/libc.so.6)

what's the problem is ?

**Comment by adityaarun1** [comment]
`RuntimeError: Not compiled with GPU support (nms at /home/janvin/faster-rcnn.pytorch/lib/model/csrc/nms.h:22)`

NMS seems to be compiled without GPU. Try removing the `build` directory and recompiling. Ensure you have CUDA/CuDNN in your path, and check for errors when running `python setup.py build develop`

**Comment by JanVin** [comment]
Yes, it's seem like is nvidia's problem. Thank you!

**Comment by 9p15p** [comment]
1.install cuda和cudnn correctly (be careful about their version)
2.配置环境变量
3.delete旧的build文件夹
4.python setup.py build develop

**Comment by KimYangOfCat** [comment]
> `RuntimeError: Not compiled with GPU support (nms at /home/janvin/faster-rcnn.pytorch/lib/model/csrc/nms.h:22)`
> 
> NMS seems to be compiled without GPU. Try removing the `build` directory and recompiling. Ensure you have CUDA/CuDNN in your path, and check for errors when running `python setup.py build develop`

Hello, Can you talk about how to ensure my CUDA/CUDNN in my path? thanks~

**Comment by FlyDre** [comment]
> Hello, Can you talk about how to ensure my CUDA/CUDNN in my path? thanks~

Hello, Have you done this step? Appreciate.

**Comment by KimYangOfCat** [comment]
> > Hello, Can you talk about how to ensure my CUDA/CUDNN in my path? thanks~
> 
> Hello, Have you done this step? Appreciate.

Sorry, it's a long time ago, I forget My steps. And I remember I didn't fix this problem

**Comment by FlyDre** [comment]
I‘ve done it.Thanks for reply anyway



发自我的iPhone


------------------ Original ------------------

**Comment by Guosheng-Ye** [comment]
> 1.install cuda和cudnn correctly (be careful about their version) 2.配置环境变量 3.delete旧的build文件夹 4.python setup.py build develop

I‘ve solved it. Thank you very much
