### ISSUE TITLE
AttributeError: module 'model.nms._ext.nms' has no attribute 'nms_cuda'

### ISSUE THREAD

**Issue by berthyf96** [jwyang/faster-rcnn.pytorch#415]
I'm running from the master branch with PyTorch 0.4.0 and CUDA 9.0. I already ran sh make.sh and everything compiled without errors. When I run trainval_net.py, however, I'm getting this error:

```
Loading pretrained weights from data/pretrained_model/resnet101_caffe.pth
Traceback (most recent call last):
  File "trainval_net.py", line 320, in <module>
    rois_label = fasterRCNN(im_data, im_info, gt_boxes, num_boxes)
  File "/n/fs/unpcap/py36/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/n/fs/unpcap/bfeng/faster-rcnn.pytorch/lib/model/faster_rcnn/faster_rcnn.py", line 50, in forward
    rois, rpn_loss_cls, rpn_loss_bbox = self.RCNN_rpn(base_feat, im_info, gt_boxes, num_boxes)
  File "/n/fs/unpcap/py36/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/n/fs/unpcap/bfeng/faster-rcnn.pytorch/lib/model/rpn/rpn.py", line 78, in forward
    im_info, cfg_key))
  File "/n/fs/unpcap/py36/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/n/fs/unpcap/bfeng/faster-rcnn.pytorch/lib/model/rpn/proposal_layer.py", line 148, in forward
    keep_idx_i = nms(torch.cat((proposals_single, scores_single), 1), nms_thresh, force_cpu=not cfg.USE_GPU_NMS)
  File "/n/fs/unpcap/bfeng/faster-rcnn.pytorch/lib/model/nms/nms_wrapper.py", line 21, in nms
    return nms_gpu(dets, thresh) if force_cpu == False else nms_cpu(dets, thresh)
  File "/n/fs/unpcap/bfeng/faster-rcnn.pytorch/lib/model/nms/nms_gpu.py", line 10, in nms_gpu
    nms.nms_cuda(keep, dets, num_out, thresh)
AttributeError: module 'model.nms._ext.nms' has no attribute 'nms_cuda'
srun: error: node717: task 0: Exited with exit code 1
```

Any idea why this is happening?

**Comment by GloriaZLQ** [comment]
have you solve this problem???

**Comment by lininglouis** [comment]
same here

**Comment by Stephen-ThreeD** [comment]
same error, have you solved the problem?

**Comment by dreamedrainbow** [comment]
> same error, have you solved the problem?

My problem solved. Just do as @lininglouis say

**Comment by mohanrobotics** [comment]
@berthyf96 Did you solve this error ? I am still getting the same error even after running sh make.sh

**Comment by dreamedrainbow** [comment]
> @berthyf96 Did you solve this error ? I am still getting the same error even after running sh make.sh

Check your CUDA version and the batch version

**Comment by mohanrobotics** [comment]
> > @berthyf96 Did you solve this error ? I am still getting the same error even after running sh make.sh
> 
> Check your CUDA version and the batch version
This problem occurs because I was using docker and was running the `python setup.py build develop`  during the docker build with incompatible cuda version in the docker and the local machine. As @berthyf96 told if the cuda version in the machine and the version in the docker mismatch,  
Line 31: if torch.cuda.is_available() and CUDA_HOME is not None 
of setup.py return false and so the setup.py will run without gpu support.  So, if the docker is built in a machine with no gpu/ with incompatible cuda version and porting the docker images to cluster or a machine with gpu wont work. In such case I removed the the
 if torch.cuda.is_available() and CUDA_HOME  
and was able to run with gpu support.

**Comment by chansongoal** [comment]
Hi, @mohanrobotics Could you please provide me a docker image? Appreciate it if you help me!
