### ISSUE TITLE
multi gpu train errors!

### ISSUE THREAD

**Issue by qianfangjj** [jwyang/faster-rcnn.pytorch#421]
When I run the command : CUDA_VISIBLE_DEVICES=2,3 python trainval_net.py \
                                                        --dataset pascal_voc --net res101 \
                                                        --bs 4 --nw 2 \
                                                        --lr 0.001 --lr_decay_step 5 \
                                                       --cuda --mGPUs
problems produced as follows:
Traceback (most recent call last):
  File "trainval_net.py", line 353, in <module>
    rois_label = fasterRCNN(im_data, im_info, gt_boxes, num_boxes)
  File "/home/sw/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sw/.local/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 115, in forward
    return self.gather(outputs, self.output_device)
  File "/home/sw/.local/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 127, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/home/sw/.local/lib/python2.7/site-packages/torch/nn/parallel/scatter_gather.py", line 68, in gather
    return gather_map(outputs)
  File "/home/sw/.local/lib/python2.7/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/home/sw/.local/lib/python2.7/site-packages/torch/nn/parallel/scatter_gather.py", line 55, in gather_map
    return Gather.apply(target_device, dim, *outputs)
  File "/home/sw/.local/lib/python2.7/site-packages/torch/nn/parallel/_functions.py", line 54, in forward
    ctx.input_sizes = tuple(map(lambda i: i.size(ctx.dim), inputs))
  File "/home/sw/.local/lib/python2.7/site-packages/torch/nn/parallel/_functions.py", line 54, in <lambda>
    ctx.input_sizes = tuple(map(lambda i: i.size(ctx.dim), inputs))
RuntimeError: dimension specified as 0 but tensor has no dimensions
Exception NameError: "global name 'FileNotFoundError' is not defined" in <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f2906fdf9d0>> ignored

Is anyone  know how to solve it? Thank you very much!

**Comment by air-y** [comment]
i have some problem

**Comment by wyxhahaha** [comment]
i have same problem

**Comment by yzhq97** [comment]
I have the same problem

**Comment by ZHUXUHAN** [comment]
I have the same problem

**Comment by ZHUXUHAN** [comment]
i have same problem

**Comment by fate3439** [comment]
Same here.

**Comment by shadowclouds** [comment]
i have same problem

**Comment by mametch** [comment]
in  faster-rcnn.pytorch/lib/model/faster_rcnn/faster_rcnn.py
Add the following to line 113
"""
rpn_loss_cls = torch.Tensor([0]).cuda() + rpn_loss_cls
rpn_loss_bbox = torch.Tensor([0]).cuda() + rpn_loss_bbox
RCNN_loss_cls = torch.Tensor([0]).cuda() + RCNN_loss_cls
RCNN_loss_bbox = torch.Tensor([0]).cuda() + RCNN_loss_bbox
"""
An error will occur if the return value of "_fasterRCNN" is not a tensor.

**Comment by ZiyuBao** [comment]
Same problem.

https://github.com/pytorch/pytorch/issues/6932 provides a solution: downgrade torch 0.4.0 to 0.3.0. But this will produce another error:

`lib/roi_data_layer/roibatchLoader.py", line 54, in __init__
    self.ratio_list_batch[left_idx:(right_idx+1)] = torch.tensor(target_ratio.astype(np.float64)) # trainset ratio list ,each batch is same number
TypeError: 'module' object is not callable`

This error can be solved but upgrading to 0.4.0.

Any solution to solve either one of the two errors?
