### ISSUE TITLE
assert(self.feature_size is not None and grad_output.is_cuda) AssertionError

### ISSUE THREAD

**Issue by qiqihaer** [jwyang/faster-rcnn.pytorch#424]

**Comment by qiqihaer** [comment]
Traceback (most recent call last):
  File "/data/WQ/download/faster-rcnn.pytorch-python3/trainval_net.py", line 328, in <module>
    loss.backward()
  File "/home/seivl/.local/lib/python3.5/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/seivl/.local/lib/python3.5/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/data/WQ/download/faster-rcnn.pytorch-python3/lib/model/roi_align/functions/roi_align.py", line 38, in backward
    assert(self.feature_size is not None and grad_output.is_cuda)
AssertionError

How can I fix this problem?

**Comment by qiqihaer** [comment]
It‘s my fault that I do not follow the instructions.

**Comment by IMBINGO95** [comment]
I encountered the same problem! Can you help me ?

**Comment by qiqihaer** [comment]
Please check the setting of tensors related to cuda(). Make sure that you use GPU to train the network.

**Comment by FelicityLeung** [comment]
I use the cuda to train but another question  occur "
cudaCheckError() failed : no kernel image is available for execution on the device
"
but I have installed cuda and it's right in other pytorch projects.

**Comment by tutuhuhu** [comment]
@FelicityLeung 
have you solve the problem?I meet the same problem.

**Comment by FelicityLeung** [comment]
@tutuhuhu
Yes, you have to set  the right -arch in make.sh file according to your computer.
https://github.com/jwyang/faster-rcnn.pytorch#compilation
