### ISSUE TITLE
Can't get test predictions without having annotation files

### ISSUE THREAD

**Issue by brandenkmurray** [jwyang/faster-rcnn.pytorch#438]
I've trained using a custom dataset and I am trying to use `test_net.py` to make predictions on new images for which I don't have Annotations for. However, I get a `FileNotFound` error because annotations do not exist. Is there a proper way to get predictions for an un-annotated test set? I suppose one workaround might be to create a bunch of dummy annotation files for each image, but that doesn't seem like something that should be necessary when evaluation isn't needed.

imdb ROOTD_DIR = /home/bmurray/faster-rcnn.pytorch/lib/datasets/../..
Called with args:
Namespace(cfg_file='cfgs/res101.yml', checkepoch=1, checkpoint=10021, checksession=99, class_agnostic=False, cuda=True, dataset='custom_dataset', fold='0', large_scale=False, load_dir='models', mGPUs=False, net='res101', parallel_type=0, set_cfgs=None, vis=True)
using custom_dataset
Using config:
{'ANCHOR_RATIOS': [0.5, 1, 2, 4, 8],
 'ANCHOR_SCALES': [4, 8, 16, 32],
 'CROP_RESIZE_WITH_MAX_POOL': False,
 'CUDA': False,
 'DATA_DIR': '/home/bmurray/faster-rcnn.pytorch/data',
 'DEDUP_BOXES': 0.0625,
 'EPS': 1e-14,
 'EXP_DIR': 'res101',
 'FEAT_STRIDE': [16],
 'GPU_ID': 0,
 'MATLAB': 'matlab',
 'MAX_NUM_GT_BOXES': 20,
 'MOBILENET': {'DEPTH_MULTIPLIER': 1.0,
               'FIXED_LAYERS': 5,
               'REGU_DEPTH': False,
               'WEIGHT_DECAY': 4e-05},
 'PIXEL_MEANS': array([[[102.9801, 115.9465, 122.7717]]]),
 'POOLING_MODE': 'align',
 'POOLING_SIZE': 7,
 'RESNET': {'FIXED_BLOCKS': 1, 'MAX_POOL': False},
 'RNG_SEED': 3,
 'ROOT_DIR': '/home/bmurray/faster-rcnn.pytorch',
 'TEST': {'BBOX_REG': True,
          'HAS_RPN': True,
          'MAX_SIZE': 1600,
          'MODE': 'top',
          'NMS': 0.3,
          'PROPOSAL_METHOD': 'gt',
          'RPN_MIN_SIZE': 8,
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 300,
          'RPN_PRE_NMS_TOP_N': 6000,
          'RPN_TOP_N': 5000,
          'SCALES': [1200],
          'SVM': False},
 'TRAIN': {'ASPECT_GROUPING': False,
           'BATCH_SIZE': 128,
           'BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'BBOX_NORMALIZE_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZE_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_NORMALIZE_TARGETS': True,
           'BBOX_NORMALIZE_TARGETS_PRECOMPUTED': True,
           'BBOX_REG': True,
           'BBOX_THRESH': 0.5,
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.0,
           'BIAS_DECAY': False,
           'BN_TRAIN': False,
           'DISPLAY': 20,
           'DOUBLE_BIAS': False,
           'FG_FRACTION': 0.25,
           'FG_THRESH': 0.5,
           'GAMMA': 0.1,
           'HAS_RPN': True,
           'IMS_PER_BATCH': 1,
           'LEARNING_RATE': 0.001,
           'MAX_SIZE': 1600,
           'MOMENTUM': 0.9,
           'PROPOSAL_METHOD': 'gt',
           'RPN_BATCHSIZE': 256,
           'RPN_BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_MIN_SIZE': 8,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 2000,
           'RPN_PRE_NMS_TOP_N': 12000,
           'SCALES': [1200],
           'SNAPSHOT_ITERS': 5000,
           'SNAPSHOT_KEPT': 3,
           'SNAPSHOT_PREFIX': 'res101_faster_rcnn',
           'STEPSIZE': [30000],
           'SUMMARY_INTERVAL': 180,
           'TRIM_HEIGHT': 1200,
           'TRIM_WIDTH': 1200,
           'TRUNCATED': False,
           'USE_ALL_GT': True,
           'USE_FLIPPED': False,
           'USE_GT': False,
           'WEIGHT_DECAY': 0.0001},
 'USE_GPU_NMS': True}
/home/bmurray/faster-rcnn.pytorch/data
Loaded dataset `custom_dataset_test` for training
Set proposal method: gt
Preparing training data...
Traceback (most recent call last):
  File "test_net.py", line 155, in <module>
    imdb, roidb, ratio_list, ratio_index = combined_roidb(args.imdbval_name, False)
  File "/home/bmurray/faster-rcnn.pytorch/lib/roi_data_layer/roidb.py", line 116, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "/home/bmurray/faster-rcnn.pytorch/lib/roi_data_layer/roidb.py", line 116, in <listcomp>
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "/home/bmurray/faster-rcnn.pytorch/lib/roi_data_layer/roidb.py", line 113, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/home/bmurray/faster-rcnn.pytorch/lib/roi_data_layer/roidb.py", line 102, in get_training_roidb
    prepare_roidb(imdb)
  File "/home/bmurray/faster-rcnn.pytorch/lib/roi_data_layer/roidb.py", line 21, in prepare_roidb
    roidb = imdb.roidb
  File "/home/bmurray/faster-rcnn.pytorch/lib/datasets/imdb.py", line 76, in roidb
    self._roidb = self.roidb_handler()
  File "/home/bmurray/faster-rcnn.pytorch/lib/datasets/custom_dataset.py", line 129, in gt_roidb
    for index in self.image_index]
  File "/home/bmurray/faster-rcnn.pytorch/lib/datasets/custom_dataset.py", line 129, in <listcomp>
    for index in self.image_index]
  File "/home/bmurray/faster-rcnn.pytorch/lib/datasets/custom_dataset.py", line 208, in _load_pascal_annotation
    tree = ET.parse(filename)
  File "/home/bmurray/anaconda3/envs/fasterrcnn-env/lib/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/home/bmurray/anaconda3/envs/fasterrcnn-env/lib/python3.6/xml/etree/ElementTree.py", line 586, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/bmurray/faster-rcnn.pytorch/data/custom_dataset/Annotations/test_example_0.xml'

**Comment by Jinsol-Lee** [comment]
Did you make any progress with this?

**Comment by brandenkmurray** [comment]
@Jinsol-Lee Not really. I currently create dummy annotation files as a workaround and it works, but that's not an ideal solution.

**Comment by ioneliabuzatu** [comment]
any updates, please?

**Comment by thomasr96** [comment]
You gotta use the demo.py file. There's a little example in the readme. Demo.py outputs the images with bounding boxes in them. The test_net.py code is used to evaluate the model against ground truth values.
