### ISSUE TITLE
i train my own database,but there is a question?who can help me? please.

### ISSUE THREAD

**Issue by dazhangzhang** [jwyang/faster-rcnn.pytorch#464]
my pc  gtx 1080ti  centos7 
my question 
Traceback (most recent call last):
  File "trainval_net.py", line 310, in <module>
    data = next(data_iter)
  File "/mnt/dell/anaconda3/envs/pytorch040/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/mnt/dell/anaconda3/envs/pytorch040/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/mnt/dell/anaconda3/envs/pytorch040/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/mnt/dell/anaconda3/envs/pytorch040/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/mnt/dell/faster-rcnn.pytorch/lib/roi_data_layer/roibatchLoader.py", line 150, in __getitem__
    x_s = np.random.choice(range(x_s_min, x_s_max))
  File "mtrand.pyx", line 1126, in mtrand.RandomState.choice
ValueError: a must be non-empty
Who has the same situation as me, please help me.

**Comment by adityac8** [comment]
You could check the values of `x_s_min` and `x_s_max` by
```
try:
    x_s = np.random.choice(range(x_s_min, x_s_max))
except:
    print(x_s_min, x_s_max)
````

You might be getting wrong values here.

**Comment by devendraswamy** [comment]
Actually I have my own dataset in format of ["filename" "boxes label values Like x-min y-min x-max y-max" "class-name"] and filename consist the path of the image, so how can given this dataset to model for testing and training , please  help me ..
