### ISSUE TITLE
i hava a problem "undefined symbol: __cudaPopCallConfiguration"

### ISSUE THREAD

**Issue by jaeyun95** [jwyang/faster-rcnn.pytorch#465]
i have a prolbem like this:

Traceback (most recent call last):
  File "demo.py", line 31, in <module>
    from model.nms.nms_wrapper import nms
  File "/home/ailab/JY/faster-rcnn.pytorch/lib/model/nms/nms_wrapper.py", line 10, in <module>
    from model.nms.nms_gpu import nms_gpu
  File "/home/ailab/JY/faster-rcnn.pytorch/lib/model/nms/nms_gpu.py", line 4, in <module>
    from ._ext import nms
  File "/home/ailab/JY/faster-rcnn.pytorch/lib/model/nms/_ext/nms/__init__.py", line 3, in <module>
    from ._nms import lib as _lib, ffi as _ffi
ImportError: /home/ailab/JY/faster-rcnn.pytorch/lib/model/nms/_ext/nms/_nms.so: undefined symbol: __cudaPopCallConfiguration

i use
2080Ti
CUDA10.0
CUDNN 7.3

i saw that this problem must change CUDA version. but 2080Ti only support CUDA10...
T^T help.....

**Comment by clw5180** [comment]
> i have a prolbem like this:
> 
> Traceback (most recent call last):
> File "demo.py", line 31, in
> from model.nms.nms_wrapper import nms
> File "/home/ailab/JY/faster-rcnn.pytorch/lib/model/nms/nms_wrapper.py", line 10, in
> from model.nms.nms_gpu import nms_gpu
> File "/home/ailab/JY/faster-rcnn.pytorch/lib/model/nms/nms_gpu.py", line 4, in
> from ._ext import nms
> File "/home/ailab/JY/faster-rcnn.pytorch/lib/model/nms/_ext/nms/**init**.py", line 3, in
> from ._nms import lib as _lib, ffi as _ffi
> ImportError: /home/ailab/JY/faster-rcnn.pytorch/lib/model/nms/_ext/nms/_nms.so: undefined symbol: __cudaPopCallConfiguration
> 
> i use
> 2080Ti
> CUDA10.0
> CUDNN 7.3
> 
> i saw that this problem must change CUDA version. but 2080Ti only support CUDA10...
> T^T help.....

same problem，any big old help me。。。

**Comment by yzheng97** [comment]
same problem here

**Comment by yzheng97** [comment]
> same problem here

Solve the problem by installing pytorch0.4.1 with cuda9.2
Platform: RTX2080Ti, CUDA10.0

**Comment by moondaiy** [comment]
> > same problem here
> 
> Solve the problem by installing pytorch0.4.1 with cuda9.2
> Platform: RTX2080Ti, CUDA10.0, Cudnn7.5

Platform: RTX2080Ti, CUDA10.0, Cudnn7.5 是你最终的安装环境么

**Comment by dongzhenguo2016** [comment]
I have the same problem. please help me

**Comment by Linkeyboard** [comment]
Watch out the version of cuda, and choose appropriate version of pytorch when installing.

**Comment by ZhuoyaYang** [comment]
Same problem...

**Comment by wuchangsheng951** [comment]
same problem. HelP me anyone!!!!!!!!!!!!!!

**Comment by wuchangsheng951** [comment]
> > same problem here
> 
> Solve the problem by installing pytorch0.4.1 with cuda9.2
> Platform: RTX2080Ti, CUDA10.0, Cudnn7.5

can you tell some details about how to solve this question?
