### ISSUE TITLE
undefined symbol when trying to call

### ISSUE THREAD

**Issue by EMCP** [jwyang/faster-rcnn.pytorch#471]
VOC data sets worked, but on my first attempt to run COCO based datasets, I get this

```
emcp@k:faster-rcnn.private$ CUDA_VISIBLE_DEVICES=0 python trainval_net.py --dataset coco --net res101 --bs 1 --nw 1 --lr .001 --lr_decay_step 10 --cuda
python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
Traceback (most recent call last):
  File "trainval_net.py", line 33, in <module>
    from model.faster_rcnn.vgg16 import vgg16
  File "faster-rcnn.private/lib/model/faster_rcnn/vgg16.py", line 16, in <module>
    from model.faster_rcnn.faster_rcnn import _fasterRCNN
  File "faster-rcnn.private/lib/model/faster_rcnn/faster_rcnn.py", line 10, in <module>
    from model.rpn.rpn import _RPN
  File "faster-rcnn.private/lib/model/rpn/rpn.py", line 8, in <module>
    from .proposal_layer import _ProposalLayer
  File "faster-rcnn.private/lib/model/rpn/proposal_layer.py", line 21, in <module>
    from model.roi_layers import nms
  File "faster-rcnn.private/lib/model/roi_layers/__init__.py", line 3, in <module>
    from .nms import nms
  File "faster-rcnn.private/lib/model/roi_layers/nms.py", line 3, in <module>
    from model import _C
ImportError: faster-rcnn.private/lib/model/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs
emcp@k:faster-rcnn.private$ 

```

**Comment by EMCP** [comment]
had incorrect anaconda env loaded

**Comment by kathydo** [comment]
Having same problem. Do you know what module was missing?

**Comment by EMCP** [comment]
@kathydo , It turned out I hadn't activated my conda env which I had loaded with according to the instructions.

It seems the best advice I can give is to repeat the instructions in a fresh conda environment and try again
