### ISSUE TITLE
How to compile the lib on the win10+pytorch0.4.1+cuda9.2?

### ISSUE THREAD

**Issue by y78h11b09** [jwyang/faster-rcnn.pytorch#487]
Hi ,I  had successufully compiled the nms of lib by 'python setup.py install',  but later, i got the  problem, as follows:

Traceback (most recent call last):
  File "E:/Pytorch_Room/faster-rcnn_pytorch-master/demo.py", line 31, in <module>
    from lib.model.nms.nms_wrapper import nms
  File "E:\Pytorch_Room\faster-rcnn_pytorch-master\lib\model\nms\nms_wrapper.py", line 10, in <module>
    from .nms_gpu import gpu_nms
  File "model\nms\nms_gpu.py", line 4, in init model.nms.nms_gpu
  File "E:\Pytorch_Room\faster-rcnn_pytorch-master\lib\model\nms\_ext\nms\__init__.py", line 3, in <module>
    from ._nms import lib as _lib, ffi as _ffi
  ModuleNotFoundError: No module named 'lib.model.nms._ext.nms._nms'

win 10 + python3 +pytorch 0.4.1_cuda 9.2_cudnn7
GTX 1080Ti

**Comment by YYsmith** [comment]
hello, is there any solution  for  this issue?

**Comment by zhenhuaFu** [comment]
https://blog.csdn.net/cube_suger/article/details/112648721
