### ISSUE TITLE
Testing: evaluate_detections "NotImplementedError"

### ISSUE THREAD

**Issue by mahaling** [jwyang/faster-rcnn.pytorch#488]
I got a vgg16 successfully trained on a custom dataset and it loaded perfectly while testing. 
The test_net.py code has a "imdb.evaluate_detections" at the end and this function is not implemented yet. 
I am getting the following error.
Traceback (most recent call last):
  File "test_net.py", line 333, in <module>
    imdb.evaluate_detections(all_boxes, output_dir)
  File "/faster_rcnn/lib/datasets/imdb.py", line 108, in evaluate_detections
    raise NotImplementedError
NotImplementedError

Is there something I am missing here?. 
Any help would be appreciated. Thanks.

**Comment by berniel** [comment]
Same question here.
Besides, should I just uncomment the evaluate_recall function if I want to evaluate recall?
