### ISSUE TITLE
ModuleNotFoundError: No module named 'datasets.factory'

### ISSUE THREAD

**Issue by yiiiruu** [jwyang/faster-rcnn.pytorch#489]
When I run the trainval_net.py I meet an error
Traceback (most recent call last):
  File "/home/zyr/faster-rcnn.pytorch/trainval_net.py", line 28, in <module>
    from roi_data_layer.roidb import combined_roidb
  File "/home/zyr/faster-rcnn.pytorch/lib/roi_data_layer/roidb.py", line 12, in <module>
    from datasets.factory import get_imdb
ModuleNotFoundError: No module named 'datasets.factory'

and I have __init__.py in my datasets dictionary.
can someone tell me what's the error?thank you

**Comment by yiiiruu** [comment]
I add __init__.py in lib and it solved.

**Comment by yiiiruu** [comment]
add /lib dictronary to environment use:
export PYTHONPATH=/home/zyr/faster-rcnn.pytorch/lib
