### ISSUE TITLE
AssertionError: Path does not exist

### ISSUE THREAD

**Issue by DiaoYuxian** [jwyang/faster-rcnn.pytorch#507]
Loaded dataset `voc_2007_trainval` for training
Set proposal method: gt
Appending horizontally-flipped training examples...
Traceback (most recent call last):
  File "trainval_net.py", line 197, in <module>
    imdb, roidb, ratio_list, ratio_index = combined_roidb(args.imdb_name)
  File "/public/home/qiaochen/Diao/new/faster-rcnn-mydata/lib/roi_data_layer/roidb.py", line 116, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "/public/home/qiaochen/Diao/new/faster-rcnn-mydata/lib/roi_data_layer/roidb.py", line 116, in <listcomp>
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "/public/home/qiaochen/Diao/new/faster-rcnn-mydata/lib/roi_data_layer/roidb.py", line 113, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/public/home/qiaochen/Diao/new/faster-rcnn-mydata/lib/roi_data_layer/roidb.py", line 97, in get_training_roidb
    imdb.append_flipped_images()
  File "/public/home/qiaochen/Diao/new/faster-rcnn-mydata/lib/datasets/imdb.py", line 116, in append_flipped_images
    widths = self._get_widths()
  File "/public/home/qiaochen/Diao/new/faster-rcnn-mydata/lib/datasets/imdb.py", line 112, in _get_widths
    for i in range(self.num_images)]
  File "/public/home/qiaochen/Diao/new/faster-rcnn-mydata/lib/datasets/imdb.py", line 112, in <listcomp>
    for i in range(self.num_images)]
  File "/public/home/qiaochen/Diao/new/faster-rcnn-mydata/lib/datasets/pascal_voc.py", line 80, in image_path_at
    return self.image_path_from_index(self._image_index[i])
  File "/public/home/qiaochen/Diao/new/faster-rcnn-mydata/lib/datasets/pascal_voc.py", line 95, in image_path_from_index
    'Path does not exist: {}'.format(image_path)
AssertionError: Path does not exist: /public/home/qiaochen/Diao/new/faster-rcnn-mydata/data/VOCdevkit2007/VOC2007/JPEGImages/﻿000001.jpg

When I put my own data under VOCdevkit2007/VOC2007, I got the error above.
But I have checked the path exists and I don't use a symlink.

**Comment by littleTaodog** [comment]
Hi, I got same problem, have you solved this?
