### ISSUE TITLE
sh make.sh error ImportError: libffi-45372312.so.6.0.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by 114153** [jwyang/faster-rcnn.pytorch#538]
when do sh make.sh and then i meet this problem :

sh make.sh 

running build_ext
skipping 'model/utils/bbox.c' Cython extension (up-to-date)
skipping 'pycocotools/_mask.c' Cython extension (up-to-date)
Compiling nms kernels by nvcc...
Including CUDA code.
/home/CAD409/teng/object_detect/faster_rcnn/lib/model/nms
['/home/CAD409/teng/object_detect/faster_rcnn/lib/model/nms/src/nms_cuda_kernel.cu.o']
Traceback (most recent call last):
  File "build.py", line 33, in <module>
    extra_objects=extra_objects
  File "/usr/lib64/python2.7/site-packages/torch/utils/ffi/__init__.py", line 176, in create_extension
    ffi = cffi.FFI()
  File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 46, in __init__
    import _cffi_backend as backend
ImportError: libffi-45372312.so.6.0.4: cannot open shared object file: No such file or directory
Compiling roi pooling kernels by nvcc...
/home/CAD409/teng/object_detect/faster_rcnn/lib/model/roi_pooling
Including CUDA code.
Traceback (most recent call last):
  File "build.py", line 32, in <module>
    extra_objects=extra_objects
  File "/usr/lib64/python2.7/site-packages/torch/utils/ffi/__init__.py", line 176, in create_extension
    ffi = cffi.FFI()
  File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 46, in __init__
    import _cffi_backend as backend
**ImportError: libffi-45372312.so.6.0.4: cannot open shared object file: No such file or directory**
Compiling roi align kernels by nvcc...
/home/CAD409/teng/object_detect/faster_rcnn/lib/model/roi_align
Including CUDA code.
Traceback (most recent call last):
  File "build.py", line 34, in <module>
    extra_objects=extra_objects
  File "/usr/lib64/python2.7/site-packages/torch/utils/ffi/__init__.py", line 176, in create_extension
    ffi = cffi.FFI()
  File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 46, in __init__
    import _cffi_backend as backend
**ImportError: libffi-45372312.so.6.0.4: cannot open shared object file: No such file or directory**
Compiling roi crop kernels by nvcc...
Including CUDA code.
/home/CAD409/teng/object_detect/faster_rcnn/lib/model/roi_crop
Traceback (most recent call last):
  File "build.py", line 32, in <module>
    extra_objects=extra_objects
  File "/usr/lib64/python2.7/site-packages/torch/utils/ffi/__init__.py", line 176, in create_extension
    ffi = cffi.FFI()
  File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 46, in __init__
    import _cffi_backend as backend
**ImportError: libffi-45372312.so.6.0.4: cannot open shared object file: No such file or directory**

somebody know how to solve this problem ? thanks !

**Comment by everythoughthelps** [comment]
got the same error

**Comment by yustaub** [comment]
@everythoughthelps @114153 did you solve this?
