### ISSUE TITLE
TypeError: dist must be a Distribution instance

### ISSUE THREAD

**Issue by Amazingren** [jwyang/faster-rcnn.pytorch#539]
When a run `sh make.sh`, then the following comes up, how can I overcome this problem?
and my environment:
- Ubuntu18.04
- Python3.7(Anoconda)
- Pytorch1.0.2
Help!!!!!
`running build_ext
skipping 'model/utils/bbox.c' Cython extension (up-to-date)
skipping 'pycocotools/_mask.c' Cython extension (up-to-date)
Compiling nms kernels by nvcc...
Including CUDA code.
/home/renb/project/faster-rcnn.pytorch/lib/model/nms
['/home/renb/project/faster-rcnn.pytorch/lib/model/nms/src/nms_cuda_kernel.cu.o']
Traceback (most recent call last):
  File "build.py", line 35, in <module>
    extra_objects=extra_objects
  File "/home/renb/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 228, in __init__
    super(BuildExtension, self).__init__(*args, **kwargs)
  File "/home/renb/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in __init__
    _Command.__init__(self, dist)
  File "/home/renb/anaconda3/lib/python3.7/distutils/cmd.py", line 57, in __init__
    raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance
Compiling roi pooling kernels by nvcc...
/home/renb/project/faster-rcnn.pytorch/lib/model/roi_pooling
Including CUDA code.
Traceback (most recent call last):
  File "build.py", line 32, in <module>
    extra_objects=extra_objects
  File "/home/renb/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 228, in __init__
    super(BuildExtension, self).__init__(*args, **kwargs)
  File "/home/renb/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in __init__
    _Command.__init__(self, dist)
  File "/home/renb/anaconda3/lib/python3.7/distutils/cmd.py", line 57, in __init__
    raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance
Compiling roi align kernels by nvcc...
/home/renb/project/faster-rcnn.pytorch/lib/model/roi_align
Including CUDA code.
Traceback (most recent call last):
  File "build.py", line 35, in <module>
    extra_objects=extra_objects
  File "/home/renb/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 228, in __init__
    super(BuildExtension, self).__init__(*args, **kwargs)
  File "/home/renb/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in __init__
    _Command.__init__(self, dist)
  File "/home/renb/anaconda3/lib/python3.7/distutils/cmd.py", line 57, in __init__
    raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance
Compiling roi crop kernels by nvcc...
Including CUDA code.
/home/renb/project/faster-rcnn.pytorch/lib/model/roi_crop
Traceback (most recent call last):
  File "build.py", line 32, in <module>
    extra_objects=extra_objects
  File "/home/renb/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 228, in __init__
    super(BuildExtension, self).__init__(*args, **kwargs)
  File "/home/renb/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in __init__
    _Command.__init__(self, dist)
  File "/home/renb/anaconda3/lib/python3.7/distutils/cmd.py", line 57, in __init__
    raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance
`

**Comment by Amazingren** [comment]
Wait Online!

**Comment by jwyang** [comment]
Use pytorch 1.0.0 instead.

**Comment by dongzhi0312** [comment]
Ubuntu16.04
Python3.5(Anoconda)
Pytorch1.0.0
help
I used torch 1.0.0 still encounter an same error
['/home/zzd/cv/object-detectioin/faster-rcnn.pytorch/lib/model/nms/src/nms_cuda_kernel.cu.o']
Traceback (most recent call last):
  File "build.py", line 43, in <module>
    extra_objects=extra_objects
  File "/home/zzd/anaconda3/envs/py35/lib/python3.5/site-packages/torch/utils/cpp_extension.py", line 228, in __init__
    super(BuildExtension, self).__init__(*args, **kwargs)
  File "/home/zzd/anaconda3/envs/py35/lib/python3.5/site-packages/setuptools/__init__.py", line 127, in __init__
    _Command.__init__(self, dist)
  File "/home/zzd/anaconda3/envs/py35/lib/python3.5/distutils/cmd.py", line 57, in __init__
    raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance
Compiling roi pooling kernels by nvcc...
/home/zzd/cv/object-detectioin/faster-rcnn.pytorch/lib/model/roi_pooling
Including CUDA code.
Traceback (most recent call last):
  File "build.py", line 41, in <module>
    extra_objects=extra_objects
  File "/home/zzd/anaconda3/envs/py35/lib/python3.5/site-packages/torch/utils/cpp_extension.py", line 228, in __init__
    super(BuildExtension, self).__init__(*args, **kwargs)
  File "/home/zzd/anaconda3/envs/py35/lib/python3.5/site-packages/setuptools/__init__.py", line 127, in __init__
    _Command.__init__(self, dist)
  File "/home/zzd/anaconda3/envs/py35/lib/python3.5/distutils/cmd.py", line 57, in __init__
    raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance

**Comment by Amazingren** [comment]
> Ubuntu16.04
> Python3.5(Anoconda)
> Pytorch1.0.0
> **help**
> **I used torch 1.0.0 still encounter an same error**
> ['/home/zzd/cv/object-detectioin/faster-rcnn.pytorch/lib/model/nms/src/nms_cuda_kernel.cu.o']
> Traceback (most recent call last):
> File "build.py", line 43, in 
> extra_objects=extra_objects
> File "/home/zzd/anaconda3/envs/py35/lib/python3.5/site-packages/torch/utils/cpp_extension.py", line 228, in **init**
> super(BuildExtension, self).**init**(*args, **kwargs)
> File "/home/zzd/anaconda3/envs/py35/lib/python3.5/site-packages/setuptools/**init**.py", line 127, in **init**
> _Command.**init**(self, dist)
> File "/home/zzd/anaconda3/envs/py35/lib/python3.5/distutils/cmd.py", line 57, in **init**
> raise TypeError("dist must be a Distribution instance")
> TypeError: dist must be a Distribution instance
> Compiling roi pooling kernels by nvcc...
> /home/zzd/cv/object-detectioin/faster-rcnn.pytorch/lib/model/roi_pooling
> Including CUDA code.
> Traceback (most recent call last):
> File "build.py", line 41, in 
> extra_objects=extra_objects
> File "/home/zzd/anaconda3/envs/py35/lib/python3.5/site-packages/torch/utils/cpp_extension.py", line 228, in **init**
> super(BuildExtension, self).**init**(*args, **kwargs)
> File "/home/zzd/anaconda3/envs/py35/lib/python3.5/site-packages/setuptools/**init**.py", line 127, in **init**
> _Command.**init**(self, dist)
> File "/home/zzd/anaconda3/envs/py35/lib/python3.5/distutils/cmd.py", line 57, in **init**
> raise TypeError("dist must be a Distribution instance")
> TypeError: dist must be a Distribution instance

LoL~
Just now I set my pytorch from 1.0.1——1.0.0

**Comment by Amazingren** [comment]
> Ubuntu16.04
> Python3.5(Anoconda)
> Pytorch1.0.0
> **help**
> **I used torch 1.0.0 still encounter an same error**
> ['/home/zzd/cv/object-detectioin/faster-rcnn.pytorch/lib/model/nms/src/nms_cuda_kernel.cu.o']
> Traceback (most recent call last):
> File "build.py", line 43, in 
> extra_objects=extra_objects
> File "/home/zzd/anaconda3/envs/py35/lib/python3.5/site-packages/torch/utils/cpp_extension.py", line 228, in **init**
> super(BuildExtension, self).**init**(*args, **kwargs)
> File "/home/zzd/anaconda3/envs/py35/lib/python3.5/site-packages/setuptools/**init**.py", line 127, in **init**
> _Command.**init**(self, dist)
> File "/home/zzd/anaconda3/envs/py35/lib/python3.5/distutils/cmd.py", line 57, in **init**
> raise TypeError("dist must be a Distribution instance")
> TypeError: dist must be a Distribution instance
> Compiling roi pooling kernels by nvcc...
> /home/zzd/cv/object-detectioin/faster-rcnn.pytorch/lib/model/roi_pooling
> Including CUDA code.
> Traceback (most recent call last):
> File "build.py", line 41, in 
> extra_objects=extra_objects
> File "/home/zzd/anaconda3/envs/py35/lib/python3.5/site-packages/torch/utils/cpp_extension.py", line 228, in **init**
> super(BuildExtension, self).**init**(*args, **kwargs)
> File "/home/zzd/anaconda3/envs/py35/lib/python3.5/site-packages/setuptools/**init**.py", line 127, in **init**
> _Command.**init**(self, dist)
> File "/home/zzd/anaconda3/envs/py35/lib/python3.5/distutils/cmd.py", line 57, in **init**
> raise TypeError("dist must be a Distribution instance")
> TypeError: dist must be a Distribution instance

Maybe you could have a look at this [https://stackoverflow.com/questions/21136266/typeerror-dist-must-be-a-distribution-instance](url)
Hope this could shed you some light, however, it does not work for me

**Comment by dongzhi0312** [comment]
Ubuntu16.04
**Python2.7(Anoconda)
Pytorch1.0.0**
**you maybe clone not correct branch confirm you clone the branch of pytorch-1.0**
后面的步骤还没有验证，不过目前，run， **python setup.py build develop** 没有报错
running develop
running egg_info
creating faster_rcnn.egg-info
writing faster_rcnn.egg-info/PKG-INFO
writing top-level names to faster_rcnn.egg-info/top_level.txt
writing dependency_links to faster_rcnn.egg-info/dependency_links.txt
writing manifest file 'faster_rcnn.egg-info/SOURCES.txt'
reading manifest file 'faster_rcnn.egg-info/SOURCES.txt'
writing manifest file 'faster_rcnn.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-2.7/model/_C.so -> model
Creating /home/zzd/anaconda3/envs/py27/lib/python2.7/site-packages/faster-rcnn.egg-link (link to .)
Adding faster-rcnn 0.1 to easy-install.pth file

Installed /home/zzd/cv/object-detectioin/faster-rcnn.pytorch-pytorch-1.0/lib
Processing dependencies for faster-rcnn==0.1
Finished processing dependencies for faster-rcnn==0.1

**Comment by AlexanderHustinx** [comment]
Which CUDA and GCC version do you use?

**Comment by dongzhi0312** [comment]
yes,I clone the faster-rcnn.pytorch-1.0 and run python step.py build develop, and follow the 1.0 instruction

**Comment by AlexanderHustinx** [comment]
> yes,I clone the faster-rcnn.pytorch-1.0 and run python step.py build develop, and follow the 1.0 instruction
My previous comment was directed at @Amazingren 

@dongzhi0312, which version of CUDA and GCC do you use?
What error are you getting?

**Comment by sjanbs** [comment]
Ubuntu16.04
Python3.6(Anoconda)
Pytorch1.0.1
maybe you could run 
python setup.py install

**Comment by zhanwenchen** [comment]
If someone is still having the problem for torch-related issue together with create_extension, you should try this article: https://blog.csdn.net/cyy01234/article/details/112747610?ops_request_misc=&request_id=&biz_id=102&utm_term=TypeError:%20dist%20must%20be%20a%20Dist&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduweb~default-6-112747610.pc_search_result_control_group&spm=1018.2226.3001.4187

**Comment by hnuzhy** [comment]
> If someone is still having the problem for torch-related issue together with create_extension, you should try this article: https://blog.csdn.net/cyy01234/article/details/112747610?ops_request_misc=&request_id=&biz_id=102&utm_term=TypeError:%20dist%20must%20be%20a%20Dist&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduweb~default-6-112747610.pc_search_result_control_group&spm=1018.2226.3001.4187

It's very nice of your solution link~

**Comment by Amazingren** [comment]
您的来信已经收到，稍后进行回复，谢谢~
