### ISSUE TITLE
test中报错

### ISSUE THREAD

**Issue by Youggie** [jwyang/faster-rcnn.pytorch#545]
RuntimeError: get_device is not implemented for type torch.FloatTensor
how to solve this  problem?

**Comment by AlexanderHustinx** [comment]
With only this information I don't know how to solve the problem.
Could you share the full error and stack trace?

**Comment by Youggie** [comment]
assert output.get_device() == input1.get_device(), "output and input1 must on the same device"
RuntimeError: get_device is not implemented for type torch.FloatTensor

**Comment by Youggie** [comment]
Traceback (most recent call last):
  File "/usr/lib/pycharm-community/helpers/pydev/pydevd.py", line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/usr/lib/pycharm-community/helpers/pydev/pydevd.py", line 974, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/faster-rcnn.pytorch-master/demo.py", line 313, in <module>
    rois_label = fasterRCNN(im_data, im_info, gt_boxes, num_boxes)
  File "/anaconda2/envs/2.7/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File /faster-rcnn.pytorch-master/lib/model/faster_rcnn/faster_rcnn.py", line 79, in forward
    pooled_feat = self.RCNN_roi_crop(base_feat, Variable(grid_yx).detach())
  File "/anaconda2/envs/2.7/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/faster-rcnn.pytorch-master/lib/model/roi_crop/modules/roi_crop.py", line 8, in forward
    return RoICropFunction()(input1, input2)
  File "/faster-rcnn.pytorch-master/lib/model/roi_crop/functions/roi_crop.py", line 15, in forward
    assert output.get_device() == input1.get_device(), "output and input1 must on the same device"
RuntimeError: get_device is not implemented for type torch.FloatTensor

**Comment by cugblizz** [comment]
> RuntimeError: get_device is not implemented for type torch.FloatTensor
> how to solve this problem?

hi,did you solve this problem?I also met this problem.

**Comment by Youggie** [comment]
在终端运行 python test.py --cuda就OK了，不要直接在pycharm里面run，必须加上--cuda




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "cugblizz"<notifications@github.com&gt;; 
发送时间: 2019年9月30日(星期一) 下午5:38
收件人: "jwyang/faster-rcnn.pytorch"<faster-rcnn.pytorch@noreply.github.com&gt;; 
抄送: "Van Persie"<1186560029@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [jwyang/faster-rcnn.pytorch] test中报错 (#545)



 
RuntimeError: get_device is not implemented for type torch.FloatTensor
how to solve this problem?
 
hi,did you solve this problem?I also met this problem.
