### ISSUE TITLE
How to only fine-tune the FC layer of resnet?

### ISSUE THREAD

**Issue by keineahnung2345** [jwyang/faster-rcnn.pytorch#579]
From the following code snippet:
https://github.com/jwyang/faster-rcnn.pytorch/blob/56aff1cdfeffa88fbc0668276b9e0a202beb1537/lib/model/faster_rcnn/resnet.py#L253-L259
It seems only fine-tune the FC layer is not possible, and resnet's stage 5 must be tuned, what's the reason behind this setting?

**Comment by zhengxinvip** [comment]
I want to fine-tune the FC layer too, Do you slove your issue, I need your help ,thanks.

**Comment by keineahnung2345** [comment]
In `lib/model/faster_rcnn/resnet.py`, I changed 
```
assert (0 <= cfg.RESNET.FIXED_BLOCKS < 4)
``` 
into:
```
assert (0 <= cfg.RESNET.FIXED_BLOCKS <= 4)
if cfg.RESNET.FIXED_BLOCKS >= 4:
    for p in self.RCNN_top[0].parameters(): p.requires_grad=False
```
And added the following code snippets into `trainval_net.py`:
```
parser.add_argument('--resnet_fixed_blocks', dest='resnet_fixed_blocks',
    help='fix how many blocks in resnet',
    default=1, type=int)
```
```
cfg.RESNET.FIXED_BLOCKS = args.resnet_fixed_blocks
```
When training, I also needed to add the flag `--resnet_fixed_blocks 4`.

But in my experiment, the MAPs of fixing 3 and 4 blocks are 92 and 43 respectively, so I have changed to use the original setting. Look forward to your experiment result :).

**Comment by zhengxinvip** [comment]
> In lib/model/faster_rcnn/resnet.py, I changed
> assert (0 <= cfg.RESNET.FIXED_BLOCKS < 4)
> 
> into:
> assert (0 <= cfg.RESNET.FIXED_BLOCKS <= 4)
> if cfg.RESNET.FIXED_BLOCKS >= 4:
>     for p in self.RCNN_top[0].parameters(): p.requires_grad=False
> 
> And added the following code snippets into trainval_net.py:
> parser.add_argument('--resnet_fixed_blocks', dest='resnet_fixed_blocks',
>     help='fix how many blocks in resnet',
>     default=1, type=int)
> 
> cfg.RESNET.FIXED_BLOCKS = args.resnet_fixed_blocks
> 
> When training, I also needed to add the flag --resnet_fixed_blocks 4.
> But in my experiment, the MAPs of fixing 3 and 4 blocks are 92 and 43 respectively, so I have changed to use the original setting. Look forward to your experiment result :).

I train a model with my own dataset , now I want to fine-tune this model with my other dataset, what I do just take this model to the ./data/pretrained_model  and change the path but I got this error:
loading checkpoint /home/wuwenfu/faster-rcnn.pytorch-master/data/pretrained_model/faster_rcnn_1_60_1284.pth
Traceback (most recent call last):
  File "trainval_net.py", line 282, in <module>
    fasterRCNN.load_state_dict(checkpoint['model'])
  File "/home/wuwenfu/.conda/envs/pytorch04/lib/python3.5/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for vgg16:
	Unexpected key(s) in state_dict: "RCNN_base.0.weight", "RCNN_base.1.weight", "RCNN_base.1.bias", "RCNN_base.1.running_mean", "RCNN_base.1.running_var", "RCNN_base.4.0.conv1.weight", "RCNN_base.4.0.bn1.weight", "RCNN_base.4.0.bn1.bias", "RCNN_base.4.0.bn1.running_mean", "RCNN_base.4.0.bn1.running_var", "RCNN_base.4.0.conv2.weight", "RCNN_base.4.0.bn2.weight", "RCNN_base.4.0.bn2.bias", "RCNN_base.4.0.bn2.running_mean", "RCNN_base.4.0.bn2.running_var", "RCNN_base.4.0.conv3.weight", "RCNN_base.4.0.bn3.weight", "RCNN_base.4.0.bn3.bias", "RCNN_base.4.0.bn3.running_mean", "RCNN_base.4.0.bn3.running_var", "RCNN_base.4.0.downsample.0.weight", "RCNN_base.4.0.downsample.1.weight", "RCNN_base.4.0.downsample.1.bias", "RCNN_base.4.0.downsample.1.running_mean", "RCNN_base.4.0.downsample.1.running_var", "RCNN_base.4.1.conv1.weight", "RCNN_base.4.1.bn1.weight", "RCNN_base.4.1.bn1.bias", "RCNN_base.4.1.bn1.running_mean", "RCNN_base.4.1.bn1.running_var", "RCNN_base.4.1.conv2.weight", "RCNN_base.4.1.bn2.weight", "RCNN_base.4.1.bn2.bias", "RCNN_base.4.1.bn2.running_mean", "RCNN_base.4.1.bn2.running_var", "RCNN_base.4.1.conv3.weight", "RCNN_base.4.1.bn3.weight", "RCNN_base.4.1.bn3.bias", "RCNN_base.4.1.bn3.running_mean", "RCNN_base.4.1.bn3.running_var", "RCNN_base.4.2.conv1.weight", "RCNN_base.4.2.bn1.weight", "RCNN_base.4.2.bn1.bias", "RCNN_base.4.2.bn1.running_mean", "RCNN_base.4.2.bn1.running_var", "RCNN_base.4.2.conv2.weight", "RCNN_base.4.2.bn2.weight", "RCNN_base.4.2.bn2.bias", "RCNN_base.4.2.bn2.running_mean", "RCNN_base.4.2.bn2.running_var", "RCNN_base.4.2.conv3.weight", "RCNN_base.4.2.bn3.weight", "RCNN_base.4.2.bn3.bias", "RCNN_base.4.2.bn3.running_mean", "RCNN_base.4.2.bn3.running_var", "RCNN_base.5.0.conv1.weight", "RCNN_base.5.0.bn1.weight", "RCNN_base.5.0.bn1.bias", "RCNN_base.5.0.bn1.running_mean", "RCNN_base.5.0.bn1.running_var", "RCNN_base.5.0.conv2.weight", "RCNN_base.5.0.bn2.weight", "RCNN_base.5.0.bn2.bias", "RCNN_base.5.0.bn2.running_mean", "RCNN_base.5.0.bn2.running_var", "RCNN_base.5.0.conv3.weight", "RCNN_base.5.0.bn3.weight", "RCNN_base.5.0.bn3.bias", "RCNN_base.5.0.bn3.running_mean", "RCNN_base.5.0.bn3.running_var", "RCNN_base.5.0.downsample.0.weight", "RCNN_base.5.0.downsample.1.weight", "RCNN_base.5.0.downsample.1.bias", "RCNN_base.5.0.downsample.1.running_mean", "RCNN_base.5.0.downsample.1.running_var", "RCNN_base.5.1.conv1.weight", "RCNN_base.5.1.bn1.weight", "RCNN_base.5.1.bn1.bias", "RCNN_base.5.1.bn1.running_mean", "RCNN_base.5.1.bn1.running_var", "RCNN_base.5.1.conv2.weight", "RCNN_base.5.1.bn2.weight", "RCNN_base.5.1.bn2.bias", "RCNN_base.5.1.bn2.running_mean", "RCNN_base.5.1.bn2.running_var", "RCNN_base.5.1.conv3.weight", "RCNN_base.5.1.bn3.weight", "RCNN_base.5.1.bn3.bias", "RCNN_base.5.1.bn3.running_mean", "RCNN_base.5.1.bn3.running_var", "RCNN_base.5.2.conv1.weight", "RCNN_base.5.2.bn1.weight", "RCNN_base.5.2.bn1.bias", "RCNN_base.5.2.bn1.running_mean", "RCNN_base.5.2.bn1.running_var", "RCNN_base.5.2.conv2.weight", "RCNN_base.5.2.bn2.weight", "RCNN_base.5.2.bn2.bias", "RCNN_base.5.2.bn2.running_mean", "RCNN_base.5.2.bn2.running_var", "RCNN_base.5.2.conv3.weight", "RCNN_base.5.2.bn3.weight", "RCNN_base.5.2.bn3.bias", "RCNN_base.5.2.bn3.running_mean", "RCNN_base.5.2.bn3.running_var", "RCNN_base.5.3.conv1.weight", "RCNN_base.5.3.bn1.weight", "RCNN_base.5.3.bn1.bias", "RCNN_base.5.3.bn1.running_mean", "RCNN_base.5.3.bn1.running_var", "RCNN_base.5.3.conv2.weight", "RCNN_base.5.3.bn2.weight", "RCNN_base.5.3.bn2.bias", "RCNN_base.5.3.bn2.running_mean", "RCNN_base.5.3.bn2.running_var", "RCNN_base.5.3.conv3.weight", "RCNN_base.5.3.bn3.weight", "RCNN_base.5.3.bn3.bias", "RCNN_base.5.3.bn3.running_mean", "RCNN_base.5.3.bn3.running_var", "RCNN_base.6.0.conv1.weight", "RCNN_base.6.0.bn1.weight", "RCNN_base.6.0.bn1.bias", "RCNN_base.6.0.bn1.running_mean", "RCNN_base.6.0.bn1.running_var", "RCNN_base.6.0.conv2.weight", "RCNN_base.6.0.bn2.weight", "RCNN_base.6.0.bn2.bias", "RCNN_base.6.0.bn2.running_mean", "RCNN_base.6.0.bn2.running_var", "RCNN_base.6.0.conv3.weight", "RCNN_base.6.0.bn3.weight", "RCNN_base.6.0.bn3.bias", "RCNN_base.6.0.bn3.running_mean", "RCNN_base.6.0.bn3.running_var", "RCNN_base.6.0.downsample.0.weight", "RCNN_base.6.0.downsample.1.weight", "RCNN_base.6.0.downsample.1.bias", "RCNN_base.6.0.downsample.1.running_mean", "RCNN_base.6.0.downsample.1.running_var", "RCNN_base.6.1.conv1.weight", "RCNN_base.6.1.bn1.weight", "RCNN_base.6.1.bn1.bias", "RCNN_base.6.1.bn1.running_mean", "RCNN_base.6.1.bn1.running_var", "RCNN_base.6.1.conv2.weight", "RCNN_base.6.1.bn2.weight", "RCNN_base.6.1.bn2.bias", "RCNN_base.6.1.bn2.running_mean", "RCNN_base.6.1.bn2.running_var", "RCNN_base.6.1.conv3.weight", "RCNN_base.6.1.bn3.weight", "RCNN_base.6.1.bn3.bias", "RCNN_base.6.1.bn3.running_mean", "RCNN_base.6.1.bn3.running_var", "RCNN_base.6.2.conv1.weight", "RCNN_base.6.2.bn1.weight", "RCNN_base.6.2.bn1.bias", "RCNN_base.6.2.bn1.running_mean", "RCNN_base.6.2.bn1.running_var", "RCNN_base.6.2.conv2.weight", "RCNN_base.6.2.bn2.weight", "RCNN_base.6.2.bn2.bias", "RCNN_base.6.2.bn2.running_mean", "RCNN_base.6.2.bn2.running_var", "RCNN_base.6.2.conv3.weight", "RCNN_base.6.2.bn3.weight", "RCNN_base.6.2.bn3.bias", "RCNN_base.6.2.bn3.running_mean", "RCNN_base.6.2.bn3.running_var", "RCNN_base.6.3.conv1.weight", "RCNN_base.6.3.bn1.weight", "RCNN_base.6.3.bn1.bias", "RCNN_base.6.3.bn1.running_mean", "RCNN_base.6.3.bn1.running_var", "RCNN_base.6.3.conv2.weight", "RCNN_base.6.3.bn2.weight", "RCNN_base.6.3.bn2.bias", "RCNN_base.6.3.bn2.running_mean", "RCNN_base.6.3.bn2.running_var", "RCNN_base.6.3.conv3.weight", "RCNN_base.6.3.bn3.weight", "RCNN_base.6.3.bn3.bias", "RCNN_base.6.3.bn3.running_mean", "RCNN_base.6.3.bn3.running_var", "RCNN_base.6.4.conv1.weight", "RCNN_base.6.4.bn1.weight", "RCNN_base.6.4.bn1.bias", "RCNN_base.6.4.bn1.running_mean", "RCNN_base.6.4.bn1.running_var", "RCNN_base.6.4.conv2.weight", "RCNN_base.6.4.bn2.weight", "RCNN_base.6.4.bn2.bias", "RCNN_base.6.4.bn2.running_mean", "RCNN_base.6.4.bn2.running_var", "RCNN_base.6.4.conv3.weight", "RCNN_base.6.4.bn3.weight", "RCNN_base.6.4.bn3.bias", "RCNN_base.6.4.bn3.running_mean", "RCNN_base.6.4.bn3.running_var", "RCNN_base.6.5.conv1.weight", "RCNN_base.6.5.bn1.weight", "RCNN_base.6.5.bn1.bias", "RCNN_base.6.5.bn1.running_mean", "RCNN_base.6.5.bn1.running_var", "RCNN_base.6.5.conv2.weight", "RCNN_base.6.5.bn2.weight", "RCNN_base.6.5.bn2.bias", "RCNN_base.6.5.bn2.running_mean", "RCNN_base.6.5.bn2.running_var", "RCNN_base.6.5.conv3.weight", "RCNN_base.6.5.bn3.weight", "RCNN_base.6.5.bn3.bias", "RCNN_base.6.5.bn3.running_mean", "RCNN_base.6.5.bn3.running_var", "RCNN_base.6.6.conv1.weight", "RCNN_base.6.6.bn1.weight", "RCNN_base.6.6.bn1.bias", "RCNN_base.6.6.bn1.running_mean", "RCNN_base.6.6.bn1.running_var", "RCNN_base.6.6.conv2.weight", "RCNN_base.6.6.bn2.weight", "RCNN_base.6.6.bn2.bias", "RCNN_base.6.6.bn2.running_mean", "RCNN_base.6.6.bn2.running_var", "RCNN_base.6.6.conv3.weight", "RCNN_base.6.6.bn3.weight", "RCNN_base.6.6.bn3.bias", "RCNN_base.6.6.bn3.running_mean", "RCNN_base.6.6.bn3.running_var", "RCNN_base.6.7.conv1.weight", "RCNN_base.6.7.bn1.weight", "RCNN_base.6.7.bn1.bias", "RCNN_base.6.7.bn1.running_mean", "RCNN_base.6.7.bn1.running_var", "RCNN_base.6.7.conv2.weight", "RCNN_base.6.7.bn2.weight", "RCNN_base.6.7.bn2.bias", "RCNN_base.6.7.bn2.running_mean", "RCNN_base.6.7.bn2.running_var", "RCNN_base.6.7.conv3.weight", "RCNN_base.6.7.bn3.weight", "RCNN_base.6.7.bn3.bias", "RCNN_base.6.7.bn3.running_mean", "RCNN_base.6.7.bn3.running_var", "RCNN_base.6.8.conv1.weight", "RCNN_base.6.8.bn1.weight", "RCNN_base.6.8.bn1.bias", "RCNN_base.6.8.bn1.running_mean", "RCNN_base.6.8.bn1.running_var", "RCNN_base.6.8.conv2.weight", "RCNN_base.6.8.bn2.weight", "RCNN_base.6.8.bn2.bias", "RCNN_base.6.8.bn2.running_mean", "RCNN_base.6.8.bn2.running_var", "RCNN_base.6.8.conv3.weight", "RCNN_base.6.8.bn3.weight", "RCNN_base.6.8.bn3.bias", "RCNN_base.6.8.bn3.running_mean", "RCNN_base.6.8.bn3.running_var", "RCNN_base.6.9.conv1.weight", "RCNN_base.6.9.bn1.weight", "RCNN_base.6.9.bn1.bias", "RCNN_base.6.9.bn1.running_mean", "RCNN_base.6.9.bn1.running_var", "RCNN_base.6.9.conv2.weight", "RCNN_base.6.9.bn2.weight", "RCNN_base.6.9.bn2.bias", "RCNN_base.6.9.bn2.running_mean", "RCNN_base.6.9.bn2.running_var", "RCNN_base.6.9.conv3.weight", "RCNN_base.6.9.bn3.weight", "RCNN_base.6.9.bn3.bias", "RCNN_base.6.9.bn3.running_mean", "RCNN_base.6.9.bn3.running_var", "RCNN_base.6.10.conv1.weight", "RCNN_base.6.10.bn1.weight", "RCNN_base.6.10.bn1.bias", "RCNN_base.6.10.bn1.running_mean", "RCNN_base.6.10.bn1.running_var", "RCNN_base.6.10.conv2.weight", "RCNN_base.6.10.bn2.weight", "RCNN_base.6.10.bn2.bias", "RCNN_base.6.10.bn2.running_mean", "RCNN_base.6.10.bn2.running_var", "RCNN_base.6.10.conv3.weight", "RCNN_base.6.10.bn3.weight", "RCNN_base.6.10.bn3.bias", "RCNN_base.6.10.bn3.running_mean", "RCNN_base.6.10.bn3.running_var", "RCNN_base.6.11.conv1.weight", "RCNN_base.6.11.bn1.weight", "RCNN_base.6.11.bn1.bias", "RCNN_base.6.11.bn1.running_mean", "RCNN_base.6.11.bn1.running_var", "RCNN_base.6.11.conv2.weight", "RCNN_base.6.11.bn2.weight", "RCNN_base.6.11.bn2.bias", "RCNN_base.6.11.bn2.running_mean", "RCNN_base.6.11.bn2.running_var", "RCNN_base.6.11.conv3.weight", "RCNN_base.6.11.bn3.weight", "RCNN_base.6.11.bn3.bias", "RCNN_base.6.11.bn3.running_mean", "RCNN_base.6.11.bn3.running_var", "RCNN_base.6.12.conv1.weight", "RCNN_base.6.12.bn1.weight", "RCNN_base.6.12.bn1.bias", "RCNN_base.6.12.bn1.running_mean", "RCNN_base.6.12.bn1.running_var", "RCNN_base.6.12.conv2.weight", "RCNN_base.6.12.bn2.weight", "RCNN_base.6.12.bn2.bias", "RCNN_base.6.12.bn2.running_mean", "RCNN_base.6.12.bn2.running_var", "RCNN_base.6.12.conv3.weight", "RCNN_base.6.12.bn3.weight", "RCNN_base.6.12.bn3.bias", "RCNN_base.6.12.bn3.running_mean", "RCNN_base.6.12.bn3.running_var", "RCNN_base.6.13.conv1.weight", "RCNN_base.6.13.bn1.weight", "RCNN_base.6.13.bn1.bias", "RCNN_base.6.13.bn1.running_mean", "RCNN_base.6.13.bn1.running_var", "RCNN_base.6.13.conv2.weight", "RCNN_base.6.13.bn2.weight", "RCNN_base.6.13.bn2.bias", "RCNN_base.6.13.bn2.running_mean", "RCNN_base.6.13.bn2.running_var", "RCNN_base.6.13.conv3.weight", "RCNN_base.6.13.bn3.weight", "RCNN_base.6.13.bn3.bias", "RCNN_base.6.13.bn3.running_mean", "RCNN_base.6.13.bn3.running_var", "RCNN_base.6.14.conv1.weight", "RCNN_base.6.14.bn1.weight", "RCNN_base.6.14.bn1.bias", "RCNN_base.6.14.bn1.running_mean", "RCNN_base.6.14.bn1.running_var", "RCNN_base.6.14.conv2.weight", "RCNN_base.6.14.bn2.weight", "RCNN_base.6.14.bn2.bias", "RCNN_base.6.14.bn2.running_mean", "RCNN_base.6.14.bn2.running_var", "RCNN_base.6.14.conv3.weight", "RCNN_base.6.14.bn3.weight", "RCNN_base.6.14.bn3.bias", "RCNN_base.6.14.bn3.running_mean", "RCNN_base.6.14.bn3.running_var", "RCNN_base.6.15.conv1.weight", "RCNN_base.6.15.bn1.weight", "RCNN_base.6.15.bn1.bias", "RCNN_base.6.15.bn1.running_mean", "RCNN_base.6.15.bn1.running_var", "RCNN_base.6.15.conv2.weight", "RCNN_base.6.15.bn2.weight", "RCNN_base.6.15.bn2.bias", "RCNN_base.6.15.bn2.running_mean", "RCNN_base.6.15.bn2.running_var", "RCNN_base.6.15.conv3.weight", "RCNN_base.6.15.bn3.weight", "RCNN_base.6.15.bn3.bias", "RCNN_base.6.15.bn3.running_mean", "RCNN_base.6.15.bn3.running_var", "RCNN_base.6.16.conv1.weight", "RCNN_base.6.16.bn1.weight", "RCNN_base.6.16.bn1.bias", "RCNN_base.6.16.bn1.running_mean", "RCNN_base.6.16.bn1.running_var", "RCNN_base.6.16.conv2.weight", "RCNN_base.6.16.bn2.weight", "RCNN_base.6.16.bn2.bias", "RCNN_base.6.16.bn2.running_mean", "RCNN_base.6.16.bn2.running_var", "RCNN_base.6.16.conv3.weight", "RCNN_base.6.16.bn3.weight", "RCNN_base.6.16.bn3.bias", "RCNN_base.6.16.bn3.running_mean", "RCNN_base.6.16.bn3.running_var", "RCNN_base.6.17.conv1.weight", "RCNN_base.6.17.bn1.weight", "RCNN_base.6.17.bn1.bias", "RCNN_base.6.17.bn1.running_mean", "RCNN_base.6.17.bn1.running_var", "RCNN_base.6.17.conv2.weight", "RCNN_base.6.17.bn2.weight", "RCNN_base.6.17.bn2.bias", "RCNN_base.6.17.bn2.running_mean", "RCNN_base.6.17.bn2.running_var", "RCNN_base.6.17.conv3.weight", "RCNN_base.6.17.bn3.weight", "RCNN_base.6.17.bn3.bias", "RCNN_base.6.17.bn3.running_mean", "RCNN_base.6.17.bn3.running_var", "RCNN_base.6.18.conv1.weight", "RCNN_base.6.18.bn1.weight", "RCNN_base.6.18.bn1.bias", "RCNN_base.6.18.bn1.running_mean", "RCNN_base.6.18.bn1.running_var", "RCNN_base.6.18.conv2.weight", "RCNN_base.6.18.bn2.weight", "RCNN_base.6.18.bn2.bias", "RCNN_base.6.18.bn2.running_mean", "RCNN_base.6.18.bn2.running_var", "RCNN_base.6.18.conv3.weight", "RCNN_base.6.18.bn3.weight", "RCNN_base.6.18.bn3.bias", "RCNN_base.6.18.bn3.running_mean", "RCNN_base.6.18.bn3.running_var", "RCNN_base.6.19.conv1.weight", "RCNN_base.6.19.bn1.weight", "RCNN_base.6.19.bn1.bias", "RCNN_base.6.19.bn1.running_mean", "RCNN_base.6.19.bn1.running_var", "RCNN_base.6.19.conv2.weight", "RCNN_base.6.19.bn2.weight", "RCNN_base.6.19.bn2.bias", "RCNN_base.6.19.bn2.running_mean", "RCNN_base.6.19.bn2.running_var", "RCNN_base.6.19.conv3.weight", "RCNN_base.6.19.bn3.weight", "RCNN_base.6.19.bn3.bias", "RCNN_base.6.19.bn3.running_mean", "RCNN_base.6.19.bn3.running_var", "RCNN_base.6.20.conv1.weight", "RCNN_base.6.20.bn1.weight", "RCNN_base.6.20.bn1.bias", "RCNN_base.6.20.bn1.running_mean", "RCNN_base.6.20.bn1.running_var", "RCNN_base.6.20.conv2.weight", "RCNN_base.6.20.bn2.weight", "RCNN_base.6.20.bn2.bias", "RCNN_base.6.20.bn2.running_mean", "RCNN_base.6.20.bn2.running_var", "RCNN_base.6.20.conv3.weight", "RCNN_base.6.20.bn3.weight", "RCNN_base.6.20.bn3.bias", "RCNN_base.6.20.bn3.running_mean", "RCNN_base.6.20.bn3.running_var", "RCNN_base.6.21.conv1.weight", "RCNN_base.6.21.bn1.weight", "RCNN_base.6.21.bn1.bias", "RCNN_base.6.21.bn1.running_mean", "RCNN_base.6.21.bn1.running_var", "RCNN_base.6.21.conv2.weight", "RCNN_base.6.21.bn2.weight", "RCNN_base.6.21.bn2.bias", "RCNN_base.6.21.bn2.running_mean", "RCNN_base.6.21.bn2.running_var", "RCNN_base.6.21.conv3.weight", "RCNN_base.6.21.bn3.weight", "RCNN_base.6.21.bn3.bias", "RCNN_base.6.21.bn3.running_mean", "RCNN_base.6.21.bn3.running_var", "RCNN_base.6.22.conv1.weight", "RCNN_base.6.22.bn1.weight", "RCNN_base.6.22.bn1.bias", "RCNN_base.6.22.bn1.running_mean", "RCNN_base.6.22.bn1.running_var", "RCNN_base.6.22.conv2.weight", "RCNN_base.6.22.bn2.weight", "RCNN_base.6.22.bn2.bias", "RCNN_base.6.22.bn2.running_mean", "RCNN_base.6.22.bn2.running_var", "RCNN_base.6.22.conv3.weight", "RCNN_base.6.22.bn3.weight", "RCNN_base.6.22.bn3.bias", "RCNN_base.6.22.bn3.running_mean", "RCNN_base.6.22.bn3.running_var", "RCNN_top.0.0.conv1.weight", "RCNN_top.0.0.bn1.weight", "RCNN_top.0.0.bn1.bias", "RCNN_top.0.0.bn1.running_mean", "RCNN_top.0.0.bn1.running_var", "RCNN_top.0.0.conv2.weight", "RCNN_top.0.0.bn2.weight", "RCNN_top.0.0.bn2.bias", "RCNN_top.0.0.bn2.running_mean", "RCNN_top.0.0.bn2.running_var", "RCNN_top.0.0.conv3.weight", "RCNN_top.0.0.bn3.weight", "RCNN_top.0.0.bn3.bias", "RCNN_top.0.0.bn3.running_mean", "RCNN_top.0.0.bn3.running_var", "RCNN_top.0.0.downsample.0.weight", "RCNN_top.0.0.downsample.1.weight", "RCNN_top.0.0.downsample.1.bias", "RCNN_top.0.0.downsample.1.running_mean", "RCNN_top.0.0.downsample.1.running_var", "RCNN_top.0.1.conv1.weight", "RCNN_top.0.1.bn1.weight", "RCNN_top.0.1.bn1.bias", "RCNN_top.0.1.bn1.running_mean", "RCNN_top.0.1.bn1.running_var", "RCNN_top.0.1.conv2.weight", "RCNN_top.0.1.bn2.weight", "RCNN_top.0.1.bn2.bias", "RCNN_top.0.1.bn2.running_mean", "RCNN_top.0.1.bn2.running_var", "RCNN_top.0.1.conv3.weight", "RCNN_top.0.1.bn3.weight", "RCNN_top.0.1.bn3.bias", "RCNN_top.0.1.bn3.running_mean", "RCNN_top.0.1.bn3.running_var", "RCNN_top.0.2.conv1.weight", "RCNN_top.0.2.bn1.weight", "RCNN_top.0.2.bn1.bias", "RCNN_top.0.2.bn1.running_mean", "RCNN_top.0.2.bn1.running_var", "RCNN_top.0.2.conv2.weight", "RCNN_top.0.2.bn2.weight", "RCNN_top.0.2.bn2.bias", "RCNN_top.0.2.bn2.running_mean", "RCNN_top.0.2.bn2.running_var", "RCNN_top.0.2.conv3.weight", "RCNN_top.0.2.bn3.weight", "RCNN_top.0.2.bn3.bias", "RCNN_top.0.2.bn3.running_mean", "RCNN_top.0.2.bn3.running_var", "RCNN_cls_score.weight", "RCNN_cls_score.bias", "RCNN_bbox_pred.weight", "RCNN_bbox_pred.bias". 
	While copying the parameter named "RCNN_rpn.RPN_Conv.weight", whose dimensions in the model are torch.Size([512, 512, 3, 3]) and whose dimensions in the checkpoint are torch.Size([512, 1024, 3, 3]).
am I wrong?
