### ISSUE TITLE
KeyError: 'dddddaa'

### ISSUE THREAD

**Issue by Weizhen-Fang** [jwyang/faster-rcnn.pytorch#596]
I am having some troubles train with my data. I am currently using the command:

python trainval_net.py --dataset pascal_voc --net vgg16 --bs 24 --nw 8 --lr 0.001 --lr_decay_step 2000 --cuda --mGPUs

However, I get the following error:
Traceback (most recent call last):
  File "trainval_net.py", line 197, in <module>
    imdb, roidb, ratio_list, ratio_index = combined_roidb(args.imdb_name)
  File "/share/home/weizhenfang/Playground/faster-rcnn.pytorch/lib/roi_data_layer/roidb.py", line 129, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "/share/home/weizhenfang/Playground/faster-rcnn.pytorch/lib/roi_data_layer/roidb.py", line 129, in <listcomp>
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "/share/home/weizhenfang/Playground/faster-rcnn.pytorch/lib/roi_data_layer/roidb.py", line 126, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/share/home/weizhenfang/Playground/faster-rcnn.pytorch/lib/roi_data_layer/roidb.py", line 110, in get_training_r
    imdb.append_flipped_images()
  File "/share/home/weizhenfang/Playground/faster-rcnn.pytorch/lib/datasets/imdb.py", line 118, in append_flipped_images
    boxes = self.roidb[i]['boxes'].copy()
  File "/share/home/weizhenfang/Playground/faster-rcnn.pytorch/lib/datasets/imdb.py", line 76, in roidb
    self._roidb = self.roidb_handler()
  File "/share/home/weizhenfang/Playground/faster-rcnn.pytorch/lib/datasets/pascal_voc.py", line 135, in gt_roidb
    for index in self.image_index]
  File "/share/home/weizhenfang/Playground/faster-rcnn.pytorch/lib/datasets/pascal_voc.py", line 135, in <listcomp>
    for index in self.image_index]
  File "/share/home/weizhenfang/Playground/faster-rcnn.pytorch/lib/datasets/pascal_voc.py", line 246, in _load_pascal_an
    cls = self._class_to_ind[obj.find('name').text.lower().strip()]
KeyError: 'dddddaa'

**Comment by keineahnung2345** [comment]
This means there are some class names(in your case: `'dddddaa'`) in your xml files that are not belong to your pre-defined classes(`self._class_to_ind`). So you need to clean the xml files or extend your pre-defined classes.
