### ISSUE TITLE
RuntimeError: reduce failed to synchronize: device-side assert triggered 

### ISSUE THREAD

**Issue by benedictflorance** [jwyang/faster-rcnn.pytorch#610]
I am running a variation of jwyang's Faster RCNN code. (https://github.com/tiancity-NJU/da-faster-rcnn-PyTorch/issues/17)

I am trying to perform the training from WIDERFACE dataset to FDDB dataset.

The following error occurs:
```
Traceback (most recent call last):
  File "da_trainval_net.py", line 433, in <module>
    tgt_im_data, tgt_im_info, tgt_gt_boxes, tgt_num_boxes, tgt_need_backprop)
  File "/export/livia/home/vision/bflorance/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/export/livia/home/vision/bflorance/da-faster-rcnn-PyTorch-wider/lib/model/da_faster_rcnn/faster_rcnn.py", line 190, in forward
    DA_ins_loss_cls = instance_loss(instance_sigmoid, same_size_label)
  File "/export/livia/home/vision/bflorance/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/export/livia/home/vision/bflorance/anaconda3/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 433, in forward
    reduce=self.reduce)
  File "/export/livia/home/vision/bflorance/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1483, in binary_cross_entropy
    return torch._C._nn.binary_cross_entropy(input, target, weight, size_average, reduce)
RuntimeError: reduce failed to synchronize: device-side assert triggered
```

Upon debugging, I found that the input tensor for BCE loss should contain values that are between 0 and 1. 

Further debugging showed that the reason for the issue is because `base_feat` variable in https://github.com/jwyang/faster-rcnn.pytorch/blob/master/lib/model/faster_rcnn/faster_rcnn.py#L47 is a tensor with all the values as zero.

Any idea on why this might have happened and where it might have gone wrong?

**Comment by benedictflorance** [comment]
The issue was due to some bounding box annotations with very small width and height.

This resolved it.

`not_keep = (gt_boxes[:,2] - gt_boxes[:,0]) < 10 & (gt_boxes[:,3] - gt_boxes[:,1]) < 10`
