### ISSUE TITLE
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

### ISSUE THREAD

**Issue by zhengxinvip** [jwyang/faster-rcnn.pytorch#615]
I have trained the model  when I run test_net.py I got this error:
Traceback (most recent call last):
  File "test_net.py", line 140, in <module>
    imdb, roidb, ratio_list, ratio_index = combined_roidb(args.imdbval_name, False)
  File "/home/wuwenfu/faster-rcnn.pytorch-master/lib/roi_data_layer/roidb.py", line 129, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "/home/wuwenfu/faster-rcnn.pytorch-master/lib/roi_data_layer/roidb.py", line 129, in <listcomp>
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "/home/wuwenfu/faster-rcnn.pytorch-master/lib/roi_data_layer/roidb.py", line 126, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/home/wuwenfu/faster-rcnn.pytorch-master/lib/roi_data_layer/roidb.py", line 115, in get_training_roidb
    prepare_roidb(imdb)
  File "/home/wuwenfu/faster-rcnn.pytorch-master/lib/roi_data_layer/roidb.py", line 24, in prepare_roidb
    roidb = imdb.roidb
  File "/home/wuwenfu/faster-rcnn.pytorch-master/lib/datasets/imdb.py", line 76, in roidb
    self._roidb = self.roidb_handler()
  File "/home/wuwenfu/faster-rcnn.pytorch-master/lib/datasets/pascal_voc.py", line 132, in gt_roidb
    for index in self.image_index]
  File "/home/wuwenfu/faster-rcnn.pytorch-master/lib/datasets/pascal_voc.py", line 132, in <listcomp>
    for index in self.image_index]
  File "/home/wuwenfu/faster-rcnn.pytorch-master/lib/datasets/pascal_voc.py", line 211, in _load_pascal_annotation
    tree = ET.parse(filename)
  File "/home/wuwenfu/.conda/envs/pytorch04/lib/python3.5/xml/etree/ElementTree.py", line 1195, in parse
    tree.parse(source, parser)
  File "/home/wuwenfu/.conda/envs/pytorch04/lib/python3.5/xml/etree/ElementTree.py", line 596, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
but I do not change anything about the xml file? what should I do next?

**Comment by devendraswamy** [comment]
I am getting same error , did you solve that error ??

please help
