### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (94,36,4) (1,1,3) (94,36,4) 

### ISSUE THREAD

**Issue by zhengxinvip** [jwyang/faster-rcnn.pytorch#616]
Traceback (most recent call last):
  File "trainval_net.py", line 310, in <module>
    data = next(data_iter)
  File "/home/wuwenfu/.conda/envs/pytorch04/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/home/wuwenfu/.conda/envs/pytorch04/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/home/wuwenfu/.conda/envs/pytorch04/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/wuwenfu/.conda/envs/pytorch04/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/wuwenfu/faster-rcnn.pytorch-master/lib/roi_data_layer/roibatchLoader.py", line 67, in __getitem__
    blobs = get_minibatch(minibatch_db, self._num_classes)
  File "/home/wuwenfu/faster-rcnn.pytorch-master/lib/roi_data_layer/minibatch.py", line 30, in get_minibatch
    im_blob, im_scales = _get_image_blob(roidb, random_scale_inds)
  File "/home/wuwenfu/faster-rcnn.pytorch-master/lib/roi_data_layer/minibatch.py", line 79, in _get_image_blob
    cfg.TRAIN.MAX_SIZE)
  File "/home/wuwenfu/faster-rcnn.pytorch-master/lib/model/utils/blob.py", line 39, in prep_im_for_blob
    im -= pixel_means
ValueError: operands could not be broadcast together with shapes (94,36,4) (1,1,3) (94,36,4)

**Comment by zhengxinvip** [comment]
When I train my own data , I get this error, How can I fix it? thanks.

**Comment by CaptainJohansson** [comment]
how you solve this problem? 
i get the same issue when i train own data about two catagories
