### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by zhengxinvip** [jwyang/faster-rcnn.pytorch#619]
when I train my own data, after 20 epoch I get this error: 
[session 1][epoch 20][iter 1200/1285] loss: 0.0775, lr: 1.00e-06
			fg/bg=(74/438), time cost: 100.774568
			rpn_cls: 0.0010, rpn_box: 0.0255, rcnn_cls: 0.0304, rcnn_box 0.0400
save model: models/res101/pascal_voc/faster_rcnn_1_20_1284.pth
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fc107781748>>
Traceback (most recent call last):
  File "/home/wuwenfu/.conda/envs/pytorch04/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 349, in __del__
  File "/home/wuwenfu/.conda/envs/pytorch04/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 328, in _shutdown_workers
  File "/home/wuwenfu/.conda/envs/pytorch04/lib/python3.5/multiprocessing/queues.py", line 337, in get
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 887, in _find_spec
TypeError: 'NoneType' object is not iterable

what should I do, anyone can help me? thanks

**Comment by casiahnu** [comment]
the same problem
