### ISSUE TITLE
python3.7,cuda10,pytorch1.1

### ISSUE THREAD

**Issue by MaLiXiaoGuo** [jwyang/faster-rcnn.pytorch#620]
Traceback (most recent call last):
  File "F:/faster-rcnn.pytorch-master/demo.py", line 27, in <module>
    from roi_data_layer.roidb import combined_roidb
  File "F:\faster-rcnn.pytorch-master\lib\roi_data_layer\roidb.py", line 12, in <module>
    from datasets.factory import get_imdb
  File "F:\faster-rcnn.pytorch-master\lib\datasets\factory.py", line 14, in <module>
    from datasets.pascal_voc import pascal_voc
  File "F:\faster-rcnn.pytorch-master\lib\datasets\pascal_voc.py", line 23, in <module>
    from .imdb import imdb
  File "F:\faster-rcnn.pytorch-master\lib\datasets\imdb.py", line 14, in <module>
    from model.utils.cython_bbox import bbox_overlaps
ModuleNotFoundError: No module named 'model.utils.cython_bbox'

**Comment by EMCP** [comment]
this is patched by replacing the pycocotools with the latest from github 

example at 

https://github.com/jwyang/faster-rcnn.pytorch/pull/466

**Comment by EMCP** [comment]
my tutorial to get this working is at https://mahr.io/tutorials/faster-r-cnn-pytorch-how-to

**Comment by harishkashyap** [comment]
The tutorial isn't working anymore. How I so wish, people building their modules on pytorch also update their libraries to work with latest versions in general.

**Comment by EMCP** [comment]
@harishkashyap this entire project which the tutorial was based on became out of date.  Little reason to attempt to update what requires proper refactoring by the original author who clearly hasn't touched this repo in a while.  I've personally moved into torchvision and pytorch 1.9 in order to attempt to do object detection on custom data

https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html

My full time job has not allowed me time to work beyond the basics

**Comment by harishkashyap** [comment]
Appreciate yoir quick response on this. I certainly understand given the way pytorch keeps updating with breaking changes. Tensorflow is worse. This repo would be incredibly useful if it works out of the box. Great work indeed!

**Comment by EMCP** [comment]
I definitely want to come back to redo this with coco based datasets.. this space is VERY hot obviously but the community is rough.. I even have been playing with the idea of going julialang instead... Because pytorchs own tutorials only show datasets handpicked.. as opposed to letting you pour in your own datasets and start labeling.. honestly I think there's a huge consulting money grab going on and it leaves smaller teams left to fix this stuff ourselves in the discourse and issues.. I hope you get further with torchvision.. it is quite worth looking at it once you've seen how hand codified and non production ready this repo is

**Comment by EMCP** [comment]
@harishkashyap do you have an email.. I have recently come back to this code and started fixing it.. but I don't want to say it's "ready"..

as of now I am training successfully on an RTX 3090 with Pytorch 1.11 Nightly build Cuda 11.3

if you are interested please message me your details and I can hear what your compute situation is and attempt to start a new tutorial .. I am quite impressed I got this POS code base even training again.. but I hesitate to say it's "ready"..
