### ISSUE TITLE
IndexKernel.cu:53: Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.

### ISSUE THREAD

**Issue by MatthewInkawhich** [jwyang/faster-rcnn.pytorch#622]
When running on my own dataset...
- 600x600px
- up to hundreds of annotations per image

I am trying to train my models on 4 GPUs with `nn.DataParallel` using the ResNet-101 backbone.

The error that I am getting is as follows:

```
...
...
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda [](int)->auto::operator()(int)->auto: block: [349549,0,0], thread: [92,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda [](int)->auto::operator()(int)->auto: block: [349549,0,0], thread: [93,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda [](int)->auto::operator()(int)->auto: block: [349549,0,0], thread: [94,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda [](int)->auto::operator()(int)->auto: block: [349549,0,0], thread: [95,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "trainval_net.py", line 344, in <module>
    rois_label = fasterRCNN(im_data, im_info, gt_boxes, num_boxes)
  File "/p36/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/p36/lib64/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/p36/lib64/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/p36/lib64/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/p36/lib64/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/p36/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/faster-rcnn.pytorch/lib/model/faster_rcnn/faster_rcnn.py", line 77, in forward
    rois, rpn_scores, rpn_loss_cls, rpn_loss_bbox = self.RCNN_rpn(base_feat, im_info, gt_boxes, num_boxes)
  File "/p36/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/faster-rcnn.pytorch/lib/model/rpn/rpn.py", line 103, in forward
    rpn_data = self.RPN_anchor_target((rpn_cls_score.data, gt_boxes, im_info, num_boxes))
  File "/p36/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/faster-rcnn.pytorch/lib/model/rpn/anchor_target_layer.py", line 106, in forward
    overlaps = bbox_overlaps_batch(anchors, gt_boxes)
  File "/faster-rcnn.pytorch/lib/model/rpn/bbox_transform.py", line 207, in bbox_overlaps_batch
    ih[ih < 0] = 0
RuntimeError: copy_if failed to synchronize: device-side assert triggered
```

Note that the code runs fine and the model trains if I decrease the batch size significantly. 

Also, I have observed that as I increase the feature map resolution of the `fasterRCNN.RCNN_base` output (thus decreasing anchor stride), I have to decrease the batch size even more to avoid this error.

Note that the GPU memory utilization is NOT at its maximum when this error occurs.

Anyone have any ideas?

Thanks,
Matt

**Comment by xsacha** [comment]
I am getting this now on PyTorch 1.6.0-rc2
Edit: I think it is an issue caused elsewhere but manifests at this location. The error is just that the tensor index is actually out of bounds of the tensor being indexed.
