### ISSUE TITLE
cffi.VerificationError: CompileError: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by WZHsmile** [jwyang/faster-rcnn.pytorch#641]
anaconda3/envs/py27t04/include/python2.7 -c _roi_crop.c -o ./_roi_crop.o
In file included from /home/wangzhonghao/anaconda3/envs/py27t04/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC/THC.h:4:0,
                 from _roi_crop.c:493:
/home/wangzhonghao/anaconda3/envs/py27t04/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:12:18: fatal error: cuda.h: 没有那个文件或目录
compilation terminated.
Traceback (most recent call last):
  File "build.py", line 36, in <module>
    ffi.build()
  File "/home/wangzhonghao/anaconda3/envs/py27t04/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 184, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/wangzhonghao/anaconda3/envs/py27t04/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 108, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/wangzhonghao/anaconda3/envs/py27t04/lib/python2.7/site-packages/cffi/api.py", line 723, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/wangzhonghao/anaconda3/envs/py27t04/lib/python2.7/site-packages/cffi/recompiler.py", line 1526, in recompile
    compiler_verbose, debug)
  File "/home/wangzhonghao/anaconda3/envs/py27t04/lib/python2.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/wangzhonghao/anaconda3/envs/py27t04/lib/python2.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: CompileError: command 'gcc' failed with exit status 1

**Comment by WZHsmile** [comment]
By modifying the header file of make.sh, add the following in front of the file.

**export PATH=/usr/local/cuda-8.0/bin${PATH:+:${PATH}}
export CPATH=/usr/local/cuda-8.0/include${CPATH:+:${CPATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}**
