### ISSUE TITLE
resume erro:an illegal memory access was encountered

### ISSUE THREAD

**Issue by lhiceu** [jwyang/faster-rcnn.pytorch#645]
`CUDA_VISIBLE_DEVICES=0 CUDA_LAUNCH_BLOCKING=1 python trainval_net.py --dataset pascal_voc --net res101 --bs 4 --epochs 45 --cuda --r true --checkepoch 40 --checkpoint 810
`
`Called with args:
Namespace(batch_size=4, checkepoch=40, checkpoint=810, checkpoint_interval=10000, checksession=1, class_agnostic=False, cuda=True, dataset='pascal_voc', disp_interval=100, large_scale=False, lr=0.001, lr_decay_gamma=0.1, lr_decay_step=5, mGPUs=False, max_epochs=45, net='res101', num_workers=0, optimizer='sgd', resume=True, save_dir='models', session=1, start_epoch=1, use_tfboard=False)
/media/he/Disk/faster-rcnn.pytorch-master/lib/model/utils/config.py:374: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yaml_cfg = edict(yaml.load(f))
Using config:
{'ANCHOR_RATIOS': [0.5, 1, 2],
 'ANCHOR_SCALES': [8, 16, 32],
 'CROP_RESIZE_WITH_MAX_POOL': False,
 'CUDA': False,
 'DATA_DIR': '/media/he/Disk/faster-rcnn.pytorch-master/data',
 'DEDUP_BOXES': 0.0625,
 'EPS': 1e-14,
 'EXP_DIR': 'res101',
 'FEAT_STRIDE': [16],
 'GPU_ID': 0,
 'MATLAB': 'matlab',
 'MAX_NUM_GT_BOXES': 20,
 'MOBILENET': {'DEPTH_MULTIPLIER': 1.0,
               'FIXED_LAYERS': 5,
               'REGU_DEPTH': False,
               'WEIGHT_DECAY': 4e-05},
 'PIXEL_MEANS': array([[[102.9801, 115.9465, 122.7717]]]),
 'POOLING_MODE': 'align',
 'POOLING_SIZE': 7,
 'RESNET': {'FIXED_BLOCKS': 1, 'MAX_POOL': False},
 'RNG_SEED': 3,
 'ROOT_DIR': '/media/he/Disk/faster-rcnn.pytorch-master',
 'TEST': {'BBOX_REG': True,
          'HAS_RPN': True,
          'MAX_SIZE': 1000,
          'MODE': 'nms',
          'NMS': 0.3,
          'PROPOSAL_METHOD': 'gt',
          'RPN_MIN_SIZE': 16,
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 300,
          'RPN_PRE_NMS_TOP_N': 6000,
          'RPN_TOP_N': 5000,
          'SCALES': [600],
          'SVM': False},
 'TRAIN': {'ASPECT_GROUPING': False,
           'BATCH_SIZE': 128,
           'BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'BBOX_NORMALIZE_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZE_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_NORMALIZE_TARGETS': True,
           'BBOX_NORMALIZE_TARGETS_PRECOMPUTED': True,
           'BBOX_REG': True,
           'BBOX_THRESH': 0.5,
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.0,
           'BIAS_DECAY': False,
           'BN_TRAIN': False,
           'DISPLAY': 20,
           'DOUBLE_BIAS': False,
           'FG_FRACTION': 0.25,
           'FG_THRESH': 0.5,
           'GAMMA': 0.1,
           'HAS_RPN': True,
           'IMS_PER_BATCH': 1,
           'LEARNING_RATE': 0.001,
           'MAX_SIZE': 1000,
           'MOMENTUM': 0.9,
           'PROPOSAL_METHOD': 'gt',
           'RPN_BATCHSIZE': 256,
           'RPN_BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_MIN_SIZE': 8,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 2000,
           'RPN_PRE_NMS_TOP_N': 12000,
           'SCALES': [600],
           'SNAPSHOT_ITERS': 5000,
           'SNAPSHOT_KEPT': 3,
           'SNAPSHOT_PREFIX': 'res101_faster_rcnn',
           'STEPSIZE': [30000],
           'SUMMARY_INTERVAL': 180,
           'TRIM_HEIGHT': 600,
           'TRIM_WIDTH': 600,
           'TRUNCATED': False,
           'USE_ALL_GT': True,
           'USE_FLIPPED': True,
           'USE_GT': False,
           'WEIGHT_DECAY': 0.0001},
 'USE_GPU_NMS': True}
Loaded dataset `voc_2007_trainval`
Set proposal method: gt
Preparing training data...
voc_2007_trainval gt roidb loaded from /media/he/Disk/faster-rcnn.pytorch-master/data/cache/voc_2007_trainval_gt_roidb.pkl
Image sizes loaded from /media/he/Disk/faster-rcnn.pytorch-master/data/cache/voc_2007_trainval_sizes.pkl
done
before filtering, there are 3245 images...
after filtering, there are 3245 images...
3245 roidb entries
21
Loading pretrained weights from data/pretrained_model/resnet101_caffe.pth
trainval_net.py:258: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  torch.nn.init.constant(uncert, -1.0)
loading checkpoint models/res101/pascal_voc/faster_rcnn_1_40_810.pth
loaded checkpoint models/res101/pascal_voc/faster_rcnn_1_40_810.pth
uncert: -4.9072, -4.8135, -3.5146, -3.3415
[session 1][epoch 41][iter    0/ 811] loss: -14.9492, lr: 1.00e-09
			fg/bg=(90/422), time cost: 1.062218
			rpn_cls: 0.0048, rpn_box: 0.0009, rcnn_cls: 0.0156, rcnn_box 0.0118
uncert: -4.9072, -4.8135, -3.5146, -3.3415
out of memory
an illegal memory access was encountered
CUDA Error: an illegal memory access was encountered, at line 147
CUDA Error: an illegal memory access was encountered, at line 154
an illegal memory access was encountered
an illegal memory access was encountered
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524577177097/work/aten/src/THC/generic/THCStorage.c line=36 error=77 : an illegal memory access was encountered
Traceback (most recent call last):
  File "trainval_net.py", line 328, in <module>
    rois_label = fasterRCNN(im_data, im_info, gt_boxes, num_boxes)
  File "/home/he/software/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/he/Disk/faster-rcnn.pytorch-master/lib/model/faster_rcnn/faster_rcnn.py", line 50, in forward
    rois, rpn_loss_cls, rpn_loss_bbox = self.RCNN_rpn(base_feat, im_info, gt_boxes, num_boxes)
  File "/home/he/software/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/he/Disk/faster-rcnn.pytorch-master/lib/model/rpn/rpn.py", line 78, in forward
    im_info, cfg_key))
  File "/home/he/software/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/he/Disk/faster-rcnn.pytorch-master/lib/model/rpn/proposal_layer.py", line 148, in forward
    keep_idx_i = nms(torch.cat((proposals_single, scores_single), 1), nms_thresh, force_cpu=not cfg.USE_GPU_NMS)
  File "/media/he/Disk/faster-rcnn.pytorch-master/lib/model/nms/nms_wrapper.py", line 21, in nms
    return nms_gpu(dets, thresh) if force_cpu == False else nms_cpu(dets, thresh)
  File "/media/he/Disk/faster-rcnn.pytorch-master/lib/model/nms/nms_gpu.py", line 11, in nms_gpu
    keep = keep[:num_out[0]]
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /opt/conda/conda-bld/pytorch_1524577177097/work/aten/src/THC/generic/THCStorage.c:36
`

**Comment by 893374759** [comment]
Same problem...... 
Do you solve this? 
@lhiceu
