### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '000001.xml'

### ISSUE THREAD

**Issue by Zx117x** [jwyang/faster-rcnn.pytorch#654]
When I run test_net.py in win10, the error happened.   
 Writing train VOC results file
Writing tvmonitor VOC results file
VOC07 metric? Yes
Traceback (most recent call last):
 File "test_net.py", line 325, in <module>
imdb.evaluate_detections(all_boxes, output_dir)
  File "D:\faster-rcnn.pytorch-pytorch-1.0\lib\datasets\pascal_voc.py", line 352, in evaluate_detections
    self._do_python_eval(output_dir)
  File "D:\faster-rcnn.pytorch-pytorch-1.0\lib\datasets\pascal_voc.py", line 315, in _do_python_eval
    use_07_metric=use_07_metric)
  File "D:\faster-rcnn.pytorch-pytorch-1.0\lib\datasets\voc_eval.py", line 114, in voc_eval
    recs[imagename] = parse_rec(annopath.format(imagename))
  File "D:\faster-rcnn.pytorch-pytorch-1.0\lib\datasets\voc_eval.py", line 17, in parse_rec
    tree = ET.parse(filename)
  File "D:\Anaconda3\lib\xml\etree\ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "D:\Anaconda3\lib\xml\etree\ElementTree.py", line 586, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '000001.xml'

**Comment by WenTaoLiu502** [comment]
Hello！I also have the same question.Could you please tell me how to solve it?

**Comment by loolzaaa** [comment]
Too old issue, but may this can help.

Your pascal_voc code:
```python
def _do_python_eval(self, output_dir='output'):
        annopath = os.path.join(
            self._devkit_path,
            'VOC' + self._year,
            'Annotations',
            '{:s}.xml')
...
```
Change to:
```python
def _do_python_eval(self, output_dir='output'):
        annopath = os.path.join(
            self._devkit_path,
            'VOC' + self._year,
            'Annotations',
            '{}.xml')
...
```
Short version: {:s}.xml > {}.xml

**Comment by WenTaoLiu502** [comment]
> Too old issue, but may this can help.
> Your pascal_voc code:
> def _do_python_eval(self, output_dir='output'):
>         annopath = os.path.join(
>             self._devkit_path,
>             'VOC' + self._year,
>             'Annotations',
>             '{:s}.xml')
> ...
> Change to:
> def _do_python_eval(self, output_dir='output'):
>         annopath = os.path.join(
>             self._devkit_path,
>             'VOC' + self._year,
>             'Annotations',
>             '{}.xml')
> ...
> Short version: {:s}.xml > {}.xml

Thanks for your help.The problem has been solved.

**Comment by DoubiQ** [comment]
感谢，困扰了一下午，终于解决了
