### ISSUE TITLE
pooled_feat = self._head_to_tail(pooled_feat1)

### ISSUE THREAD

**Issue by Y132om** [jwyang/faster-rcnn.pytorch#657]
Loading pretrained weights from data/pretrained_model/vgg16_caffe.pth

Traceback (most recent call last):
  File "F:/faster-rcnn.pytorch-pytorch-1.0/trainval_net.py", line 321, in <module>
    rois_label = fasterRCNN(im_data, im_info, gt_boxes, num_boxes)
  File "E:\anaconda\anacoda\envs\py36\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "F:\faster-rcnn.pytorch-pytorch-1.0\lib\model\faster_rcnn\faster_rcnn.py", line 82, in forward
    pooled_feat = self._head_to_tail(pooled_feat1)
UnboundLocalError: local variable 'pooled_feat1' referenced before assignment

How should I solve this problem?

**Comment by RebornL** [comment]
Have you fix this problem? I also meet this problem when I want to train the resnet50. I find this project set the resnet101 as default.

**Comment by RebornL** [comment]
I find the reason: because the POOLING_MODE equal "crop", there is no if-else statement for "crop"

**Comment by zychen2016** [comment]
> I find the reason: because the POOLING_MODE equal "crop", there is no if-else statement for "crop"

I also meet this problem when set POOLING_MODE=pooling

**Comment by adhilshereef** [comment]
Iam also facing this problem..help me out

**Comment by SHAOSIHAN** [comment]
> Have you fix this problem? I also meet this problem when I want to train the resnet50. I find this project set the resnet101 as default.

I meet the same problem when I use resnet50 as backbone, you can find res50.yml, set POOLING_MODE=align that is the same as res101.yml.
