### ISSUE TITLE
Missing key(s) in state_dict

### ISSUE THREAD

**Issue by NicholasIrving** [jwyang/faster-rcnn.pytorch#676]
Traceback (most recent call last):
  File "trainval_net.py", line 249, in <module>
    fasterRCNN.create_architecture()
  File "/home/fitlab/NiCk/faster-rcnn.pytorch/lib/model/faster_rcnn/faster_rcnn.py", line 135, in create_architecture
    self._init_modules()
  File "/home/fitlab/NiCk/faster-rcnn.pytorch/lib/model/faster_rcnn/vgg16.py", line 33, in _init_modules
    vgg.load_state_dict({k:v for k,v in state_dict.items() if k in vgg.state_dict()})
  File "/home/fitlab/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for VGG:
 Missing key(s) in state_dict: "classifier.1.weight", "classifier.1.bias", "classifier.4.weight", "classifier.4.bias".

How to solve ?

**Comment by simobupt** [comment]
sometimes with vgg16,this problem will raise, however when you use res101, this problem will disapper.

**Comment by Saharkakavand** [comment]
@NicholasIrving  did you solve this problem?

**Comment by Saharkakavand** [comment]
@NicholasIrving  did you solve this problem?

**Comment by Saharkakavand** [comment]
use vgg.load_state_dict(torch.load(self.model_path),strict=False) and remove line 32 and 33 of vgg16.py. this worked for me

**Comment by NicholasIrving** [comment]
@Saharkakavand use pytorch1.0 bench is OK
