### ISSUE TITLE
ImportError: model/utils/cython_bbox.so: invalid ELF header

### ISSUE THREAD

**Issue by yonglizhong** [jwyang/faster-rcnn.pytorch#677]
I have compiled the code & looks like it went smoothly without errors & only warning signs of unused variables. However, when I tried to run the demo.py, I've been given an Import error message of invalid ELF header from model/utils/cython_bbox.so.

**Comment by yonglizhong** [comment]
(pytorch-lighthead_env) yonglizhong@atma-grasping-WM:~/pytorch-lighthead$ python demo.py --net vgg16 --checksession $SESSION \
> --checkepoch $EPOCH --checkpoint $CHECKPOINT \
> --cuda --lighthead --load_dir /home/yonglizhong/pytorch-lighthead/data/pretrained_model
Traceback (most recent call last):
  File "demo.py", line 27, in <module>
    from roi_data_layer.roidb import combined_roidb
  File "/home/yonglizhong/pytorch-lighthead/lib/roi_data_layer/roidb.py", line 9, in <module>
    from datasets.factory import get_imdb
  File "/home/yonglizhong/pytorch-lighthead/lib/datasets/factory.py", line 14, in <module>
    from datasets.pascal_voc import pascal_voc
  File "/home/yonglizhong/pytorch-lighthead/lib/datasets/pascal_voc.py", line 23, in <module>
    from .imdb import imdb
  File "/home/yonglizhong/pytorch-lighthead/lib/datasets/imdb.py", line 14, in <module>
    from model.utils.cython_bbox import bbox_overlaps
ImportError: /home/yonglizhong/pytorch-lighthead/lib/model/utils/cython_bbox.so: invalid ELF header

**Comment by yonglizhong** [comment]
(pytorch-lighthead_env) yonglizhong@atma-grasping-WM:~/pytorch-lighthead$ python demo.py --net vgg16 --checksession $SESSION \
> --checkepoch $EPOCH --checkpoint $CHECKPOINT \
> --cuda --lighthead --load_dir /home/yonglizhong/pytorch-lighthead/data/pretrained_model
Traceback (most recent call last):
  File "demo.py", line 27, in <module>
    from roi_data_layer.roidb import combined_roidb
  File "/home/yonglizhong/pytorch-lighthead/lib/roi_data_layer/roidb.py", line 9, in <module>
    from datasets.factory import get_imdb
  File "/home/yonglizhong/pytorch-lighthead/lib/datasets/factory.py", line 14, in <module>
    from datasets.pascal_voc import pascal_voc
  File "/home/yonglizhong/pytorch-lighthead/lib/datasets/pascal_voc.py", line 23, in <module>
    from .imdb import imdb
  File "/home/yonglizhong/pytorch-lighthead/lib/datasets/imdb.py", line 14, in <module>
    from model.utils.cython_bbox import bbox_overlaps
ImportError: /home/yonglizhong/pytorch-lighthead/lib/model/utils/cython_bbox.so: invalid ELF header

**Comment by yonglizhong** [comment]
Here is my python environment in anaconda. I'm currently using python 2.7, CUDA 9.0 on a Geforce GTX 1050 GPU.
absl-py==0.8.1
actionlib==1.11.13
angles==1.9.11
astor==0.8.0
backports.functools-lru-cache==1.5
backports.shutil-get-terminal-size==1.0.0
backports.weakref==1.0.post1
bleach==1.5.0
camera-calibration-parsers==1.11.13
catkin==0.7.18
certifi==2019.9.11
cffi==1.13.0
cloudpickle==1.2.2
controller-manager==0.13.3
controller-manager-msgs==0.13.3
controller-manager-tests==0.13.3
cv-bridge==1.12.8
cycler==0.10.0
Cython==0.29.13
cython-bbox==0.1.3
decorator==4.4.0
diagnostic-updater==1.9.3
dynamic-reconfigure==1.5.50
easydict==1.9
enum34==1.1.6
funcsigs==1.0.2
functools32==3.2.3.post2
future==0.18.0
futures==3.3.0
gast==0.2.2
gencpp==0.6.0
geneus==2.2.6
genlisp==0.4.16
genmsg==0.5.11
gennodejs==2.0.1
genpy==0.6.7
google-pasta==0.1.7
grpcio==1.24.1
h5py==2.10.0
html5lib==0.9999999
image-geometry==1.12.8
interactive-markers==1.11.4
ipython==5.8.0
ipython-genutils==0.2.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.1.0
laser-geometry==1.6.4
Markdown==3.1.1
matplotlib==2.2.4
message-filters==1.12.14
mock==3.0.5
moveit-ros-planning-interface==0.9.17
moveit-ros-visualization==0.9.17
networkx==2.2
numpy==1.16.5
opencv-contrib-python==4.1.1.26
opencv-python==4.1.1.26
opt-einsum==2.3.2
pathlib2==2.3.5
pexpect==4.7.0
pickleshare==0.7.5
Pillow==6.2.0
pluginlib==1.11.3
prompt-toolkit==1.0.16
protobuf==3.10.0
ptyprocess==0.6.0
pycparser==2.19
Pygments==2.4.2
pyparsing==2.4.2
python-dateutil==2.8.0
python-qt-binding==0.3.4
pytz==2019.3
PyWavelets==1.0.3
PyYAML==5.1.2
qt-gui==0.3.11
resource-retriever==1.12.5
ros-pytest==0.1.2
rosbag==1.12.14
rosclean==1.14.6
rosgraph==1.12.14
roslaunch==1.12.14
roslib==1.14.6
roslz4==1.12.14
rosmaster==1.12.14
rosmsg==1.12.14
rosnode==1.12.14
rosparam==1.12.14
rospy==1.12.14
rosserial-client==0.7.7
rosserial-python==0.7.7
rosservice==1.12.14
rostest==1.12.14
rostopic==1.12.14
rosunit==1.14.6
roswtf==1.12.14
rqt-gui==0.5.0
rqt-gui-py==0.5.0
rqt-joint-trajectory-controller==0.13.5
rviz==1.12.17
scandir==1.10.0
scikit-image==0.14.5
scipy==1.2.2
sensor-msgs==1.12.7
simplegeneric==0.8.1
six==1.12.0
smclib==1.8.3
srdfdom==0.4.2
style==1.1.0
subprocess32==3.5.4
tensorboard==1.13.1
tensorflow==1.5.0
tensorflow-estimator==1.13.0
tensorflow-gpu==1.13.1
tensorflow-tensorboard==1.5.1
termcolor==1.1.0
tf==1.11.9
tf-conversions==1.11.9
tf2-kdl==0.5.20
tf2-py==0.5.20
tf2-ros==0.5.20
topic-tools==1.12.14
torch==0.4.0
torchvision==0.2.1
traitlets==4.3.2
update==0.0.1
urdfdom-py==0.3.3
wcwidth==0.1.7
Werkzeug==0.16.0
wrapt==1.11.2
xacro==1.11.3

**Comment by yonglizhong** [comment]
I've also made sure that my arch in make.sh is changed according to my GPU and have set the CUDA path to the proper one to 9.0.

Hope someone can help me regarding this. Been stuck on it for the past 2 days. Thanks so much

**Comment by sarsigmadelta** [comment]
以后不要给我发了，烦死了





At 2019-10-18 14:15:18, "yonglizhong" <notifications@github.com> wrote:


I have compiled the code & looks like it went smoothly without errors & only warning signs of unused variables. However, when I tried to run the demo.py, I've been given an Import error message of invalid ELF header from model/utils/cython_bbox.so.
