### ISSUE TITLE
assert(self.feature_size is not None and grad_output.is_cuda) AssertionError

### ISSUE THREAD

**Issue by write-rookie** [jwyang/faster-rcnn.pytorch#687]
Encounter this kind of circumstance to do not know how to solve suddenly, hope you have time to be able to help solve
"""
Traceback (most recent call last):
  File "/home/zpf/taget_detection/faster-rcnn.pytorch/trainval_net_test_input.py", line 337, in <module>
    loss.backward()
  File "/home/miccai/software/anaconda3/envs/zpfpython/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/miccai/software/anaconda3/envs/zpfpython/lib/python3.6/site-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/zpf/taget_detection/faster-rcnn.pytorch/lib/model/roi_align/functions/roi_align.py", line 38, in backward
    assert(self.feature_size is not None and grad_output.is_cuda)
AssertionError
"""

**Comment by zzfpython** [comment]
Have you solved this problem now？

**Comment by write-rookie** [comment]
sorry, I just saw the news recently, I remember I had to change the thread to one

dataloader = torch.utils.data.DataLoader(dataset, batch_size=1,
                            shuffle=False, num_workers=0,
                            pin_memory=True)

**Comment by jingwenh** [comment]
Same problem here. Could you be more specific about the solution?

**Comment by write-rookie** [comment]
thanks very much， i have deal with this problem。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jingwenh"<notifications@github.com&gt;; 
发送时间: 2020年2月23日(星期天) 下午2:08
收件人: "jwyang/faster-rcnn.pytorch"<faster-rcnn.pytorch@noreply.github.com&gt;; 
抄送: "827691435"<827691435@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [jwyang/faster-rcnn.pytorch] assert(self.feature_size is not None and grad_output.is_cuda) AssertionError (#687)




Same problem here. Could you be more specific about the solution?
