### ISSUE TITLE
RuntimeError: Python version >= 3.5 required.

### ISSUE THREAD

**Issue by ZiyuBao** [jwyang/faster-rcnn.pytorch#693]
python version: 2.7.5
pip version: 8.1.2 from /usr/lib/python2.7/site-packages (python 2.7)
cuda version: 9.0
torch version: 0.4.0

When I am running "pip install -r requirements.txt", an error message prompts:

```
> Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-xG7nHh/numpy/setup.py", line 31, in <module>
>         raise RuntimeError("Python version >= 3.5 required.")
>     RuntimeError: Python version >= 3.5 required.
```

Please, anyone can help? Do I need to change to pip3 to install it? Or, change the code of that line in setup.py to from "python" to "python3"? But I installed torch in python2, so it's best if someone can tell me what to fix using python2 directly?

**Comment by ZiyuBao** [comment]
I notice that this happens in trying to install "opencv-python", line 3 of requirements.txt. Installing opencv-python would require numpy with version later than 1.11.1, I think this is what pip2 cannot do.

**Comment by ZiyuBao** [comment]
Okay, I fixed it. It tried to install numpy==1.17.3 but it couldn't. So I manually installed numpy==1.11.1 because any version later than or equal to 1.11.1 could work. After manually installing numpy==1.11.1, do "pip install -r requirements.txt" will not give you any error.
