### ISSUE TITLE
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.

### ISSUE THREAD

**Issue by ssunlin** [jwyang/faster-rcnn.pytorch#706]
Traceback (most recent call last):
  File "trainval_net.py", line 30, in <module>
    from model.utils.net_utils import weights_normal_init, save_net, load_net, \
  File "/app/pypro/det/faster-rcnn.pytorch/lib/model/utils/net_utils.py", line 8, in <module>
    from model.roi_crop.functions.roi_crop import RoICropFunction
  File "/app/pypro/det/faster-rcnn.pytorch/lib/model/roi_crop/functions/roi_crop.py", line 4, in <module>
    from .._ext import roi_crop
  File "/app/pypro/det/faster-rcnn.pytorch/lib/model/roi_crop/_ext/roi_crop/__init__.py", line 2, in <module>
    from torch.utils.ffi import _wrap_function
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.

**Comment by wtliao** [comment]
@ssunlin I have the same issue when running sh make.sh under lib/. Any idea to solve it?

**Comment by SWHL** [comment]
I have the same issue, and fing a solution https://github.com/pytorch/pytorch/issues/15645#issuecomment-466984786

**Comment by amiormu** [comment]
you can use torch= 0.4.0, torchvision=0.2.0, 
this question will be solved
