### ISSUE TITLE
run python setup.py build develop  return subprocess.CalledProcessError: Command '['which', '/usr/local/gcc-4.9.2/bin/g++']' returned non-zero exit status 1

### ISSUE THREAD

**Issue by xwzyb** [jwyang/faster-rcnn.pytorch#710]
when I run python setup.py build develop in lib , it returned following error:

running build_ext
Traceback (most recent call last):
  File "setup.py", line 66, in <module>
    cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
  File "/root/anaconda3/envs/train_detect_py3/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/root/anaconda3/envs/train_detect_py3/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/root/anaconda3/envs/train_detect_py3/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/root/anaconda3/envs/train_detect_py3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/root/anaconda3/envs/train_detect_py3/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/root/anaconda3/envs/train_detect_py3/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/root/anaconda3/envs/train_detect_py3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/root/anaconda3/envs/train_detect_py3/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/root/anaconda3/envs/train_detect_py3/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/root/anaconda3/envs/train_detect_py3/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/root/anaconda3/envs/train_detect_py3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 232, in build_extensions
    self._check_abi()
  File "/root/anaconda3/envs/train_detect_py3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 370, in _check_abi
    check_compiler_abi_compatibility(compiler)
  File "/root/anaconda3/envs/train_detect_py3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 162, in check_compiler_abi_compatibility
    if not check_compiler_ok_for_platform(compiler):
  File "/root/anaconda3/envs/train_detect_py3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 138, in check_compiler_ok_for_platform
    which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
  File "/root/anaconda3/envs/train_detect_py3/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/root/anaconda3/envs/train_detect_py3/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['which', '/usr/local/gcc-4.9.2/bin/g++']' returned non-zero exit status 1.

**Comment by xwzyb** [comment]
upgrade the gcc to 4.9 solved the problem
