### ISSUE TITLE
lib/model/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol

### ISSUE THREAD

**Issue by wtliao** [jwyang/faster-rcnn.pytorch#711]
Compile env:
torch=1.0.0
torchvision=0.2.1
python=3.6
OS = linux

When I try to run trainval_net.py, I have the following issue:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/liao/work_code/faster-rcnn.pytorch/lib/model/faster_rcnn/vgg16.py", line 16, in <module>
    from model.faster_rcnn.faster_rcnn import _fasterRCNN
  File "/home/liao/work_code/faster-rcnn.pytorch/lib/model/faster_rcnn/faster_rcnn.py", line 10, in <module>
    from model.rpn.rpn import _RPN
  File "/home/liao/work_code/faster-rcnn.pytorch/lib/model/rpn/rpn.py", line 8, in <module>
    from .proposal_layer import _ProposalLayer
  File "/home/liao/work_code/faster-rcnn.pytorch/lib/model/rpn/proposal_layer.py", line 21, in <module>
    from model.roi_layers import nms
  File "/home/liao/work_code/faster-rcnn.pytorch/lib/model/roi_layers/__init__.py", line 3, in <module>
    from .nms import nms
  File "/home/liao/work_code/faster-rcnn.pytorch/lib/model/roi_layers/nms.py", line 3, in <module>
    from model import _C
ImportError: /home/liao/work_code/faster-rcnn.pytorch/lib/model/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

I have tried all solutions given on #503 ,but none of them works for me. Anyone knows how to solve it? Thanks a lot

**Comment by DavidSongGitHub** [comment]
I got same problem

**Comment by wtliao** [comment]
> I got same problem

Have you solved it?
