### ISSUE TITLE
AssertionError: Path does not exist: /media/user1/storage-1/Devendra/faster_rcnn_2_jwyang/faster-rcnn.pytorch/data/VOCdevkit2007/VOC2007/JPEGImages/filename

### ISSUE THREAD

**Issue by devendraswamy** [jwyang/faster-rcnn.pytorch#717]
/media/user1/storage-1/V4_DATASET/new_annotation/train_person.txt data loaded
/media/user1/storage-1/V4_DATASET/new_annotation/test_person.txt data loaded

/media/user1/storage-1/Devendra/faster_rcnn_2_jwyang/faster-rcnn.pytorch/data/VOCdevkit2007/VOC2007 data path
Loaded dataset `voc_2007_train` for training
Set proposal method: gt
Appending horizontally-flipped training examples...
Traceback (most recent call last):
  File "trainval_net.py", line 203, in <module>
    imdb, roidb, ratio_list, ratio_index = combined_roidb(args.imdb_name)
  File "/media/user1/storage-1/Devendra/faster_rcnn_2_jwyang/faster-rcnn.pytorch/lib/roi_data_layer/roidb.py", line 116, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "/media/user1/storage-1/Devendra/faster_rcnn_2_jwyang/faster-rcnn.pytorch/lib/roi_data_layer/roidb.py", line 116, in <listcomp>
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "/media/user1/storage-1/Devendra/faster_rcnn_2_jwyang/faster-rcnn.pytorch/lib/roi_data_layer/roidb.py", line 113, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/media/user1/storage-1/Devendra/faster_rcnn_2_jwyang/faster-rcnn.pytorch/lib/roi_data_layer/roidb.py", line 97, in get_training_roidb
    imdb.append_flipped_images()
  File "/media/user1/storage-1/Devendra/faster_rcnn_2_jwyang/faster-rcnn.pytorch/lib/datasets/imdb.py", line 117, in append_flipped_images
    widths = self._get_widths()
  File "/media/user1/storage-1/Devendra/faster_rcnn_2_jwyang/faster-rcnn.pytorch/lib/datasets/imdb.py", line 113, in _get_widths
    for i in range(self.num_images)]
  File "/media/user1/storage-1/Devendra/faster_rcnn_2_jwyang/faster-rcnn.pytorch/lib/datasets/imdb.py", line 113, in <listcomp>
    for i in range(self.num_images)]
  File "/media/user1/storage-1/Devendra/faster_rcnn_2_jwyang/faster-rcnn.pytorch/lib/datasets/own_dataset.py", line 86, in image_path_at
    return self.image_path_from_index(self._image_index[i])
  File "/media/user1/storage-1/Devendra/faster_rcnn_2_jwyang/faster-rcnn.pytorch/lib/datasets/own_dataset.py", line 102, in image_path_from_index
    'Path does not exist: {}'.format(image_path)
AssertionError: Path does not exist: /media/user1/storage-1/Devendra/faster_rcnn_2_jwyang/faster-rcnn.pytorch/data/VOCdevkit2007/VOC2007/JPEGImages/filename

please help me to solve this error, I am try to training with my own dataset .

**Comment by ElsaReedz** [comment]
I have the same problem, did you solve it?

**Comment by devendraswamy** [comment]
That is the path error , i solved that error by adding my own file path , if your using pascal_voc dataset then please check dataset path and if it is not there then arrange based upon the error.

**Comment by ElsaReedz** [comment]
> That is the path error , i solved that error by adding my own file path , if your using pascal_voc dataset then please check dataset path and if it is not there then arrange based upon the error.

I solved that too, but cant remember the detail, like found myself creating soft link in the wrong path I suppose, seemingly the same way

**Comment by devendraswamy** [comment]
I thought soft link was not require and on which data you kept the training ? custom or pascal_voc

**Comment by ElsaReedz** [comment]
> I thought soft link was not require and on which data you kept the training ? custom or pascal_voc

pascal_voc, and I do remember when I encountered with this, I followed the tuturial in https://github.com/rbgirshick/py-faster-rcnn#beyond-the-demo-installation-for-training-and-testing-models and tried create the soft link  VOCdevkit2007 under /VOCdevkit, but failed to include the whole path so I created that in the wrong place, anyway I completed the path and this error no longer comes out again

**Comment by devendraswamy** [comment]
I need a one help , when i am kept the training with large data then my system was restarted. why its happening and its works for less data.

please help me to find the solution

**Comment by ElsaReedz** [comment]
> I need a one help , when i am kept the training with large data then my system was restarted. why its happening and its works for less data.
> 
> please help me to find the solution

I ran the whole project on a cloud server, trained with a large dataset of over 10k images while also a much smaller one containing only 270 which is made by my team, and did not encounter with such issue, so I may not able to be of help. I found some of my fellows met the same problem however, one of them checked his hardware and solve it
issue: https://blog.csdn.net/wuzuyu365/article/details/52212544
summary of related: https://blog.csdn.net/u011622208/article/details/90579252
hopefully it would help

**Comment by devendraswamy** [comment]
Thank you , the blogs are suggested to increase the power supply to GPU. ok i will try and if any other solution please drop here.

**Comment by devendraswamy** [comment]
File "/media/user1/storage-1/Devendra/TF_model/tf-faster-rcnn/tools/../lib/datasets/voc_eval.py", line 251, in voc_eval
if not R['det'][jmax]:
IndexError: list index out of range


please help ,Thanking you!!!
