### ISSUE TITLE
Error while finetuning with ResNet101 (KeyError: "filename 'storages' not found")

### ISSUE THREAD

**Issue by hamzarawal** [jwyang/faster-rcnn.pytorch#743]
I was finetuning my dataset with ResNet101. Testing works fine with the pre-trained weights, but when I start training, it gives the following error:

Preparing training data...
Extracting image sizes... (It may take long time)
Done!!
done
before filtering, there are 10022 images...
after filtering, there are 10022 images...
10022 roidb entries
Loading pretrained weights from data/pretrained_model/resnet101_caffe.pth
Traceback (most recent call last):
  File "trainval_net.py", line 249, in <module>
    fasterRCNN.create_architecture()
  File "/home/itu/hamza/thesis/faster-rcnn.pytorch/lib/model/faster_rcnn/faster_rcnn.py", line 135, in create_architecture
    self._init_modules()
  File "/home/itu/hamza/thesis/faster-rcnn.pytorch/lib/model/faster_rcnn/resnet.py", line 244, in _init_modules
    state_dict = torch.load(self.model_path)
  File "/home/itu/virtual_envs/frcnn/lib/python3.6/site-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "/home/itu/virtual_envs/frcnn/lib/python3.6/site-packages/torch/serialization.py", line 454, in _load
    return legacy_load(f)
  File "/home/itu/virtual_envs/frcnn/lib/python3.6/site-packages/torch/serialization.py", line 383, in legacy_load
    tar.extract('storages', path=tmpdir)
  File "/home/itu/virtual_envs/frcnn/lib/python3.6/tarfile.py", line 2041, in extract
    tarinfo = self.getmember(member)
  File "/home/itu/virtual_envs/frcnn/lib/python3.6/tarfile.py", line 1752, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename 'storages' not found"

**Comment by Zpadger** [comment]
You need to modify the class name of the 48th line in'lib/datasets/pascal_voc.py', and modify it according to your data set category name
