### ISSUE TITLE
Windows No module named 'pycocotools._mask'

### ISSUE THREAD

**Issue by GrassGuo7** [jwyang/faster-rcnn.pytorch#765]
when I run trainval_net.py --dateset pascal_voc --net vgg16 --bs 4 --nw 1 --lr 0.004 --lr_decay_step 8 --cuda ,a error occuers.However,the pycocotools has been installed in the pytorch lib and removed from the local file path faster-rcnn.pytorch1.0.

**Comment by loolzaaa** [comment]
Can you leave full stack trace here?

**Comment by 52lly** [comment]
Traceback (most recent call last):
  File "E:/pycode/faster-rcnn.pytorch-pytorch-1.0/trainval_net.py", line 27, in <module>
    from roi_data_layer.roidb import combined_roidb
  File "E:\pycode\faster-rcnn.pytorch-pytorch-1.0\lib\roi_data_layer\roidb.py", line 9, in <module>
    from datasets.factory import get_imdb
  File "E:\pycode\faster-rcnn.pytorch-pytorch-1.0\lib\datasets\factory.py", line 15, in <module>
    from datasets.coco import coco
  File "E:\pycode\faster-rcnn.pytorch-pytorch-1.0\lib\datasets\coco.py", line 23, in <module>
    from pycocotools.coco import COCO
  File "E:\pycode\faster-rcnn.pytorch-pytorch-1.0\lib\pycocotools\coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "E:\pycode\faster-rcnn.pytorch-pytorch-1.0\lib\pycocotools\mask.py", line 3, in <module>
    import pycocotools._mask as _mask
ModuleNotFoundError: No module named 'pycocotools._mask'

i have same problem like this

**Comment by stekau** [comment]
python trainval_net.py --dataset pascal_voc --net vgg16 --bs 24 --nw 1 --lr 0.001 --lr_decay_step 8 --cuda

Traceback (most recent call last):
  File "trainval_net.py", line 27, in <module>
    from roi_data_layer.roidb import combined_roidb
  File "C:\Users\AI\PycharmProjects\faster-rcnn.pytorch\lib\roi_data_layer\roidb.py", line 9, in <module>
    from datasets.factory import get_imdb
  File "C:\Users\AI\PycharmProjects\faster-rcnn.pytorch\lib\datasets\factory.py", line 15, in <module>
    from datasets.coco import coco
  File "C:\Users\AI\PycharmProjects\faster-rcnn.pytorch\lib\datasets\coco.py", line 23, in <module>
    from pycocotools.coco import COCO
  File "C:\Users\AI\PycharmProjects\faster-rcnn.pytorch\lib\pycocotools\coco.py", line 60, in <module>
    from . import mask
  File "C:\Users\AI\PycharmProjects\faster-rcnn.pytorch\lib\pycocotools\mask.py", line 3, in <module>
    from . import _mask
ImportError: cannot import name '_mask' from 'pycocotools' (C:\Users\AI\PycharmProjects\faster-rcnn.pytorch\lib\pycocotools\__init__.py)

I also have the same problem. Does anybody have some recommendations?

**Comment by ppte93** [comment]
> python trainval_net.py --dataset pascal_voc --net vgg16 --bs 24 --nw 1 --lr 0.001 --lr_decay_step 8 --cuda
> 
> Traceback (most recent call last):
> File "trainval_net.py", line 27, in
> from roi_data_layer.roidb import combined_roidb
> File "C:\Users\AI\PycharmProjects\faster-rcnn.pytorch\lib\roi_data_layer\roidb.py", line 9, in
> from datasets.factory import get_imdb
> File "C:\Users\AI\PycharmProjects\faster-rcnn.pytorch\lib\datasets\factory.py", line 15, in
> from datasets.coco import coco
> File "C:\Users\AI\PycharmProjects\faster-rcnn.pytorch\lib\datasets\coco.py", line 23, in
> from pycocotools.coco import COCO
> File "C:\Users\AI\PycharmProjects\faster-rcnn.pytorch\lib\pycocotools\coco.py", line 60, in
> from . import mask
> File "C:\Users\AI\PycharmProjects\faster-rcnn.pytorch\lib\pycocotools\mask.py", line 3, in
> from . import _mask
> ImportError: cannot import name '_mask' from 'pycocotools' (C:\Users\AI\PycharmProjects\faster-rcnn.pytorch\lib\pycocotools__init__.py)
> 
> I also have the same problem. Does anybody have some recommendations?

Did you figure it out?

**Comment by ppte93** [comment]
> python trainval_net.py --dataset pascal_voc --net vgg16 --bs 24 --nw 1 --lr 0.001 --lr_decay_step 8 --cuda
> 
> Traceback (most recent call last):
> File "trainval_net.py", line 27, in
> from roi_data_layer.roidb import combined_roidb
> File "C:\Users\AI\PycharmProjects\faster-rcnn.pytorch\lib\roi_data_layer\roidb.py", line 9, in
> from datasets.factory import get_imdb
> File "C:\Users\AI\PycharmProjects\faster-rcnn.pytorch\lib\datasets\factory.py", line 15, in
> from datasets.coco import coco
> File "C:\Users\AI\PycharmProjects\faster-rcnn.pytorch\lib\datasets\coco.py", line 23, in
> from pycocotools.coco import COCO
> File "C:\Users\AI\PycharmProjects\faster-rcnn.pytorch\lib\pycocotools\coco.py", line 60, in
> from . import mask
> File "C:\Users\AI\PycharmProjects\faster-rcnn.pytorch\lib\pycocotools\mask.py", line 3, in
> from . import _mask
> ImportError: cannot import name '_mask' from 'pycocotools' (C:\Users\AI\PycharmProjects\faster-rcnn.pytorch\lib\pycocotools__init__.py)
> 
> I also have the same problem. Does anybody have some recommendations?

Did you figure it out?
