### ISSUE TITLE
KeyError: '006256'

### ISSUE THREAD

**Issue by shehuimao** [jwyang/faster-rcnn.pytorch#777]
when I run test_net.py, I meet the follow bugs:

Traceback (most recent call last):
  File "test_net.py", line 328, in <module>
    imdb.evaluate_detections(all_boxes, output_dir)
  File "/home/mao/PycharmProjects/faster-rcnn.pytorch/lib/datasets/pascal_voc.py", line 367, in evaluate_detections
    self._do_python_eval(output_dir)
  File "/home/mao/PycharmProjects/faster-rcnn.pytorch/lib/datasets/pascal_voc.py", line 330, in _do_python_eval
    use_07_metric=use_07_metric)
  File "/home/mao/PycharmProjects/faster-rcnn.pytorch/lib/datasets/voc_eval.py", line 134, in voc_eval
    R = [obj for obj in recs[imagename] if (obj['name']).lower() == classname]
KeyError: '006256'

**Comment by loolzaaa** [comment]
Looks like you correct test image set file.

May be you need to clean annotations cache file from cache dir?

By default, devkit_path -> annotations_cache ...
