### ISSUE TITLE
Not compiled with GPU support (nms at /home/yuezhangw/Program/Faster_RCNN_torch101/faster-rcnn.pytorch/lib/model/csrc/nms.h:22)

### ISSUE THREAD

**Issue by YueZhangX** [jwyang/faster-rcnn.pytorch#793]
The processing of compiling is successful, without errors but a warning:
**command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++**

Then, when I try **train_val.py**, errors occured:
**Not compiled with GPU support (nms at /home/yuezhangw/Program/Faster_RCNN_torch101/faster-rcnn.pytorch/lib/model/csrc/nms.h:22)**

it seems like that i had not compiled nms into GPU env, but the compiling was no error.
i used py36 to complie, maybe i should try py27?As a new hand, I don't know how to use a different version Python in one env, one for complie, one for run program?

SO, anyone had the same problem?Thanks for the helping!

**Comment by loolzaaa** [comment]
Do you have _C........pyd file after compiling in /lib or more deep folder?

**Comment by YueZhangX** [comment]
> Do you have _C........pyd file after compiling in /lib or more deep folder?

yes, but it didn't work

**Comment by loolzaaa** [comment]
It seems that code can't detect CUDA device.
`torch.cuda.is_available()` return True for you?

**Comment by YueZhangX** [comment]
> It seems that code can't detect CUDA device.
> `torch.cuda.is_available()` return True for you?
> 
> If yes, try to remove `CUDA_HOME` from [this](https://github.com/jwyang/faster-rcnn.pytorch/blob/6f0c63b64dde6dc4eb3e24f90650d789f96f4c75/lib/setup.py#L31) line.
> 
> Of course, i hope you use PyTorch 1.0 branch.

maybe you are right, i will try it tomorrow! Much thanks to your reply!

**Comment by YueZhangX** [comment]
> It seems that code can't detect CUDA device.
> `torch.cuda.is_available()` return True for you?
> 
> If yes, try to remove `CUDA_HOME` from [this](https://github.com/jwyang/faster-rcnn.pytorch/blob/6f0c63b64dde6dc4eb3e24f90650d789f96f4c75/lib/setup.py#L31) line.
> 
> Of course, i hope you use PyTorch 1.0 branch.

**if torch.cuda.is_available() and CUDA_HOME is not None**
I try to remove part of this, and it turns to

**if torch.cuda.is_available()** , **torch.cuda.is_available()** always returns Ture

then I run the file setup.py again, error occurs:

Traceback (most recent call last):
  File "setup.py", line 65, in <module>
    ext_modules=get_extensions(),
  File "setup.py", line 52, in get_extensions
    extra_compile_args=extra_compile_args,
  File "/home/yuezhangw/anaconda3/envs/py36_torch101_cuda90/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 476, in CUDAExtension
    library_dirs += library_paths(cuda=True)
  File "/home/yuezhangw/anaconda3/envs/py36_torch101_cuda90/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 549, in library_paths
    paths.append(_join_cuda_home(lib_dir))
  File "/home/yuezhangw/anaconda3/envs/py36_torch101_cuda90/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1121, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
(py36_torch101_cuda90) yuezhangw@yuezhangw-PC:~/Program/Faster_RCNN_torch101/faster-rcnn.pytorch/lib$ python setup.py build develop
Traceback (most recent call last):
  File "setup.py", line 65, in <module>
    ext_modules=get_extensions(),
  File "setup.py", line 52, in get_extensions
    extra_compile_args=extra_compile_args,
  File "/home/yuezhangw/anaconda3/envs/py36_torch101_cuda90/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 476, in CUDAExtension
    library_dirs += library_paths(cuda=True)
  File "/home/yuezhangw/anaconda3/envs/py36_torch101_cuda90/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 549, in library_paths
    paths.append(_join_cuda_home(lib_dir))
  File "/home/yuezhangw/anaconda3/envs/py36_torch101_cuda90/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1121, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
(py36_torch101_cuda90) yuezhangw@yuezhangw-PC:~/Program/Faster_RCNN_torch101/faster-rcnn.pytorch/lib$ python setup.py build develop
yes
Traceback (most recent call last):
  File "setup.py", line 66, in <module>
    ext_modules=get_extensions(),
  File "setup.py", line 53, in get_extensions
    extra_compile_args=extra_compile_args,
  File "/home/yuezhangw/anaconda3/envs/py36_torch101_cuda90/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 476, in CUDAExtension
    library_dirs += library_paths(cuda=True)
  File "/home/yuezhangw/anaconda3/envs/py36_torch101_cuda90/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 549, in library_paths
    paths.append(_join_cuda_home(lib_dir))
  File "/home/yuezhangw/anaconda3/envs/py36_torch101_cuda90/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1121, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

do you know how to deal with it?Thank you ever so much

**Comment by loolzaaa** [comment]
Ok, i see. You use anaconda and i suppose you install CUDA through it, so it is not the entire package.

Install CUDA drivers manually https://developer.nvidia.com/cuda-downloads

After installation, pytorch would be able to access the CUDA path. You can check it:
```python
import os
print(os.environ.get('CUDA_PATH')
```

**Comment by Chenlei6** [comment]
Excuse me! I meet the same problem with yours, do you solve it now? if yes, please share the solution, thanks!

**Comment by yuezhangW** [comment]
> Excuse me! I meet the same problem with yours, do you solve it now? if yes, please share the solution, thanks!

sorry,i did not solve it till now

**Comment by xxxjw-fighting** [comment]
Before compiling _setup.py_, you should make sure that _print(torch.cuda.is_available())_ returns True.
I've solved this problem!

**Comment by DarkFlameSword** [comment]
> The processing of compiling is successful, without errors but a warning: **command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++**
> 
> Then, when I try **train_val.py**, errors occured: **Not compiled with GPU support (nms at /home/yuezhangw/Program/Faster_RCNN_torch101/faster-rcnn.pytorch/lib/model/csrc/nms.h:22)**
> 
> it seems like that i had not compiled nms into GPU env, but the compiling was no error. i used py36 to complie, maybe i should try py27?As a new hand, I don't know how to use a different version Python in one env, one for complie, one for run program?
> 
> SO, anyone had the same problem?Thanks for the helping!

I also encountered the same question, I struggle in this problem for a long time, so I want to know were you fix this problem?
