### ISSUE TITLE
LinkError: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by ChuanchuanZheng** [jwyang/faster-rcnn.pytorch#795]
gcc -pthread -shared -std=c99 ./_nms.o ./home/ssd1/test/faster-rcnn.pytorch/lib/model/nms/src/nms_cuda.o /home/ssd1/test/faster-rcnn.pytorch/lib/model/nms/src/nms_cuda_kernel.cu.o -L/home/work/python/build/lib -lpython2.7 -o ./_nms.so
/usr/bin/ld: cannot find -lpython2.7
collect2: ld returned 1 exit status
Traceback (most recent call last):
  File "build.py", line 37, in <module>
    ffi.build()
  File "/home/work/python_env/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 184, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/work/python_env/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 108, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/work/python_env/lib/python2.7/site-packages/cffi/api.py", line 684, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/work/python_env/lib/python2.7/site-packages/cffi/recompiler.py", line 1484, in recompile
    compiler_verbose, debug)
  File "/home/work/python_env/lib/python2.7/site-packages/cffi/ffiplatform.py", line 20, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/work/python_env/lib/python2.7/site-packages/cffi/ffiplatform.py", line 56, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: LinkError: command 'gcc' failed with exit status 1

Using torch 0.4.0  CUDA 9.0 -arch sm_61 and modify the CUDA path and python path, but this LinkError remains not solved. Anyone can give me any suggestion?

**Comment by xxxjw-fighting** [comment]
Try to update gcc.
