### ISSUE TITLE
Compiling Issue - Branche: pytorch-1.0 - lib/setup.py

### ISSUE THREAD

**Issue by stekau** [jwyang/faster-rcnn.pytorch#804]
I started the setup.py for compilation in the lib direction. The compilation of the code seemed to work fine until a error occured:

4 errors detected in the compilation of "C:/Users/AI/AppData/Local/Temp/tmpxft_000009b0_00000000-10_ROIAlign_cuda.cpp1.ii".
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.2\\bin\\nvcc.exe' failed with exit status 1

Does anybody have an idea how I can fix the problem? 
My environment uses the following packages:
pytorch 1.2.0
torchvision 0.4.0
cudatoolkit 10.0
python -> 3.7
OS -> Win10

Because of this error I do not get the _C file necessary to train the network as described in #503.
As described in #503 I get the following error message:

python trainval_net.py --dataset pascal_voc --net vgg16 --bs 24 --nw 1 --lr 0.001 --lr_decay_step 8 --cuda

Traceback (most recent call last):
  File "trainval_net.py", line 33, in <module>
    from model.faster_rcnn.vgg16 import vgg16
  File "C:\Users\AI\PycharmProjects\faster-rcnn.pytorch\lib\model\faster_rcnn\vgg16.py", line 16, in <module>
    from model.faster_rcnn.faster_rcnn import _fasterRCNN
  File "C:\Users\AI\PycharmProjects\faster-rcnn.pytorch\lib\model\faster_rcnn\faster_rcnn.py", line 10, in <module>
    from model.rpn.rpn import _RPN
  File "C:\Users\AI\PycharmProjects\faster-rcnn.pytorch\lib\model\rpn\rpn.py", line 8, in <module>
    from .proposal_layer import _ProposalLayer
  File "C:\Users\AI\PycharmProjects\faster-rcnn.pytorch\lib\model\rpn\proposal_layer.py", line 21, in <module>
    from model.roi_layers import nms
  File "C:\Users\AI\PycharmProjects\faster-rcnn.pytorch\lib\model\roi_layers\__init__.py", line 3, in <module>
    from .nms import nms
  File "C:\Users\AI\PycharmProjects\faster-rcnn.pytorch\lib\model\roi_layers\nms.py", line 3, in <module>
    from model import _C
ImportError: cannot import name '_C' from 'model' (C:\Users\Steffen\PycharmProjects\faster-rcnn.pytorch\lib\model\__init__.py)

If anybody have some recommendations on this problem I would appreciate. 
Thanks in advance.

**Comment by stekau** [comment]
I found a solution for the problem.
https://github.com/facebookresearch/maskrcnn-benchmark/issues/254
and 
https://github.com/facebookresearch/maskrcnn-benchmark/pull/271/files
