### ISSUE TITLE
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.

### ISSUE THREAD

**Issue by xQsM3** [jwyang/faster-rcnn.pytorch#826]
**issue**
 while running:
`bash travis.sh `

results in error:

`Working directory:  /home/xqsme/TrackerPackageDRNet/DRNet/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src
Compiling prroi_pooling kernels by nvcc...
Working directory:  /home/xqsme/TrackerPackageDRNet/DRNet/ltr/external/PreciseRoIPooling/pytorch/prroi_pool
Building python libraries...
Traceback (most recent call last):
  File "build.py", line 15, in <module>
    from torch.utils.ffi import create_extension
  File "/home/xqsme/anaconda3/envs/pytracking/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.`

**to reproduce**
Ubuntu 20.04
python 3.7
 CUDA 10.1
pytorch==1.5.1 
torchvision==0.6.1 
cudatoolkit=10.1

before, i also tried this:
https://github.com/visionml/pytracking/tree/pytorch041 which is running on pytorch 0.4.1 and supposed to work on ubuntu 18, doesnt work for me tho, too. 

 I also tried torch= 0.4.0, torchvision=0.2.0 according to https://github.com/jwyang/faster-rcnn.pytorch/issues/706 but it doesnt support python 3.7.

Is there any solution for this issue?

**Comment by kesaroid** [comment]
Hey @xQsM3, were you able to solve this issue by downgrading torch version?

**Comment by ajithvcoder** [comment]
@xQsM3  install torch==0.4.0

**Comment by kesaroid** [comment]
The pytorch-1.0 branch works fine. I used torch=1.1.0 with that.

**Comment by ajithvcoder** [comment]
okay thanks @kesaroid
