### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by Jezzzzz** [jwyang/faster-rcnn.pytorch#833]
Traceback (most recent call last):
  File "/faster-rcnn.pytorch-pytorch-1.0/lib/datasets/voc_eval.py", line 124, in voc_eval
    recs = pickle.load(f)
EOFError: Ran out of input

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_net.py", line 325, in <module>
    imdb.evaluate_detections(all_boxes, output_dir)
  File "/faster-rcnn.pytorch-pytorch-1.0/lib/datasets/pascal_voc.py", line 346, in evaluate_detections
    self._do_python_eval(output_dir)
  File "/faster-rcnn.pytorch-pytorch-1.0/lib/datasets/pascal_voc.py", line 309, in _do_python_eval
    use_07_metric=use_07_metric)
  File "/faster-rcnn.pytorch-pytorch-1.0/lib/datasets/voc_eval.py", line 126, in voc_eval
    recs = pickle.load(f, encoding='bytes')
EOFError: Ran out of input

when I run test_net.py, I encountered the question. How to solve it?

**Comment by caizhaoxin** [comment]
Same issue. Help!
