### ISSUE TITLE
meet this error when train faster rcnn with voc2007

### ISSUE THREAD

**Issue by ShelbyXu9** [jwyang/faster-rcnn.pytorch#857]
freshman to training faster rcnn with vpc2007.
CUDA_VISIBLE_DEVICES=0 python trainval_net.py --dataset pascal_voc --net vgg16  --bs 1 --nw 1 --cuda
get the following mistake:
Traceback (most recent call last):
  File "trainval_net.py", line 186, in <module>
    imdb, roidb, ratio_list, ratio_index = combined_roidb(args.imdb_name)
  File "/home/ray/Documents/Detection-PyTorch-Notebook/chapter4/faster-rcnn-pytorch/lib/roi_data_layer/roidb.py", line 116, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "/home/ray/Documents/Detection-PyTorch-Notebook/chapter4/faster-rcnn-pytorch/lib/roi_data_layer/roidb.py", line 116, in <listcomp>
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "/home/ray/Documents/Detection-PyTorch-Notebook/chapter4/faster-rcnn-pytorch/lib/roi_data_layer/roidb.py", line 109, in get_roidb
    imdb = get_imdb(imdb_name)
  File "/home/ray/Documents/Detection-PyTorch-Notebook/chapter4/faster-rcnn-pytorch/lib/datasets/factory.py", line 66, in get_imdb
    return __sets[name]()
  File "/home/ray/Documents/Detection-PyTorch-Notebook/chapter4/faster-rcnn-pytorch/lib/datasets/factory.py", line 25, in <lambda>
    __sets[name] = (lambda split=split, year=year: pascal_voc(split, year))
  File "/home/ray/Documents/Detection-PyTorch-Notebook/chapter4/faster-rcnn-pytorch/lib/datasets/pascal_voc.py", line 58, in __init__
    self._image_index = self._load_image_set_index()
  File "/home/ray/Documents/Detection-PyTorch-Notebook/chapter4/faster-rcnn-pytorch/lib/datasets/pascal_voc.py", line 109, in _load_image_set_index
    'Path does not exist: {}'.format(image_set_file)
AssertionError: Path does not exist: /root/Detection-PyTorch-Notebook/chapter4/faster-rcnn-pytorch/data/VOC2012/ImageSets/Main/trainval.txt

how could i solve this problem?

**Comment by ShelbyXu9** [comment]
why i got the "/root/Detection-PyTorch-Notebook/chapter4``````"
