### ISSUE TITLE
sh make.sh (mingw 64 in windows10)

### ISSUE THREAD

**Issue by fangzhouAlonso** [jwyang/faster-rcnn.pytorch#878]
i download a mingw 64 to run the "sh make.sh".
but there is something wrong, anyone could help me? tks a lot!

$ sh make.sh
running build_ext
Traceback (most recent call last):
  File "setup.py", line 138, in <module>
    cmdclass={'build_ext': custom_build_ext},
  File "F:\fz\anaconda3\lib\site-packages\setuptools\__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "F:\fz\anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "F:\fz\anaconda3\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "F:\fz\anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "F:\fz\anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "F:\fz\anaconda3\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "setup.py", line 114, in build_extensions
    customize_compiler_for_nvcc(self.compiler)
  File "setup.py", line 86, in customize_compiler_for_nvcc
    default_compiler_so = self.compiler_so
AttributeError: 'MSVCCompiler' object has no attribute 'compiler_so'
Compiling nms kernels by nvcc...
nvcc fatal   : Cannot find compiler 'cl.exe' in PATH
Traceback (most recent call last):
  File "build.py", line 4, in <module>
    from torch.utils.ffi import create_extension
  File "F:\fz\anaconda3\lib\site-packages\torch\utils\ffi\__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
Compiling roi pooling kernels by nvcc...
nvcc fatal   : Cannot find compiler 'cl.exe' in PATH
Traceback (most recent call last):
  File "build.py", line 4, in <module>
    from torch.utils.ffi import create_extension
  File "F:\fz\anaconda3\lib\site-packages\torch\utils\ffi\__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
Compiling roi align kernels by nvcc...
nvcc fatal   : Cannot find compiler 'cl.exe' in PATH
Traceback (most recent call last):
  File "build.py", line 4, in <module>
    from torch.utils.ffi import create_extension
  File "F:\fz\anaconda3\lib\site-packages\torch\utils\ffi\__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
Compiling roi crop kernels by nvcc...
nvcc fatal   : Cannot find compiler 'cl.exe' in PATH
Traceback (most recent call last):
  File "build.py", line 4, in <module>
    from torch.utils.ffi import create_extension
  File "F:\fz\anaconda3\lib\site-packages\torch\utils\ffi\__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.

**Comment by CalvinSpol** [comment]
try installing torch==0.4.0

**Comment by Lyhour-Chhay** [comment]
you can create the python file : ffiext.py with the link code below. Copy it to location torch/utils/. In your coding change the statement torch.utils.ffiext.
https://gwnuackr-my.sharepoint.com/:u:/g/personal/lyhour_gwnu_ac_kr/EbpNHQUUbQNIhxBzTbEU7RQBLOI14L390ipZYUB7xYNp0w?e=QmqWBg

**Comment by fangzhouAlonso** [comment]
> try installing torch==0.4.0

thanks!

**Comment by fangzhouAlonso** [comment]
> you can create the python file : ffiext.py with the link code below. Copy it to location torch/utils/. In your coding change the statement torch.utils.ffiext. https://gwnuackr-my.sharepoint.com/:u:/g/personal/lyhour_gwnu_ac_kr/EbpNHQUUbQNIhxBzTbEU7RQBLOI14L390ipZYUB7xYNp0w?e=QmqWBg

thanks! i have solved it!
